3-TronyaginaAlexandra-B12
motorny/alg-dstruct pull request #106
Opened 2021-11-03 14:13 UTC by tronyaginaa

# Чек-лист для сдачи лабораторной

Список для проверки того, что вы ничего не забыли перед тем, как сдать лабораторную.

- [ ] Создан файл ридми с текстом задания лабораторной
- [ ] Директория с лабораторной называется согласно паттерну `<group_number>-<NameSurname>-<lab_variant>` (Пример: `1-NikitaLanskov-A26`). Это важно, такое название позволяет автоматически назначить в ревью нужного человека.
- [ ] Создан файл .gitignore в директории с лабораторной, в котором перечислены все вспомогательные файлы от visual studio
- [ ] В Pull Request отсутсвуют лишние файлы: сторонние библиотеки, их исходный код, собранные бинарные файлы вашей программы, ваши конфигурационные файлы IDE. В большинстве случаев в PR будет не более 10-15 файлов
- [ ] В Pull Request включены файлы только относящиеся к текущей лабораторной. Чтобы лабы не смешивались, создавайте новую ветвь для каждой лабы
- [ ] Написаны юнит-тесты для всех функций, подлежащих тестированию согласно памятке
- [ ] Пройдены тесты в системе проверки (для второй лабораторной и выше)
- [ ] Код написан в едином стиле

# Дополнительные комментарии к решению

2021-11-05 11:27 UTC, maik-nack requested changes
Проверьте использование функции `memgetblocksize`. В некоторых местах нужно использовать `memgetminimumsize`

2021-11-05 11:27 UTC, maik-nack commented on 3-TronyaginaAlexandra-B12/aaaaaaaaa/3-Tronyagina-B12.c
> +        actualDescriptor = *blockPtr(usedDescriptor);
А если `usedDescriptor` был разделён на два блока, то откуда должен начинаться поиск в следующий раз?

2021-11-05 11:27 UTC, maik-nack commented on 3-TronyaginaAlexandra-B12/aaaaaaaaa/3-Tronyagina-B12.c
> +            *blockPtr(prevDescriptor) = newDescriptor;
А что будет, если `usedDescriptor` будет равен `actualDescriptor`?

2021-11-05 18:51 UTC, tronyaginaa commented
Исправила Ваши замечания. 
После исправлений 26-й тест все равно не проходит(

2021-11-07 13:02 UTC, maik-nack requested changes
Вы не всё исправили!

2021-11-11 19:03 UTC, maik-nack reviewed
Окей, лабораторная зачтена! Есть правда кусок кода, который повторяется, но это ничего не ломает.

2021-11-11 19:03 UTC, closed without merging