3-BoitsovAnton-B17
motorny/alg-dstruct pull request #113
Opened 2021-11-05 16:34 UTC by d3biruwan

# Чек-лист для сдачи лабораторной

Список для проверки того, что вы ничего не забыли перед тем, как сдать лабораторную.

- [ ] Создан файл ридми с текстом задания лабораторной
- [ ] Директория с лабораторной называется согласно паттерну `<group_number>-<NameSurname>-<lab_variant>` (Пример: `1-NikitaLanskov-A26`). Это важно, такое название позволяет автоматически назначить в ревью нужного человека.
- [ ] Создан файл .gitignore в директории с лабораторной, в котором перечислены все вспомогательные файлы от visual studio
- [ ] В Pull Request отсутсвуют лишние файлы: сторонние библиотеки, их исходный код, собранные бинарные файлы вашей программы, ваши конфигурационные файлы IDE. В большинстве случаев в PR будет не более 10-15 файлов
- [ ] В Pull Request включены файлы только относящиеся к текущей лабораторной. Чтобы лабы не смешивались, создавайте новую ветвь для каждой лабы
- [ ] Написаны юнит-тесты для всех функций, подлежащих тестированию согласно памятке
- [ ] Пройдены тесты в системе проверки (для второй лабораторной и выше)
- [ ] Код написан в едином стиле

# Дополнительные комментарии к решению

Тут вы можете добавить дополнительные пояснения к решению вашего варианта лабораторной.

Различные сравнения и прочее.

2021-11-06 23:23 UTC, maik-nack requested changes
Исправьте, пожалуйста, замечания

1. Проверьте расстановку фигурных скобок
2. Проверьте наименование своих переменных
3. Свои функции Вы решили называть так же, как названы функции в `memallocator.h`, но не все функции названы в таком стиле
4. Унифицируйте проверку указателя на `NULL`

2021-11-06 23:23 UTC, maik-nack commented on 3-Boitsov-B17/src/MemorySystem.cpp
> +void  memfree(void* p) {
Здесь есть пробел, которого нет в других объявлениях функций

2021-11-10 08:34 UTC, maik-nack requested changes
Проверки указателей на `NULL` до сих пор различаются, а переменные названы в разных стилях.

2021-11-10 10:48 UTC, d3biruwan commented
Имена переменных я исправил, но я не знаю, что делать с проверкой указателей на NULL. В прошлый раз у меня были проверки через != и == в разных местах, я подумал, что вы это имеете в виду под унификацией проверок указателей, и поменял все на ==.

2021-11-10 22:19 UTC, maik-nack commented
Получается, что Вы хотите проверять на `NULL` через `!=` или `==`. Но есть пара мест, где Вы пользуетесь приведением указателя к булевому типу вместо того, что сравнить его с `NULL`.

2021-11-11 11:13 UTC, d3biruwan commented
Проверку указателей исправил.

2021-11-11 14:43 UTC, maik-nack reviewed
Хорошо, лабораторная зачтена, но следите за пробелами и в целом за стилем кодирования.

2021-11-11 14:44 UTC, closed without merging