3 rubanova valeria c4
motorny/alg-dstruct pull request #114
Opened 2021-11-05 18:42 UTC by riapush

# Чек-лист для сдачи лабораторной

Список для проверки того, что вы ничего не забыли перед тем, как сдать лабораторную.

- [ ] Создан файл ридми с текстом задания лабораторной
- [ ] Директория с лабораторной называется согласно паттерну `<group_number>-<NameSurname>-<lab_variant>` (Пример: `1-NikitaLanskov-A26`). Это важно, такое название позволяет автоматически назначить в ревью нужного человека.
- [ ] Создан файл .gitignore в директории с лабораторной, в котором перечислены все вспомогательные файлы от visual studio
- [ ] В Pull Request отсутсвуют лишние файлы: сторонние библиотеки, их исходный код, собранные бинарные файлы вашей программы, ваши конфигурационные файлы IDE. В большинстве случаев в PR будет не более 10-15 файлов
- [ ] В Pull Request включены файлы только относящиеся к текущей лабораторной. Чтобы лабы не смешивались, создавайте новую ветвь для каждой лабы
- [ ] Написаны юнит-тесты для всех функций, подлежащих тестированию согласно памятке
- [ ] Пройдены тесты в системе проверки (для второй лабораторной и выше)
- [ ] Код написан в едином стиле

# Дополнительные комментарии к решению

Тут вы можете добавить дополнительные пояснения к решению вашего варианта лабораторной.

Различные сравнения и прочее.

2021-11-06 09:43 UTC, riapush commented
Имя устройства	LAPTOP-F07HB6MN
Процессор	AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx     2.10 GHz
Оперативная память	8,00 ГБ (доступно: 6,94 ГБ)
Код продукта	00342-41414-59145-AAOEM
Тип системы	64-разрядная операционная система, процессор x64

2021-11-07 11:48 UTC, maik-nack requested changes
Исправьте, пожалуйста, замечания

1. Нагрузочный тест должен быть написан с помощью библиотеки GTest
2. Проверьте расстановку фигурных скобок в ветвлениях с одной командой
3. Нет инициализации значений ячеек tree
4. Присутствуют возможные утечки памяти

2021-11-07 11:48 UTC, maik-nack commented on 3-Rubanova-C4/3-Rubanova-C4/LabC.c
> +		return 0;
Код ошибки совпадает с тем, что очередь не пуста

2021-11-07 11:48 UTC, maik-nack commented on 3-Rubanova-C4/3-Rubanova-C4/LabC.c
> +void insert(queue* q, int vertex) {
Невозможно узнать, была ли вставка успешной

2021-11-11 09:54 UTC, riapush commented
не уверена, что все возможные утечки памяти исправлены, подскажите, пожалуйста, если надо что-то еще изменить

2021-11-13 15:45 UTC, maik-nack requested changes
Исправьте, пожалуйста, замечания

Присутствуют файлы, не относящиеся к данной лабораторной

2021-11-13 15:45 UTC, maik-nack commented on 3-Rubanova-C4/3-Rubanova-C4/StressTest/test.cpp
> +			tree[i][j] = rand() % 2;
Отсутствует симметричное заполнение матрицы смежности

2021-11-13 15:45 UTC, maik-nack commented on 3-Rubanova-C4/3-Rubanova-C4/StressTest/test.cpp
> +TEST(bfsStressTest, stressTest) {
И сколько же времени и памяти занимает этот тест?

2021-11-13 15:45 UTC, maik-nack commented on 3-Rubanova-C4/3-Rubanova-C4/3-Rubanova-C4/LabCfunc.c
> +int breadthFirstSearch(int vertex) {
Присутствуют возможные утечки памяти в этой функции

2021-11-13 15:45 UTC, maik-nack commented on 3-Rubanova-C4/3-Rubanova-C4/LabC_realization/LabC.c
> +int main(void) {
В этой функции присутствуют возможные утечки памяти

2021-11-15 10:48 UTC, riapush commented on 3-Rubanova-C4/3-Rubanova-C4/StressTest/test.cpp
> +TEST(bfsStressTest, stressTest) {
По памяти: 866,4Мб
По времени: 55.625000 секунд

2021-11-20 16:45 UTC, maik-nack requested changes
Исправьте, пожалуйста, замечания

2021-11-20 16:45 UTC, maik-nack commented on 3-Rubanova-C4/3-Rubanova-C4/3-Rubanova-C4Test/test.cpp
> +TEST(bfsStressTest, stressTest) {
В этом тесте возможно исключение о доступе к памяти

2021-11-20 16:45 UTC, maik-nack commented on 3-Rubanova-C4/3-Rubanova-C4/3-Rubanova-C4/LabCfunc.c
> +int breadthFirstSearch(int vertex) {
Утечки памяти до сих пор присутствуют

2021-11-21 20:24 UTC, maik-nack requested changes

2021-11-21 20:24 UTC, maik-nack commented on 3-Rubanova-C4/3-Rubanova-C4/3-Rubanova-C4Test/test.cpp
> +TEST(bfsStressTest, stressTest) {
Не исправлено!

2021-11-23 20:44 UTC, maik-nack reviewed
Ок, лабораторная зачтена!

2021-11-23 20:44 UTC, closed without merging