3-Zinyakova-C2
motorny/alg-dstruct pull request #115
Opened 2021-11-05 21:41 UTC by KateZin

# Чек-лист для сдачи лабораторной

Список для проверки того, что вы ничего не забыли перед тем, как сдать лабораторную.

- [ ] Создан файл ридми с текстом задания лабораторной
- [ ] Директория с лабораторной называется согласно паттерну `<group_number>-<NameSurname>-<lab_variant>` (Пример: `1-NikitaLanskov-A26`). Это важно, такое название позволяет автоматически назначить в ревью нужного человека.
- [ ] Создан файл .gitignore в директории с лабораторной, в котором перечислены все вспомогательные файлы от visual studio
- [ ] В Pull Request отсутсвуют лишние файлы: сторонние библиотеки, их исходный код, собранные бинарные файлы вашей программы, ваши конфигурационные файлы IDE. В большинстве случаев в PR будет не более 10-15 файлов
- [ ] В Pull Request включены файлы только относящиеся к текущей лабораторной. Чтобы лабы не смешивались, создавайте новую ветвь для каждой лабы
- [ ] Написаны юнит-тесты для всех функций, подлежащих тестированию согласно памятке
- [ ] Пройдены тесты в системе проверки (для второй лабораторной и выше)
- [ ] Код написан в едином стиле

# Дополнительные комментарии к решению

Тут вы можете добавить дополнительные пояснения к решению вашего варианта лабораторной.

Различные сравнения и прочее.

2021-11-05 21:42 UTC, KateZin commented
Тесты в тестовой системе пройдены

2021-11-07 12:53 UTC, maik-nack requested changes
Исправьте, пожалуйста, замечания и проверьте величину отступов

2021-11-07 12:53 UTC, maik-nack commented on 3-Zinyakova-C2/Stress_Test/test.cpp
> +
Нет конфигурации компьютера

2021-11-07 12:53 UTC, maik-nack commented on 3-Zinyakova-C2/Stress_Test/test.cpp
> +TEST(GraphStressTest, GraphMain) {
Тест не компилируется

2021-11-07 12:53 UTC, maik-nack commented on 3-Zinyakova-C2/graphFunctions.c
> +    Push(myStack, start);
Здесь и ниже отсутствует проверка возвращаемого значения функции `Push`

2021-11-07 21:23 UTC, closed without merging