3-PetroshenkoArtem-C3
motorny/alg-dstruct pull request #118
Opened 2021-11-07 22:18 UTC by Artem-Petroshenko

Got 100/100 on testing system
Wrritten Stress Test

# Чек-лист для сдачи лабораторной

Список для проверки того, что вы ничего не забыли перед тем, как сдать лабораторную.

- [ ] Создан файл ридми с текстом задания лабораторной
- [ ] Директория с лабораторной называется согласно паттерну `<group_number>-<NameSurname>-<lab_variant>` (Пример: `1-NikitaLanskov-A26`). Это важно, такое название позволяет автоматически назначить в ревью нужного человека.
- [ ] Создан файл .gitignore в директории с лабораторной, в котором перечислены все вспомогательные файлы от visual studio
- [ ] В Pull Request отсутсвуют лишние файлы: сторонние библиотеки, их исходный код, собранные бинарные файлы вашей программы, ваши конфигурационные файлы IDE. В большинстве случаев в PR будет не более 10-15 файлов
- [ ] В Pull Request включены файлы только относящиеся к текущей лабораторной. Чтобы лабы не смешивались, создавайте новую ветвь для каждой лабы
- [ ] Написаны юнит-тесты для всех функций, подлежащих тестированию согласно памятке
- [ ] Пройдены тесты в системе проверки (для второй лабораторной и выше)
- [ ] Код написан в едином стиле

# Дополнительные комментарии к решению

Тут вы можете добавить дополнительные пояснения к решению вашего варианта лабораторной.

Различные сравнения и прочее.

2021-11-13 15:13 UTC, maik-nack requested changes
Исправьте, пожалуйста, замечания

2021-11-13 15:13 UTC, maik-nack commented on 3-Petroshenko-C3/LabC-Var1/LabC.c
> +				free(LineBuf);
Будет получено исключение о доступе к памяти

2021-11-13 15:13 UTC, maik-nack commented on 3-Petroshenko-C3/LabC-Var1/LabC.c
> +	Element->vertex = vertex;
Нет проверки указателя на `NULL`

2021-11-13 15:13 UTC, maik-nack commented on 3-Petroshenko-C3/LabC-Var1/LabC.c
> +	Q->back = NULL;
Нет проверки указателя на `NULL`

2021-11-13 18:01 UTC, Artem-Petroshenko commented on 3-Petroshenko-C3/Tests/test.cpp
> +TEST(BFS_StressTest, GraphTraversal) {
Не очень понимаю, какие...
Если Вы про очистку графа, то память для него чистится в функции BFS

2021-11-14 20:37 UTC, maik-nack requested changes
Исправьте, пожалуйста, замечания

2021-11-14 20:37 UTC, maik-nack commented on 3-Petroshenko-C3/LabC-Var1/LabC.c
> +		return;
А как Вы узнаете, прошла ли вставка успешно?

2021-11-14 20:37 UTC, maik-nack commented on 3-Petroshenko-C3/Tests/test.cpp
> +TEST(BFS_StressTest, GraphTraversal) {
Из названия функции `BFS` следует, что функция реализует поиск в ширину на графе. Внутри такой функции не должна производиться очистка графа, должно быть лишь итерирование по графу. То есть граф не должен изменяться

2021-11-14 22:29 UTC, maik-nack requested changes
Исправьте, пожалуйста, замечания

2021-11-14 22:29 UTC, maik-nack commented on 3-Petroshenko-C3/LabC-Var1/LabC.c
> +	return;
Недостаточно логики при удалении элемента из очереди

2021-11-14 22:29 UTC, maik-nack commented on 3-Petroshenko-C3/Tests/test.cpp
> +TEST(BFS_StressTest, GraphTraversal) {
Граф до сих пор может изменяться в функции `BFS`

2021-11-14 22:29 UTC, maik-nack commented on 3-Petroshenko-C3/LabC-Var1/LabC.c
> +int BFS(FILE* Stream, Graph_t* Graph) {
В этой функции присутствуют возможные утечки памяти

2021-11-14 22:41 UTC, Artem-Petroshenko commented on 3-Petroshenko-C3/LabC-Var1/LabC.c
> +	return;
Поясните, пожалуйста, это замечание

2021-11-14 22:52 UTC, Artem-Petroshenko commented on 3-Petroshenko-C3/LabC-Var1/LabC.c
> +	return;
В том плане, что нет проверки на то, не пустая ли очередь?

2021-11-18 13:17 UTC, maik-nack reviewed
Окей, лабораторная зачтена!

2021-11-18 13:25 UTC, closed without merging