3-ZinyakovaKate-C2
motorny/alg-dstruct pull request #119
Opened 2021-11-07 22:40 UTC by KateZin

# Чек-лист для сдачи лабораторной

Список для проверки того, что вы ничего не забыли перед тем, как сдать лабораторную.

- [ ] Создан файл ридми с текстом задания лабораторной
- [ ] Директория с лабораторной называется согласно паттерну `<group_number>-<NameSurname>-<lab_variant>` (Пример: `1-NikitaLanskov-A26`). Это важно, такое название позволяет автоматически назначить в ревью нужного человека.
- [ ] Создан файл .gitignore в директории с лабораторной, в котором перечислены все вспомогательные файлы от visual studio
- [ ] В Pull Request отсутсвуют лишние файлы: сторонние библиотеки, их исходный код, собранные бинарные файлы вашей программы, ваши конфигурационные файлы IDE. В большинстве случаев в PR будет не более 10-15 файлов
- [ ] В Pull Request включены файлы только относящиеся к текущей лабораторной. Чтобы лабы не смешивались, создавайте новую ветвь для каждой лабы
- [ ] Написаны юнит-тесты для всех функций, подлежащих тестированию согласно памятке
- [ ] Пройдены тесты в системе проверки (для второй лабораторной и выше)
- [ ] Код написан в едином стиле

# Дополнительные комментарии к решению

Тут вы можете добавить дополнительные пояснения к решению вашего варианта лабораторной.

Различные сравнения и прочее.

2021-11-07 22:42 UTC, KateZin commented
Создан другой pull request из-за проблем с Visual Studio

2021-11-13 19:32 UTC, maik-nack requested changes
Исправьте, пожалуйста, замечания

2021-11-13 19:32 UTC, maik-nack commented on 3-ZinyakovaKate-C2/3-Zinyakova-C/graphFunctions.c
> +void PrintStack(Stack* myStack) {
Хоть Вы и не используете эту функцию, напишите её правильно. Эта функция не должна изменять стек

2021-11-13 19:32 UTC, maik-nack commented on 3-ZinyakovaKate-C2/3-Zinyakova-C/graphFunctions.c
> +	Push(myStack, start);
Здесь и ниже отсутствует проверка возвращаемого значения функции `Push`

2021-11-14 09:25 UTC, KateZin commented on 3-ZinyakovaKate-C2/TestGraph/test.cpp
> +TEST(GraphStressTest, GraphMain) {
исправила утечки памяти

2021-11-14 09:26 UTC, KateZin commented on 3-ZinyakovaKate-C2/3-Zinyakova-C/graphFunctions.c
> +void PrintStack(Stack* myStack) {
переписала функцию

2021-11-14 09:26 UTC, KateZin commented on 3-ZinyakovaKate-C2/TestGraph/test.cpp
> +*/
добавила время и память

2021-11-14 09:26 UTC, KateZin commented on 3-ZinyakovaKate-C2/3-Zinyakova-C/graphFunctions.c
> +	Push(myStack, start);
добавила проверку на NULL

2021-11-14 09:27 UTC, KateZin commented on 3-ZinyakovaKate-C2/TestGraph/test.cpp
> +TEST(GraphStressTest, GraphMain) {
устранила утечки памяти

2021-11-14 09:27 UTC, KateZin commented on 3-ZinyakovaKate-C2/3-Zinyakova-C/graphFunctions.c
> +void PrintStack(Stack* myStack) {
переписала

2021-11-14 09:27 UTC, KateZin commented
Исправила замечания

2021-11-14 20:52 UTC, maik-nack requested changes
Исправьте, пожалуйста, замечание

2021-11-14 20:52 UTC, maik-nack commented on 3-ZinyakovaKate-C2/3-Zinyakova-C/graphFunctions.c
> +void DFS(FILE* stream, int** matrix, int n) {
В функции присутствуют возможные утечки памяти

2021-11-14 23:25 UTC, KateZin commented on 3-ZinyakovaKate-C2/3-Zinyakova-C/graphFunctions.c
> +void DFS(FILE* stream, int** matrix, int n) {
исправила утечки памяти

2021-11-18 13:25 UTC, maik-nack reviewed
Окей, лабораторная зачтена!

2021-11-18 13:25 UTC, closed without merging