4-TomilovIvan-A23
motorny/alg-dstruct pull request #128
Opened 2021-11-12 14:20 UTC by IvanTomilov1

# Чек-лист для сдачи лабораторной

Список для проверки того, что вы ничего не забыли перед тем, как сдать лабораторную.

- [+] Создан файл ридми с текстом задания лабораторной
- [+] Директория с лабораторной называется согласно паттерну `<group_number>-<NameSurname>-<lab_variant>` (Пример: `1-NikitaLanskov-A26`). Это важно, такое название позволяет автоматически назначить в ревью нужного человека.
- [+] Создан файл .gitignore в директории с лабораторной, в котором перечислены все вспомогательные файлы от visual studio
- [+] В Pull Request отсутсвуют лишние файлы: сторонние библиотеки, их исходный код, собранные бинарные файлы вашей программы, ваши конфигурационные файлы IDE. В большинстве случаев в PR будет не более 10-15 файлов
- [+] В Pull Request включены файлы только относящиеся к текущей лабораторной. Чтобы лабы не смешивались, создавайте новую ветвь для каждой лабы
- [+] Написаны юнит-тесты для всех функций, подлежащих тестированию согласно памятке
- [+] Пройдены тесты в системе проверки (для второй лабораторной и выше)
- [+] Код написан в едином стиле

# Дополнительные комментарии к решению

Тут вы можете добавить дополнительные пояснения к решению вашего варианта лабораторной.

Различные сравнения и прочее.

2021-11-13 08:12 UTC, IvanTomilov1 commented
> # Чек-лист для сдачи лабораторной
> Список для проверки того, что вы ничего не забыли перед тем, как сдать лабораторную.
> 
> * [+] Создан файл ридми с текстом задания лабораторной
> * [+] Директория с лабораторной называется согласно паттерну `<group_number>-<NameSurname>-<lab_variant>` (Пример: `1-NikitaLanskov-A26`). Это важно, такое название позволяет автоматически назначить в ревью нужного человека.
> * [+] Создан файл .gitignore в директории с лабораторной, в котором перечислены все вспомогательные файлы от visual studio
> * [+] В Pull Request отсутсвуют лишние файлы: сторонние библиотеки, их исходный код, собранные бинарные файлы вашей программы, ваши конфигурационные файлы IDE. В большинстве случаев в PR будет не более 10-15 файлов
> * [+] В Pull Request включены файлы только относящиеся к текущей лабораторной. Чтобы лабы не смешивались, создавайте новую ветвь для каждой лабы
> * [+] Написаны юнит-тесты для всех функций, подлежащих тестированию согласно памятке
> * [+] Пройдены тесты в системе проверки (для второй лабораторной и выше)
> * [+] Код написан в едином стиле
> 
> # Дополнительные комментарии к решению
> Тут вы можете добавить дополнительные пояснения к решению вашего варианта лабораторной.
> 
> Различные сравнения и прочее.

2021-11-13 08:16 UTC, IvanTomilov1 commented
@ExpressFromSiberia, можете, пожалуйста, проверить? У меня нет возможности добавить ревьюера

2021-11-14 21:53 UTC, ExpressFromSiberia commented on 4-ExpressFromSiberia-A23/WordsSortingLab/WordSorting.c
> +int WordLength(string w) {
А зачем писать эту функцию, если есть стандартная?

2021-11-14 21:58 UTC, ExpressFromSiberia commented on 4-ExpressFromSiberia-A23/WordsSortingLab/WordSorting.c
> +			/*
Зачем тут этот комментарий?

2021-11-14 21:59 UTC, ExpressFromSiberia commented on 4-ExpressFromSiberia-A23/WordsSortingLab/WordSorting.c
> +	string* list_of_words = (string*)malloc(number_of_words*sizeof(string));
Почему нет проверки выделения памяти?

2021-11-14 22:01 UTC, ExpressFromSiberia commented on 4-ExpressFromSiberia-A23/WordsSortingLab/WordSorting.c
> +			word = (char*)malloc(len + 1);
И тут нужно проверять выделилась ли память.

2021-11-14 22:07 UTC, ExpressFromSiberia commented on 4-ExpressFromSiberia-A23/WordsSortingLab/WordSorting.c
> +	sorted_words.arr = (string*)malloc(sizeof(string) * array_size);
И тут надо проверить память.

2021-11-14 22:14 UTC, IvanTomilov1 commented on 4-ExpressFromSiberia-A23/WordsSortingLab/WordSorting.c
> +			/*
Рудимент от предыдущих мыслей

2021-11-14 22:15 UTC, IvanTomilov1 commented on 4-ExpressFromSiberia-A23/WordsSortingLab/WordSorting.c
> +int WordLength(string w) {
Не помню почему, но во время написания кода было чем-то удобнее с ней. Удалил

2021-11-14 22:15 UTC, IvanTomilov1 commented on 4-ExpressFromSiberia-A23/WordsSortingLab/WordSorting.c
> +	string* list_of_words = (string*)malloc(number_of_words*sizeof(string));
Добавил assert

2021-11-14 22:15 UTC, IvanTomilov1 commented on 4-ExpressFromSiberia-A23/WordsSortingLab/WordSorting.c
> +			word = (char*)malloc(len + 1);
Добавил assert

2021-11-14 22:15 UTC, IvanTomilov1 commented on 4-ExpressFromSiberia-A23/WordsSortingLab/WordSorting.c
> +	sorted_words.arr = (string*)malloc(sizeof(string) * array_size);
Добавил assert

2021-11-14 22:15 UTC, ExpressFromSiberia requested changes
Первое. Задание начинается так - "Считать все слова из текстового файла в список...". Где работа с файлом? Так мы точно не договоримся.
Второе. Почему Вы вообще не проверяете результаты выделения памяти? Это обязательно нужно делать.
Третье. Зачем Вы оставляете комментарии с кусками кода? Если он не нужен и программа работает без него - его нужно удалить.

2021-11-14 23:49 UTC, IvanTomilov1 commented
Комментарии с кусками кода удалены, assert для результата выделения памяти добавлен.
Для работы с файлом добавлена функция, считывающая текст из этого самого файла.

2021-11-14 23:58 UTC, IvanTomilov1 commented
Комментарии с кусками кода удалены, assert для результата выделения памяти добавлен.
Для работы с файлом добавлена функция, считывающая текст из этого самого файла.

2021-11-23 10:16 UTC, closed without merging