3-TronyaginaAlexandra-C2
motorny/alg-dstruct pull request #130
Opened 2021-11-14 16:16 UTC by tronyaginaa

# Чек-лист для сдачи лабораторной

Список для проверки того, что вы ничего не забыли перед тем, как сдать лабораторную.

- [ ] Создан файл ридми с текстом задания лабораторной
- [ ] Директория с лабораторной называется согласно паттерну `<group_number>-<NameSurname>-<lab_variant>` (Пример: `1-NikitaLanskov-A26`). Это важно, такое название позволяет автоматически назначить в ревью нужного человека.
- [ ] Создан файл .gitignore в директории с лабораторной, в котором перечислены все вспомогательные файлы от visual studio
- [ ] В Pull Request отсутсвуют лишние файлы: сторонние библиотеки, их исходный код, собранные бинарные файлы вашей программы, ваши конфигурационные файлы IDE. В большинстве случаев в PR будет не более 10-15 файлов
- [ ] В Pull Request включены файлы только относящиеся к текущей лабораторной. Чтобы лабы не смешивались, создавайте новую ветвь для каждой лабы
- [ ] Написаны юнит-тесты для всех функций, подлежащих тестированию согласно памятке
- [ ] Пройдены тесты в системе проверки (для второй лабораторной и выше)
- [ ] Код написан в едином стиле

# Дополнительные комментарии к решению

2021-11-17 23:19 UTC, maik-nack requested changes
Исправьте, пожалуйста, замечания

1. Проверьте отступы.
2. У цикла `for` с телом из одной команды по-разному расставлены скобки.
3. У `if` по-разному расставлены пробелы перед скобками.

2021-11-17 23:19 UTC, maik-nack commented on 3-TronyaginaAlexandra-C2/LabCTests/test.cpp
> +            ASSERT_TRUE(graph);
Этот assert не вызовет остановку программы

2021-11-17 23:19 UTC, maik-nack commented on 3-TronyaginaAlexandra-C2/LabCTests/test.cpp
> +            checkedVertices[j] = FALSE;
Инициализация этого массива производится больше одного раза

2021-11-17 23:19 UTC, maik-nack commented on 3-TronyaginaAlexandra-C2/LabCTests/test.cpp
> +    unsigned long start = clock();
В замеры времени должен входить весь этот тест. Замерять время самостоятельно не нужно, так как GTest сам замеряет время каждого теста

2021-11-17 23:19 UTC, maik-nack commented on 3-TronyaginaAlexandra-C2/main.cpp
> +            checkedVertices[i] = FALSE;
Инициализация этого массива производится больше одного раза

2021-11-17 23:19 UTC, maik-nack commented on 3-TronyaginaAlexandra-C2/main.cpp
> +    if (!graph) {
Это условие не всегда будет выполнено, когда нужно будет совершить выход из программы

2021-11-17 23:19 UTC, maik-nack commented on 3-TronyaginaAlexandra-C2/main.cpp
> +            DFS(i, graph, checkedVertices, numOfVertices);
Решение должно быть реализовано без использования рекурсии

2021-11-20 23:17 UTC, maik-nack requested changes
Исправьте, пожалуйста, замечания

1. Отступы и пробелы! Везде смотрите!
2. Проверка на `NULL` различается.
3. Код не компилируется!

2021-11-20 23:17 UTC, maik-nack commented on 3-TronyaginaAlexandra-C2/main.cpp
> +int main(void) {
Зачем Вам `main`, если Вам нужно тесты запускать?

2021-11-20 23:17 UTC, maik-nack commented on 3-TronyaginaAlexandra-C2/main.cpp
> +void fillGraph() {
Судя из названия функции, в этой функции может изменяться только граф

2021-11-20 23:17 UTC, maik-nack commented on 3-TronyaginaAlexandra-C2/main.cpp
> +    stack = (myStack_t*)malloc(sizeof(myStack_t));
Нет проверки возвращаемого значения

2021-11-20 23:17 UTC, maik-nack commented on 3-TronyaginaAlexandra-C2/main.cpp
> +int* checkedVertices;
Зачем Вам глобальные переменные?

2021-11-20 23:17 UTC, maik-nack commented on 3-TronyaginaAlexandra-C2/main.cpp
> +        memoryFree(stack, checkedVertices, graph);
Вы уже потеряли указатель на выделенную память и получите исключение о доступе к памяти

2021-11-20 23:17 UTC, maik-nack commented on 3-TronyaginaAlexandra-C2/main.cpp
> +                        memoryFree(stack, checkedVertices, graph);
Вы уже потеряли указатель на выделенную память и получите исключение о доступе к памяти

2021-11-20 23:17 UTC, maik-nack commented on 3-TronyaginaAlexandra-C2/main.cpp
> +void DFS(int num, int** graph, int* checkedVertices, int numOfVertices, myStack_t* stack) {
В этой функции граф не должен изменяться.
`checkedVertices` и `stack` должны создаваться и удаляться внутри этой функции, потому что в других местах они не нужны

2021-11-21 10:32 UTC, tronyaginaa commented
Исправила Ваши замечания. После изменений время выполнения теста  почти не изменилось. 
Не уверена насчет исключения о доступе памяти в тесте. После внесенных изменений найти где бы могло возникнуть исключение не получилось

2021-11-21 19:59 UTC, maik-nack requested changes
Исправьте, пожалуйста, замечания

1. Проверьте расстановку пробелов.

2021-11-21 19:59 UTC, maik-nack commented on 3-TronyaginaAlexandra-C2/main.cpp
> +void stackDestroy(myStack_t* stack) {
При вызове этой функции может возникнуть исключение о доступе к памяти

2021-11-21 19:59 UTC, maik-nack commented on 3-TronyaginaAlexandra-C2/main.cpp
> +void readGraph(FILE* stream, int** graph) {
При вызове этой функции может возникнуть исключение о доступе к памяти

2021-11-21 19:59 UTC, maik-nack commented on 3-TronyaginaAlexandra-C2/main.cpp
> +    myStack_t* stack = (myStack_t*)malloc(sizeof(myStack_t));
Нет проверки возвращаемого значения!

2021-11-22 21:04 UTC, maik-nack requested changes

2021-11-22 21:04 UTC, maik-nack commented on 3-TronyaginaAlexandra-C2/main.cpp
> +void stackDestroy(myStack_t* stack) {
Не исправлено!

2021-11-23 19:34 UTC, maik-nack requested changes

2021-11-23 19:34 UTC, maik-nack commented on 3-TronyaginaAlexandra-C2/main.cpp
> +void stackDestroy(myStack_t* stack) {
Исключения теперь не возникнет, но отступы у Вас поехали

2021-11-24 04:14 UTC, tronyaginaa commented
Надеюсь теперь с функцией все нормально :D

2021-11-24 20:27 UTC, maik-nack reviewed
Ок, лабораторная зачтена!

2021-11-24 20:28 UTC, closed without merging