v1
motorny/alg-dstruct pull request #131
Opened 2021-11-14 17:31 UTC by AfellayDS

# Graph BFS from edges list (C4)

   Необходимо создать программу, которая реализует обход графа в ширину. Следует реализовывать
прямой обход (pre-order). Граф задан списком ребер.

Код реализуется только на языке Си, при отправке следует выбрать язык С.

   Входные данные подаются в поток стандартного ввода stdin. В первой строке содержится
количество вершин графа. Далее построчно ребра, заданные парой вершин ему инцидентных.
   Нумерация вершин начинается с 0. Не гарантируется, что граф связный.
Обход графа необходимо начинать с вершины с номером 0.
   При выборе следующей вершины из смежных с текущей следует выбирать вершину с наименьшим
номером.

На выходе ожидается список вершин в порядке обхода через пробел.

2021-11-23 19:29 UTC, LanskovNV requested changes
Добрый вечер

2021-11-23 19:29 UTC, LanskovNV commented on 1-FilippovDenis-C4/Source.c
> +	}
Тут вы не освобождаете память, выделенную под Array2D, если память под matrix выделить не удалось

2021-11-23 19:29 UTC, LanskovNV commented on 1-FilippovDenis-C4/Source.c
> +	}
перед exit снова не будет освобождаться выделенная выше память

2021-11-23 19:29 UTC, LanskovNV commented on 1-FilippovDenis-C4/Source.c
> +		return -1;
тут у вас -1 считается за некоторый маркер особой ситуации, при этом не очень понятно, как отличить эту ситуацию от ситуации, когда вы просто достаете -1 из очереди

2021-11-23 19:29 UTC, LanskovNV commented on 1-FilippovDenis-C4/Source.c
> +	}
А освободить память из под graph?

2021-11-24 19:30 UTC, AfellayDS commented
Здравствуйте. Исправил найденные места, в которых наблюдалась утечка памяти. Также доработал функции для работы с "очередью" - просто изначально я думал, что область допустимых значений входных данных ограничена натуральными числами (номерами вершин). Теперь, в случае некорректной работы функции происходит оповещение в поток вывода ошибок. Полагаю, можно возложить ответственность проверки очереди на ее заполненность на человека, который использует мой интерфейс для работы с типом данных "очередь".

2021-11-24 20:30 UTC, LanskovNV approved these changes
Лабораторная зачтена
Жду сообщение в телеграме, вариант какой лабораторной вам выдавать

2021-11-24 20:33 UTC, closed without merging