3 kopnov alexander c4
motorny/alg-dstruct pull request #133
Opened 2021-11-14 19:52 UTC by Wumianzhe

# Чек-лист для сдачи лабораторной

Список для проверки того, что вы ничего не забыли перед тем, как сдать лабораторную.

- [ ] Создан файл ридми с текстом задания лабораторной
- [ ] Директория с лабораторной называется согласно паттерну `<group_number>-<NameSurname>-<lab_variant>` (Пример: `1-NikitaLanskov-A26`). Это важно, такое название позволяет автоматически назначить в ревью нужного человека.
- [ ] Создан файл .gitignore в директории с лабораторной, в котором перечислены все вспомогательные файлы от visual studio
- [ ] В Pull Request отсутсвуют лишние файлы: сторонние библиотеки, их исходный код, собранные бинарные файлы вашей программы, ваши конфигурационные файлы IDE. В большинстве случаев в PR будет не более 10-15 файлов
- [ ] В Pull Request включены файлы только относящиеся к текущей лабораторной. Чтобы лабы не смешивались, создавайте новую ветвь для каждой лабы
- [ ] Написаны юнит-тесты для всех функций, подлежащих тестированию согласно памятке
- [ ] Пройдены тесты в системе проверки (для второй лабораторной и выше)
- [ ] Код написан в едином стиле

# Дополнительные комментарии к решению

Тут вы можете добавить дополнительные пояснения к решению вашего варианта лабораторной.

Различные сравнения и прочее.

2021-11-17 23:55 UTC, maik-nack requested changes
Исправьте, пожалуйста, замечания

2021-11-17 23:55 UTC, maik-nack commented on 3-Kopnov-C4/test/load_test.cpp
> +        printf("Error while opening file\n");
Возможна утечка памяти

2021-11-17 23:55 UTC, maik-nack commented on 3-Kopnov-C4/test/load_test.cpp
> + * RAM:
Впишите, пожалуйста, значения

2021-11-17 23:55 UTC, maik-nack commented on 3-Kopnov-C4/src/queue.c
> +        return;
Так Вы не сможете узнать, была ли вставка в очередь успешной

2021-11-17 23:55 UTC, maik-nack commented on 3-Kopnov-C4/src/graph.c
> +                free(graph);
Возможна утечка памяти

2021-11-17 23:55 UTC, maik-nack commented on 3-Kopnov-C4/test/load_test.cpp
> +    graph_t* graph = graphCreate(verticesCount);
Отсутствует проверка возвращаемого значения

2021-11-18 08:18 UTC, Wumianzhe commented on 3-Kopnov-C4/src/queue.c
> +        return;
Я всё ещё могу узнать, была ли вставка успешной по значению errno, так как оно мной не обнуляется.

2021-11-19 08:08 UTC, maik-nack commented on 3-Kopnov-C4/src/queue.c
> +        return;
Тогда Вам требуется написать проверки значения `errno` после каждого вызова `enqueue`

2021-11-20 16:52 UTC, maik-nack requested changes
Исправьте, пожалуйста, замечание, и мы договоримся

2021-11-20 16:52 UTC, maik-nack commented on 3-Kopnov-C4/src/graph.c
> +                    queueDelete(queue);
Возможна утечка памяти

2021-11-21 20:17 UTC, maik-nack reviewed
Окей, лабораторная зачтена!
Обращаю внимание на то, что решение хранить список смежности в виде массива очередей в общем случае плоха, так как Вы уничтожаете граф, просто итерируясь по нему, чего происходить не должно.

2021-11-21 20:17 UTC, closed without merging