3-DikarevaMaria-C2
motorny/alg-dstruct pull request #136
Opened 2021-11-15 16:43 UTC by dikareva-me

# Чек-лист для сдачи лабораторной

Список для проверки того, что вы ничего не забыли перед тем, как сдать лабораторную.

- [ ] Создан файл ридми с текстом задания лабораторной
- [ ] Директория с лабораторной называется согласно паттерну `<group_number>-<NameSurname>-<lab_variant>` (Пример: `1-NikitaLanskov-A26`). Это важно, такое название позволяет автоматически назначить в ревью нужного человека.
- [ ] Создан файл .gitignore в директории с лабораторной, в котором перечислены все вспомогательные файлы от visual studio
- [ ] В Pull Request отсутсвуют лишние файлы: сторонние библиотеки, их исходный код, собранные бинарные файлы вашей программы, ваши конфигурационные файлы IDE. В большинстве случаев в PR будет не более 10-15 файлов
- [ ] В Pull Request включены файлы только относящиеся к текущей лабораторной. Чтобы лабы не смешивались, создавайте новую ветвь для каждой лабы
- [ ] Написаны юнит-тесты для всех функций, подлежащих тестированию согласно памятке
- [ ] Пройдены тесты в системе проверки (для второй лабораторной и выше)
- [ ] Код написан в едином стиле

# Дополнительные комментарии к решению

Тут вы можете добавить дополнительные пояснения к решению вашего варианта лабораторной.

Различные сравнения и прочее.

2021-11-19 07:51 UTC, maik-nack requested changes
Исправьте, пожалуйста, замечания и проверьте отступы.

2021-11-19 07:51 UTC, maik-nack commented on 3-DikarevaMaria-C2/Tests/test.cpp
> +	for (int i = 0; i < NUM_EDGES; i++) {
Такая генерация не гарантирует, что не будет повторяющихся рёбер, и что порядок рёбер в файле будет правильным

2021-11-19 07:51 UTC, maik-nack commented on 3-DikarevaMaria-C2/Tests/test.cpp
> +	char* verticesCountBuf = (char*)malloc(MAX_INT_LENGTH * sizeof(char));
Нет проверки на `NULL`

2021-11-19 07:51 UTC, maik-nack commented on 3-DikarevaMaria-C2/labc.c
> +        free(next);
А Вы уверены, что очищаете то, что нужно?

2021-11-19 07:51 UTC, maik-nack commented on 3-DikarevaMaria-C2/labc.c
> +        StackDestroy(stack);
Здесь будет получено исключение о доступе к памяти

2021-11-19 07:51 UTC, maik-nack commented on 3-DikarevaMaria-C2/labc.c
> +        StackDestroy(stack);
Вы уже потеряли указатель на выделенную память и получите исключение о доступе к памяти

2021-11-19 07:51 UTC, maik-nack commented on 3-DikarevaMaria-C2/labc.c
> +int DepthFirstSearch(FILE* stream, int** matrix, int vertexNum) {
В этой функции присутствуют утечки памяти

2021-11-19 07:51 UTC, maik-nack commented on 3-DikarevaMaria-C2/labc.c
> +                StackDestroy(stack);
Аналогично тому, что выше

2021-11-21 10:49 UTC, maik-nack requested changes
Отступы как были различными, так и остались. Выберите что-то одно: либо таб, либо 4 пробела.

2021-11-21 20:27 UTC, maik-nack requested changes
Судя по коммиту, Вы решили ставить табы вместо пробелов, но в `lab.c` все отступы сделаны через пробелы.

2021-11-22 18:30 UTC, dikareva-me commented
В файле lab.c он автоматически ставит пробелы вместо таба, когда я нажимаю на таб. Даже когда я копирую отступ, сделанный табом и воспринимаемый как цельный отступ в другом файле, он становится как 4 пробела в lab.c. Если я копирую код в новый файл то все то же самое. Можно ли оставить так или из-за того что вижуалка тупит исправлять все отступы во всех остальных файлах кроме lab.c?

2021-11-22 18:33 UTC, dikareva-me commented
И те же самые 4 пробела из lab.c в других файлах он воспринимает как цельный отступ

2021-11-22 18:50 UTC, dikareva-me commented
Более того, в настройках даже стоит сохранять знаки табуляции. 
![image](https://user-images.githubusercontent.com/91259546/142918261-2bd4b8a3-30ce-43f5-ad96-39756468989e.png)

2021-11-22 20:42 UTC, maik-nack commented
А, Вы решили воспользоваться галкой, которая на самом деле почти всегда не работает. Там это нужно по-другому настраивать. Ну ладно, пускай будет так.

2021-11-22 20:43 UTC, maik-nack reviewed
Ох, лабораторная зачтена!

2021-11-22 20:43 UTC, closed without merging