LabaC
motorny/alg-dstruct pull request #146
Opened 2021-11-17 16:35 UTC by nikolaichay

# Чек-лист для сдачи лабораторной

Список для проверки того, что вы ничего не забыли перед тем, как сдать лабораторную.

- [ ] Создан файл ридми с текстом задания лабораторной
- [ ] Директория с лабораторной называется согласно паттерну `<group_number>-<NameSurname>-<lab_variant>` (Пример: `1-NikitaLanskov-A26`). Это важно, такое название позволяет автоматически назначить в ревью нужного человека.
- [ ] Создан файл .gitignore в директории с лабораторной, в котором перечислены все вспомогательные файлы от visual studio
- [ ] В Pull Request отсутсвуют лишние файлы: сторонние библиотеки, их исходный код, собранные бинарные файлы вашей программы, ваши конфигурационные файлы IDE. В большинстве случаев в PR будет не более 10-15 файлов
- [ ] В Pull Request включены файлы только относящиеся к текущей лабораторной. Чтобы лабы не смешивались, создавайте новую ветвь для каждой лабы
- [ ] Написаны юнит-тесты для всех функций, подлежащих тестированию согласно памятке
- [ ] Пройдены тесты в системе проверки (для второй лабораторной и выше)
- [ ] Код написан в едином стиле

# Дополнительные комментарии к решению

Тут вы можете добавить дополнительные пояснения к решению вашего варианта лабораторной.

Различные сравнения и прочее.

2021-11-20 11:33 UTC, maik-nack requested changes
Исправьте, пожалуйста, замечания

1. Проверьте расстановку пробелов.
2. Проверьте расстановку скобок в условиях с одной командой.

2021-11-20 11:33 UTC, maik-nack commented on 3-ChaikovskiNikolai-C3/TEST_Laba3/test.cpp
> +RAM: about
Либо допишите значения для памяти, либо сотрите комментарий про память

2021-11-20 11:33 UTC, maik-nack commented on 3-ChaikovskiNikolai-C3/TEST_Laba3/test.cpp
> +	if (!graph) {
Вы уверены, что проверка находится в нужном месте?

2021-11-20 11:33 UTC, maik-nack commented on 3-ChaikovskiNikolai-C3/Algos_Laba3/LabaC.c
> +graph_t* GraphCreate(int size) {
В этой функции возможны утечки памяти

2021-11-20 11:33 UTC, maik-nack commented on 3-ChaikovskiNikolai-C3/Algos_Laba3/LabaC.c
> +			Enqueue(graph->links[nextVal], first);
Нет проверок, что вставки прошли успешно

2021-11-20 11:33 UTC, maik-nack commented on 3-ChaikovskiNikolai-C3/Algos_Laba3/LabaC.c
> +				Enqueue(queue, n);
Нет проверки, что вставка прошла успешно

2021-11-20 14:55 UTC, nikolaichay commented on 3-ChaikovskiNikolai-C3/Algos_Laba3/LabaC.c
> +				Enqueue(queue, n);
Загрузил исправления

2021-11-20 14:56 UTC, nikolaichay commented
Загрузил исправления

2021-11-21 11:44 UTC, maik-nack requested changes
Исправьте, пожалуйста, замечания

1. Проверьте расстановку пробелов.
2. Присутствуют файлы, которые не относятся к данной лабораторной.

2021-11-21 11:44 UTC, maik-nack commented on 3-ChaikovskiNikolai-C3/Algos_Laba3/LabaC.c
> +graph_t* GraphCreate(int size) {
Не исправлено!

2021-11-21 11:44 UTC, maik-nack commented on 3-ChaikovskiNikolai-C3/Algos_Laba3/LabaC.c
> +	if (!in) {
Вы уверены, что эта проверка находится в нужном месте?

2021-11-21 11:44 UTC, maik-nack commented on 3-ChaikovskiNikolai-C3/Algos_Laba3/LabaC.c
> +int BFS(graph_t* graph, FILE* out) {
В этой функции возможны утечки памяти

2021-11-21 12:08 UTC, nikolaichay commented
Все файлы,  не относящиеся к текущей лабораторной, по возможности были удалены.

2021-11-21 12:10 UTC, nikolaichay commented
Все ненужные файлы, которые можно удалить были удалены. Если есть ещё неверная расстановка пробелов, можно сообщить где.

2021-11-21 20:11 UTC, maik-nack requested changes
Да тут ещё файлов 15 от второй лабораторной!

2021-11-21 20:11 UTC, maik-nack commented on 3-ChaikovskiNikolai-C3/Algos_Laba3/LabaC.c
> +	else
Скобки

2021-11-21 20:11 UTC, maik-nack commented on 3-ChaikovskiNikolai-C3/TEST_Laba3/test.cpp
> +	depthFirstTraversalResult =BFS(graph, fileOutput);
Пробел

2021-11-21 20:13 UTC, nikolaichay commented
Как убрать эти 15 файлов?

2021-11-22 20:14 UTC, maik-nack requested changes
Вот как Вы эти файлы добавили, так их и удалите

2021-11-22 20:48 UTC, nikolaichay commented
Удалены

2021-11-22 20:52 UTC, maik-nack reviewed
Ура! Лабораторная зачтена!

2021-11-22 20:52 UTC, closed without merging