3-ChibyshevTimofey-C1
motorny/alg-dstruct pull request #149
Opened 2021-11-17 22:36 UTC by Timofey-Chibyshev

# Чек-лист для сдачи лабораторной

Список для проверки того, что вы ничего не забыли перед тем, как сдать лабораторную.

- [ ] Создан файл ридми с текстом задания лабораторной
- [ ] Директория с лабораторной называется согласно паттерну `<group_number>-<NameSurname>-<lab_variant>` (Пример: `1-NikitaLanskov-A26`). Это важно, такое название позволяет автоматически назначить в ревью нужного человека.
- [ ] Создан файл .gitignore в директории с лабораторной, в котором перечислены все вспомогательные файлы от visual studio
- [ ] В Pull Request отсутсвуют лишние файлы: сторонние библиотеки, их исходный код, собранные бинарные файлы вашей программы, ваши конфигурационные файлы IDE. В большинстве случаев в PR будет не более 10-15 файлов
- [ ] В Pull Request включены файлы только относящиеся к текущей лабораторной. Чтобы лабы не смешивались, создавайте новую ветвь для каждой лабы
- [ ] Написаны юнит-тесты для всех функций, подлежащих тестированию согласно памятке
- [ ] Пройдены тесты в системе проверки (для второй лабораторной и выше)
- [ ] Код написан в едином стиле

# Дополнительные комментарии к решению

Тут вы можете добавить дополнительные пояснения к решению вашего варианта лабораторной.

Различные сравнения и прочее.

2021-11-18 20:33 UTC, Timofey-Chibyshev commented
*fix mistake

2021-11-20 13:09 UTC, maik-nack requested changes
Исправьте, пожалуйста, замечания

1. Программа не компилируется.
2. Определитесь с тем, как Вы называете типы.

2021-11-20 13:09 UTC, maik-nack commented on 3-ChibyshevTimofey-C1/Func.cpp
> +void StackDestroy(Stack* stack)
А Вы уверены в том, что именно вы очищаете в этой функции?

2021-11-21 12:00 UTC, maik-nack requested changes
Исправьте, пожалуйста, замечания и сделайте так, чтобы код можно было скомпилировать

2021-11-21 12:00 UTC, maik-nack commented on 3-ChibyshevTimofey-C1/Func.cpp
> +        AdjListDestroy(graph);
Не исправлено!

2021-11-21 12:00 UTC, maik-nack commented on 3-ChibyshevTimofey-C1/Func.cpp
> +void StackDestroy(Stack_t* stack)
Посмотрите на эту функцию ещё раз!

2021-11-23 19:26 UTC, maik-nack requested changes
Ок, лабораторная зачтена!

2021-11-23 19:27 UTC, closed without merging