1-MakarovaArina-C3
motorny/alg-dstruct pull request #151
Opened 2021-11-18 17:56 UTC by ArinaMak

# Чек-лист для сдачи лабораторной

Список для проверки того, что вы ничего не забыли перед тем, как сдать лабораторную.

- [ ] Создан файл ридми с текстом задания лабораторной
- [ ] Директория с лабораторной называется согласно паттерну `<group_number>-<NameSurname>-<lab_variant>` (Пример: `1-NikitaLanskov-A26`). Это важно, такое название позволяет автоматически назначить в ревью нужного человека.
- [ ] Создан файл .gitignore в директории с лабораторной, в котором перечислены все вспомогательные файлы от visual studio
- [ ] В Pull Request отсутсвуют лишние файлы: сторонние библиотеки, их исходный код, собранные бинарные файлы вашей программы, ваши конфигурационные файлы IDE. В большинстве случаев в PR будет не более 10-15 файлов
- [ ] В Pull Request включены файлы только относящиеся к текущей лабораторной. Чтобы лабы не смешивались, создавайте новую ветвь для каждой лабы
- [ ] Написаны юнит-тесты для всех функций, подлежащих тестированию согласно памятке
- [ ] Пройдены тесты в системе проверки (для второй лабораторной и выше)
- [ ] Код написан в едином стиле

# Дополнительные комментарии к решению

Тут вы можете добавить дополнительные пояснения к решению вашего варианта лабораторной.

Различные сравнения и прочее.

2021-11-23 21:32 UTC, LanskovNV requested changes

2021-11-23 21:32 UTC, LanskovNV commented on 1-MakarovaArina-C3/src/main.c
> +}queue_t;
Ох, что-то странное у вас со структурами данных. для списка смежности вам достаточно иметь структуру вида:
```c
typedef struct tagList {
  int value;
  struct tagList *next;
} list_t;
```
Тогда список смежности графа у вас будет:
```c
struct tagGraph {
  int numVertices;
  list_t **verticeNeighbours;
}
```
Ну и для обхода вам может пригодиться структура очереди:
```c
struct tagQueue {
  int length;
  list_t *head;
  list_t *tail;
}
```
Нумерация вершин начинается с нуля. Тоесть вы считываете число вершин графа, выделяете память под массив списков, и затем просто последовательно вставляете все индексы вершин смежных текущей в ее список, сохраняя его отсортированным. 

Ваши структуры как-будто перепутали свои привычные имена и используются не очень очевидным способом, что заметно по сложности вашей функции ReadList

2021-11-23 21:32 UTC, LanskovNV commented on 1-MakarovaArina-C3/src/main.c
> +int ReadList(list_t list[], int number_of_vertices)
Описание алгоритма вашей функции для считывания графа, в тех структурах данных, что описаны в комментарии выше:
1. Считать число вершин
2. Выделить память для массива списков смежности (graph->verticeNeighbours = ...malloc(graph.numVertices ...))
3. Пока не обработаны все строки:
   - читаем индекс вершины и добавляем все смежные с учетом порядка:
   (addNeigbourSorted(&(graph->verticeNeghbours[index])))

Это я к тому, что очень важно сначала определиться со структурами данных, в дальнейшем это сильно повлияет на сложность кода, который вы пишете.

2021-11-23 21:32 UTC, LanskovNV commented on 1-MakarovaArina-C3/src/main.c
> +}queue_t;
Поясните пожалуйста, что означает каждая из ваших структур данных и каким образом используется

2021-11-27 17:21 UTC, ArinaMak commented on 1-MakarovaArina-C3/src/main.c
> +}queue_t;
Структура node_t хранит список смежных вершин для одной вершины, list_t содержит начало и конец одного списка и информацию - пройдена ли вершина, для которой хранится этот список(используется при обходе в ширину).  queue_t - список, который содержит пройденные вершины при обходе в ширину(можно было использовать структуру node_t, но это, возможно, привело бы к путанице).

2021-11-27 17:23 UTC, ArinaMak commented on 1-MakarovaArina-C3/src/main.c
> +						return 0;
Создала функцию FreeGraph

2021-11-27 17:25 UTC, ArinaMak commented on 1-MakarovaArina-C3/src/main.c
> +					list[num_main_vert].tail = list[num_main_vert].head;
Добавила функцию MemoryLeaks и проверила на очистку памяти, в этом месте она и терялась

2021-11-27 17:29 UTC, ArinaMak commented on 1-MakarovaArina-C3/src/main.c
> +int ReadList(list_t list[], int number_of_vertices)
Большое спасибо, в будущем учту

2021-11-28 18:59 UTC, LanskovNV approved these changes
Лабораторная зачтена, напишите в телеграме, для какой следующей лабораторной вам выдать вариант

2021-12-06 11:07 UTC, closed without merging