Попов С2
motorny/alg-dstruct pull request #155
Opened 2021-11-18 21:36 UTC by Pavel5926

# Чек-лист для сдачи лабораторной

Список для проверки того, что вы ничего не забыли перед тем, как сдать лабораторную.

- [ ] Создан файл ридми с текстом задания лабораторной
- [ ] Директория с лабораторной называется согласно паттерну `<group_number>-<NameSurname>-<lab_variant>` (Пример: `1-NikitaLanskov-A26`). Это важно, такое название позволяет автоматически назначить в ревью нужного человека.
- [ ] Создан файл .gitignore в директории с лабораторной, в котором перечислены все вспомогательные файлы от visual studio
- [ ] В Pull Request отсутсвуют лишние файлы: сторонние библиотеки, их исходный код, собранные бинарные файлы вашей программы, ваши конфигурационные файлы IDE. В большинстве случаев в PR будет не более 10-15 файлов
- [ ] В Pull Request включены файлы только относящиеся к текущей лабораторной. Чтобы лабы не смешивались, создавайте новую ветвь для каждой лабы
- [ ] Написаны юнит-тесты для всех функций, подлежащих тестированию согласно памятке
- [ ] Пройдены тесты в системе проверки (для второй лабораторной и выше)
- [ ] Код написан в едином стиле

# Дополнительные комментарии к решению

Тут вы можете добавить дополнительные пояснения к решению вашего варианта лабораторной.

Различные сравнения и прочее.

2021-11-20 16:21 UTC, maik-nack requested changes
Исправьте, пожалуйста, замечания

1. Проверьте расстановку пробелов.
2. Проверьте расстановку скобок в условиях с одной командой.

2021-11-20 16:21 UTC, maik-nack commented on 3-PopovPavel-C2/Graph.c
> +int** MatrixCreate(int vert_num) {
В этой функции возможно исключение доступа к памяти

2021-11-20 16:21 UTC, maik-nack commented on 3-PopovPavel-C2/Graph.c
> +		StackDelete(stack);
Вы уже потеряли указатель на выделенную память и получите исключение о доступе к памяти

2021-11-20 16:21 UTC, maik-nack commented on 3-PopovPavel-C2/Graph.c
> +int DFS(int** matrix, int vert_num,FILE* out) {
В этой функции присутствуют утечки памяти

2021-11-20 16:21 UTC, maik-nack commented on 3-PopovPavel-C2/Graph.c
> +//int main(void) {
В этой функции присутствуют утечки памяти

2021-11-20 16:21 UTC, maik-nack commented on 3-PopovPavel-C2/Graph.c
> +//	FillZero(matrix, vert_num);
Здесь можно получить исключение о доступе к памяти

2021-11-20 16:21 UTC, maik-nack commented on 3-PopovPavel-C2/Graph.c
> +			Push(stack, cur_vert);
Отсутствует проверка вставки элемента

2021-11-20 19:58 UTC, Pavel5926 commented on 3-PopovPavel-C2/Graph.c
> +			Push(stack, cur_vert);
Исправил

2021-11-20 19:59 UTC, Pavel5926 commented on 3-PopovPavel-C2/Graph.c
> +//int main(void) {
Исправил

2021-11-20 19:59 UTC, Pavel5926 commented on 3-PopovPavel-C2/Graph.c
> +int DFS(int** matrix, int vert_num,FILE* out) {
Исправил

2021-11-20 19:59 UTC, Pavel5926 commented on 3-PopovPavel-C2/Graph.c
> +		StackDelete(stack);
Исправил

2021-11-20 19:59 UTC, Pavel5926 commented on 3-PopovPavel-C2/Graph.c
> +int** MatrixCreate(int vert_num) {
Исправил

2021-11-20 19:59 UTC, Pavel5926 commented on 3-PopovPavel-C2/3-PopovPavel-C2-Test/test.cpp
> +TEST(loadTest, graphReadAndBFS) {
Исправил;
Пробелы и отступы тоже исправил

2021-11-20 20:01 UTC, Pavel5926 commented on 3-PopovPavel-C2/Graph.c
> +//	FillZero(matrix, vert_num);
исправил

2021-11-21 19:33 UTC, maik-nack requested changes
Исправьте, пожалуйста, замечания

1. Проверьте расстановку пробелов.
2. Отступы различны. Выберите что-то одно: либо таб, либо 4 пробела.

2021-11-21 19:33 UTC, maik-nack commented on 3-PopovPavel-C2/3-PopovPavel-C2-Test/test.cpp
> +TEST(loadTest, graphReadAndBFS) {
Возможная утечка памяти не была устранена!

2021-11-21 19:33 UTC, maik-nack commented on 3-PopovPavel-C2/Graph.c
> +		return 0;
Теперь у Вас здесь утечка памяти

2021-11-21 19:33 UTC, maik-nack commented on 3-PopovPavel-C2/Graph.c
> +void StackDelete(stack_t* stack) {
Вызов этой функции создаёт исключение о доступе к памяти

2021-11-21 19:33 UTC, maik-nack commented on 3-PopovPavel-C2/Graph.c
> +	return 3;
То есть программа успешно у Вас никогда не завершается?

2021-11-21 23:21 UTC, Pavel5926 commented on 3-PopovPavel-C2/3-PopovPavel-C2-Test/test.cpp
> +TEST(loadTest, graphReadAndBFS) {
Я добавил в ф-ю ReadGraph проверку на открытие файла. Если я опять не заметил утечку, подскажите, пожалуйста, где конкретно.

2021-11-21 23:22 UTC, Pavel5926 commented on 3-PopovPavel-C2/Graph.c
> +void StackDelete(stack_t* stack) {
Теперь не вызывает. Добавил при инициализации стека stack->top = NULL на 8 строчке.

2021-11-21 23:22 UTC, Pavel5926 commented on 3-PopovPavel-C2/Graph.c
> +		return 0;
Исправил

2021-11-21 23:22 UTC, Pavel5926 commented on 3-PopovPavel-C2/Graph.c
> +	return 3;
исправил

2021-11-23 21:06 UTC, maik-nack requested changes
Исправьте, пожалуйста, замечания

2021-11-23 21:06 UTC, maik-nack commented on 3-PopovPavel-C2/Graph.c
> +			if (Peek(stack) == 0) {
Здесь будет исключение о доступе к памяти, если нулевая вершина не смежна ни с какой другой

2021-11-24 20:03 UTC, Pavel5926 commented on 3-PopovPavel-C2/Graph.c
> +			if (Peek(stack) == 0) {
Ответил в телеграме

2021-11-26 19:30 UTC, maik-nack requested changes

2021-11-26 19:30 UTC, maik-nack commented on 3-PopovPavel-C2/Graph.c
> +			if (Peek(stack) == 0) {
От того, что Вы перенесли кусок кода в другое место в данном случае исключение о доступе к памяти не исчезнет. Оно возникнет именно в этой строчке, а не после неё!

2021-11-27 18:09 UTC, Pavel5926 commented on 3-PopovPavel-C2/Graph.c
> +			if (Peek(stack) == 0) {
Исправил. Теперь не вылетает.

2021-11-28 18:09 UTC, maik-nack reviewed
Класс, лабораторная зачтена!

2021-11-28 18:09 UTC, closed without merging