2-Navetkina-C2
motorny/alg-dstruct pull request #159
Opened 2021-11-19 15:08 UTC by mmurze

# Чек-лист для сдачи лабораторной

Список для проверки того, что вы ничего не забыли перед тем, как сдать лабораторную.

- [ ] Создан файл ридми с текстом задания лабораторной
- [ ] Директория с лабораторной называется согласно паттерну `<group_number>-<NameSurname>-<lab_variant>` (Пример: `1-NikitaLanskov-A26`). Это важно, такое название позволяет автоматически назначить в ревью нужного человека.
- [ ] Создан файл .gitignore в директории с лабораторной, в котором перечислены все вспомогательные файлы от visual studio
- [ ] В Pull Request отсутсвуют лишние файлы: сторонние библиотеки, их исходный код, собранные бинарные файлы вашей программы, ваши конфигурационные файлы IDE. В большинстве случаев в PR будет не более 10-15 файлов
- [ ] В Pull Request включены файлы только относящиеся к текущей лабораторной. Чтобы лабы не смешивались, создавайте новую ветвь для каждой лабы
- [ ] Написаны юнит-тесты для всех функций, подлежащих тестированию согласно памятке
- [ ] Пройдены тесты в системе проверки (для второй лабораторной и выше)
- [ ] Код написан в едином стиле

# Дополнительные комментарии к решению

Тут вы можете добавить дополнительные пояснения к решению вашего варианта лабораторной.

Различные сравнения и прочее.

2021-11-22 19:21 UTC, motorny requested changes
Добавьте, пожалуйста, проверку на отказ в выделении памяти в нескольких местах

2021-11-22 19:21 UTC, motorny commented on 2-Navetkina-C2/main.c
> +	stress_test(5000);
Добрый день,
Опишите точнее, пожалуйста, условия вашего стресс теста.
Сколько было вершин - 5 000 или 200 000?
Сколько программа заняла по памяти и по времени?

2021-11-24 13:31 UTC, mmurze commented on 2-Navetkina-C2/main.c
> +	stress_test(5000);
исправила

2021-11-25 22:15 UTC, motorny commented
Ок, зачтено

2021-12-06 11:07 UTC, closed without merging