Работа 1
motorny/alg-dstruct pull request #16
Opened 2021-09-24 13:06 UTC by nikolaichay

В30

# Чек-лист для сдачи лабораторной

Список для проверки того, что вы ничего не забыли перед тем, как сдать лабораторную.

- [+] Создан файл ридми с текстом задания лабораторной
- [+] Создан файл .gitignore в директории с лабораторной, в котором перечислены все вспомогательные файлы от visual studio
- [+ ] В Pull Request отсутсвуют лишние файлы: сторонние библиотеки, их исходный код, собранные бинарные файлы вашей программы, ваши конфигурационные файлы IDE. В большинстве случаев в PR будет не более 10-15 файлов
- [+ ] В Pull Request включены файлы только относящиеся к текущей лабораторной. Чтобы лабы не смешивались, создавайте новую ветвь для каждой лабы
- [+ ] Написаны юнит-тесты для всех функций, подлежащих тестированию согласно памятке
- [ ] Пройдены тесты в системе проверки (для второй лабораторной и выше)
- [+ ] Код написан в едином стиле

# Дополнительные комментарии к решению

Тут вы можете добавить дополнительные пояснения к решению вашего варианта лабораторной.

Различные сравнения и прочее.

2021-09-26 21:44 UTC, maik-nack requested changes
Исправьте, пожалуйста, комментарии.

1. В трёх из семи функций есть проверки на корректные входные данные. Добавьте их тогда и в остальные тоже.
2. Функцию `DestroyPlenty` можно использовать только в тесте с функцией `CreateZeroPlenty`.
3. Все
   ```c
   if (A == NULL) {
       ASSERT_TRUE(0);
   }
   ```
   можно записать в виде
   ```c
   ASSERT_NE(A, NULL);
   ```
   но не требуется.
4. В тестах Вы совсем не проверяете результат выделения памяти. Чтобы не думать о таких вещах в тестах, рекомендуется использовать статическую память. Исключением является элемент, который должен быть удалён в тесте на удаление.

2021-09-26 21:44 UTC, maik-nack commented on 3-ChaikovskiNikolai-A30/Src/Source.c
> +	if ((A == NULL) || (A->head == NULL)) {
Нарушен стиль кодирования. Расстановка скобок отличается от той, что в таком же месте в функции `IsIncludePlenty`.

2021-09-26 21:44 UTC, maik-nack commented on 3-ChaikovskiNikolai-A30/Src/Source.c
> +	while (p1!=NULL)
Нарушен стиль кодирования. Расстановка пробелов отличается от той, что ниже.

2021-09-26 21:44 UTC, maik-nack commented on 3-ChaikovskiNikolai-A30/Src/Source.c
> +	Plenty_t* C = CreateZeroPlenty();
Отсутствует проверка возвращаемого значения на `NULL`.

2021-09-26 21:44 UTC, maik-nack commented on 3-ChaikovskiNikolai-A30/Src/Source.c
> +	return C;
Что будет, если хотя бы при одном вызове функции `AddInPlenty` не выполнится добавление элемента в множество?

2021-09-26 21:44 UTC, maik-nack commented on 3-ChaikovskiNikolai-A30/Src/Source.c
> +	Plenty_t* C = CreateZeroPlenty();
Отсутствует проверка возвращаемого значения на `NULL`.

2021-09-26 21:44 UTC, maik-nack commented on 3-ChaikovskiNikolai-A30/Src/Source.c
> +			AddInPlenty(C, p2->elem);
Что будет, если хотя бы при одном вызове функции `AddInPlenty` не выполнится добавление элемента в множество?

2021-09-26 21:44 UTC, maik-nack commented on 3-ChaikovskiNikolai-A30/Src/Source.c
> +		if (p1->elem = p2->elem) {
Подумайте ещё.

2021-09-26 21:44 UTC, maik-nack commented on 3-ChaikovskiNikolai-A30/Src/Source.c
> +		if (p1->elem = p2->elem) {
Подумайте ещё.

2021-09-26 21:44 UTC, maik-nack commented on 3-ChaikovskiNikolai-A30/Src/Source.c
> +void FillPlenty(Plenty_t* A, int size, int step) {
Данную функцию по заданию не просили, но раз уж Вы её написали, то добавьте проверку возвращаемого значения на `NULL` в некотором месте.

2021-09-26 21:44 UTC, maik-nack commented on 3-ChaikovskiNikolai-A30/Test/test.cpp
> +	A->head =NULL;
Пропал пробел.

2021-09-26 21:44 UTC, maik-nack commented on 3-ChaikovskiNikolai-A30/Test/test.cpp
> +	ASSERT_FALSE(A==NULL);
В строчке ниже абсолютно такая же ситуация, но уже стоят пробелы.

2021-09-26 21:44 UTC, maik-nack commented on 3-ChaikovskiNikolai-A30/Test/test.cpp
> +	ASSERT_EQ(1,A->head->elem);
Снова нет пробела, хотя во всех остальных таких же ситуациях он есть.

2021-09-26 21:44 UTC, maik-nack commented on 3-ChaikovskiNikolai-A30/Test/test.cpp
> +	ASSERT_EQ(1,A->head->elem);
В этом и остальных тестах, где вы пытаетесь получить доступ к памяти, которая была выделена внутри тестируемой функции, Вам нужно проверять значение каждого указателя на то, что он не равен `NULL`, например, с помощью `ASSERT_NE`. В противном случае Вы можете словить ошибку доступа к памяти.

2021-09-26 21:44 UTC, maik-nack commented on 3-ChaikovskiNikolai-A30/Test/test.cpp
> +	bool check = DeleteFromPlenty(A, 32);
Почему именно `32`? Если это несёт какой-то смысл, то вынесите это в макрос с названием, которое доносит этот смысл.

2021-09-26 21:44 UTC, maik-nack commented on 3-ChaikovskiNikolai-A30/Test/test.cpp
> +	bool check = DeleteFromPlenty(A, 32);
Почему именно `32`? Если это несёт какой-то смысл, то вынесите это в макрос с названием, которое доносит этот смысл.

2021-09-26 21:44 UTC, maik-nack commented on 3-ChaikovskiNikolai-A30/Test/test.cpp
> +	bool check = CompareValues(C, a, 4);
Четыре элемента можно проверить ручками и без циклов. Циклы вообще лучше не использовать в юнит-тестировании.

2021-09-28 20:29 UTC, nikolaichay commented
Исправлено

2021-10-03 21:31 UTC, maik-nack commented on 3-ChaikovskiNikolai-A30/Src/Source.c
> +	if (A == NULL || size == 0) {
А если `step` будет равен нулю, то что тогда?

2021-10-03 21:31 UTC, maik-nack commented on 3-ChaikovskiNikolai-A30/Src/Source.c
> +	return C;
То есть Вы считаете, что правильно возвращать недоделанное объединение? Тогда пользователь будет считать, что объединение удалось, что неверно.

2021-10-03 21:31 UTC, maik-nack commented on 3-ChaikovskiNikolai-A30/Src/Source.c
> +			AddInPlenty(C, p2->elem);
То есть Вы считаете, что правильно возвращать недоделанное пересечение? Тогда пользователь будет считать, что пересечение удалось, что неверно.

2021-10-03 21:40 UTC, maik-nack requested changes
Исправьте, пожалуйста, комментарии.

1. Опять же в тестах нет проверки результата выделения памяти. Настоятельно рекомендую выделять динамически память только под элемент, который должен быть удалён.
2. В тестах остались места, где возвращаемые значения из Ваших функций не проверяются на `NULL`.
3. Определитесь, что вы используете: `nullptr` или `NULL`.

2021-10-04 19:38 UTC, nikolaichay commented
Как понимать 2 пункт. Можно пример, где нет проверки.

2021-10-04 20:10 UTC, nikolaichay reviewed
Из-за специфики гугол тестов, при попытке сравнить с помощью ф-ции ASSERT_NE() NULL с указателем выдается ошибка. Поэтому я везде, где сравниваю указатель с нулевым указателем, использую nullptr.

2021-10-05 14:50 UTC, maik-nack reviewed
А Вы понимаете, по какой причине функция `AddInPlenty ` могла не сработать в `PlentyCombine` и `PlentyIntersect`?

2021-10-05 15:13 UTC, nikolaichay commented
AddInPlenty может не сработать, т.е. вернуть false, если С = NULL, если элемент такой уже есть, если не удалось выделить память на новый элемент. Первый вариант невозможен (после создания сразу идет проверка на это), второй вариант проверяется, а решение третьего случая это вторая попытка добавить элемент, что и делается при таком раскладе.

2021-10-05 15:21 UTC, maik-nack commented
Вы уверены, что при Ваших алгоритмах для `PlentyCombine` и `PlentyIntersect` вообще возможен случай добавления повторяющего элемента в множество?

2021-10-05 15:23 UTC, nikolaichay commented
Возможен, если множество создано не с помощью моих ф-ций. А так, нет

2021-10-05 15:26 UTC, maik-nack commented
Как раз-таки подразумевается, что работа с множествами осуществляется с помощью Ваших функций.

2021-10-05 15:29 UTC, nikolaichay commented
Т.е. достаточно запускать повторно попытку добавки элемента в множество, пока он не добавится?

2021-10-05 15:38 UTC, maik-nack commented
К сожалению, нет. Эта попытка может обернуться бесконечным циклом из-за того, что у Вас закончилась доступная память. Поэтому надо просто очистить `C` и вернуть `NULL`.

2021-10-06 06:53 UTC, maik-nack reviewed
Ок, лабораторная зачтена!

2021-10-11 06:37 UTC, closed without merging