3-KrasnikovRoman-D28
motorny/alg-dstruct pull request #169
Opened 2021-11-25 13:12 UTC by krasnikovra

# Чек-лист для сдачи лабораторной

Список для проверки того, что вы ничего не забыли перед тем, как сдать лабораторную.

- [ ] Создан файл ридми с текстом задания лабораторной
- [ ] Директория с лабораторной называется согласно паттерну `<group_number>-<NameSurname>-<lab_variant>` (Пример: `1-NikitaLanskov-A26`). Это важно, такое название позволяет автоматически назначить в ревью нужного человека.
- [ ] Создан файл .gitignore в директории с лабораторной, в котором перечислены все вспомогательные файлы от visual studio
- [ ] В Pull Request отсутсвуют лишние файлы: сторонние библиотеки, их исходный код, собранные бинарные файлы вашей программы, ваши конфигурационные файлы IDE. В большинстве случаев в PR будет не более 10-15 файлов
- [ ] В Pull Request включены файлы только относящиеся к текущей лабораторной. Чтобы лабы не смешивались, создавайте новую ветвь для каждой лабы
- [ ] Написаны юнит-тесты для всех функций, подлежащих тестированию согласно памятке
- [ ] Пройдены тесты в системе проверки (для второй лабораторной и выше)
- [ ] Код написан в едином стиле

# Дополнительные комментарии к решению

## Затраты ресурсов в нагрузочном тесте:

- Время: 44,249 секунд
- Память: 1 Мб зарезервировано под стек, по метрике VS 772 Кб.

2021-12-05 15:53 UTC, maik-nack requested changes
Исправьте, пожалуйста, замечания

2021-12-05 15:53 UTC, maik-nack commented on 3-Krasnikov-D28/src/test.cpp
> +	int distWagError = DistributeWagons(
Не похоже на стиль кодирования в других файлах

2021-12-05 16:04 UTC, krasnikovra commented on 3-Krasnikov-D28/src/test.cpp
> +	int distWagError = DistributeWagons(
Сделал в одну строку, если Вы это имели в виду, на всякий случай объясню, почему в `DistributeWagons` 0 означает успешное завершение функции в отличие от остальных функций - по смыслу `DistributeWagons` - это точка входа программы, которая в точности является решением лабораторной, то есть в точке входа будет написано
```
int main(void) {
    return DistributeWagons("input.txt", "output.txt");
}
```

2021-12-11 14:57 UTC, maik-nack requested changes

2021-12-11 14:57 UTC, maik-nack commented on 3-Krasnikov-D28/src/lab_solution.c
> +        g_wagonsRestricted[iter->wagon] = 0;
А не обнуляться ли тут ограничения, которые были поставлены предыдущими вагонами? Может стоит также запоминать, какой вагон первым поставил ограничение, чтобы не терять его?

2021-12-11 15:06 UTC, krasnikovra commented on 3-Krasnikov-D28/src/lab_solution.c
> +        g_wagonsRestricted[iter->wagon] = 0;
Можно при добавлении ограничения делать не `= 1`, а `+= 1` (соответственно убираем ограничение - `-= 1`) - тогда если несколько вагонов ставят одно ограничение, то оно обнулится только при возврате на глубину до первого вагона, который его наложил, возврат на один вагон в описанном случае не обнулит ограничение.
Все тесты с таким изменением по прежнему проходят.

2021-12-22 22:04 UTC, maik-nack reviewed
Супер! Лабораторная зачтена!

2021-12-22 22:04 UTC, closed without merging