3-Zinyakova-D20
motorny/alg-dstruct pull request #170
Opened 2021-11-28 01:08 UTC by KateZin

# Чек-лист для сдачи лабораторной

Список для проверки того, что вы ничего не забыли перед тем, как сдать лабораторную.

- [ ] Создан файл ридми с текстом задания лабораторной
- [ ] Директория с лабораторной называется согласно паттерну `<group_number>-<NameSurname>-<lab_variant>` (Пример: `1-NikitaLanskov-A26`). Это важно, такое название позволяет автоматически назначить в ревью нужного человека.
- [ ] Создан файл .gitignore в директории с лабораторной, в котором перечислены все вспомогательные файлы от visual studio
- [ ] В Pull Request отсутсвуют лишние файлы: сторонние библиотеки, их исходный код, собранные бинарные файлы вашей программы, ваши конфигурационные файлы IDE. В большинстве случаев в PR будет не более 10-15 файлов
- [ ] В Pull Request включены файлы только относящиеся к текущей лабораторной. Чтобы лабы не смешивались, создавайте новую ветвь для каждой лабы
- [ ] Написаны юнит-тесты для всех функций, подлежащих тестированию согласно памятке
- [ ] Пройдены тесты в системе проверки (для второй лабораторной и выше)
- [ ] Код написан в едином стиле

# Дополнительные комментарии к решению

Тут вы можете добавить дополнительные пояснения к решению вашего варианта лабораторной.

Различные сравнения и прочее.

2021-12-05 19:02 UTC, maik-nack requested changes
Исправьте, пожалуйста, замечания

1. Пишите относительные пути к файлам, а не абсолютные!
2. Было бы неплохо иметь лишь одну функцию, которая на вход принимает пути к двум файлам.

2021-12-05 19:02 UTC, maik-nack commented on 3-Zinyakova-D20/Subset-Test-D20/test.cpp
> +//   Time with reading from file: 26.811 ms
Нагрузочный тест должен либо потреблять 512 мб памяти, либо выполняться 30 секунд. Очевидно, что по времени условие не выполнено, а про память так вообще ничего не написано

2021-12-06 17:09 UTC, KateZin commented on 3-Zinyakova-D20/3-ZinyakovaKate-D20/SubsetHeader.h
> +	int SubsetSum(int set[], int n, int sum, int** res );
исправила передачу массива

2021-12-06 17:09 UTC, KateZin commented on 3-Zinyakova-D20/3-ZinyakovaKate-D20/SubsetHeader.h
> +	int findSet(int** subset, int* mass, int** res, int n, int sum);
исправила написание

2021-12-06 17:09 UTC, KateZin commented on 3-Zinyakova-D20/3-ZinyakovaKate-D20/SubsetHeader.h
> +	int ReadData(char* filename, int* B, int* N, int** mass);
исправила написание

2021-12-06 17:10 UTC, KateZin commented on 3-Zinyakova-D20/3-ZinyakovaKate-D20/SubsetFunctions.c
> +	*B = atoi((char*)countBuf);
теперь B  имеет тип unsigned long int, что удовлетворяет условию

2021-12-06 17:11 UTC, KateZin commented on 3-Zinyakova-D20/3-ZinyakovaKate-D20/SubsetFunctions.c
> +			*res = mass[i - 1];
исправила и написала дополнительный тест для данного случая

2021-12-06 17:11 UTC, KateZin commented on 3-Zinyakova-D20/Subset-Test-D20/test.cpp
> +TEST(FunctionalTest, CheckSizeOfSubSet) {
написала через файлы

2021-12-06 17:11 UTC, KateZin commented on 3-Zinyakova-D20/Subset-Test-D20/test.cpp
> +	EXPECT_EQ(checkSum, B);
ответ знаю, исправила

2021-12-06 17:12 UTC, KateZin commented on 3-Zinyakova-D20/Subset-Test-D20/test.cpp
> +	free(countBuf);
случайно. исправила

2021-12-06 17:12 UTC, KateZin commented on 3-Zinyakova-D20/Subset-Test-D20/test.cpp
> +	fclose(fstdin);
случайно повторилась. исправила

2021-12-06 17:12 UTC, KateZin commented on 3-Zinyakova-D20/Subset-Test-D20/test.cpp
> +	int* set = NULL;
пересчитала время

2021-12-06 17:13 UTC, KateZin commented on 3-Zinyakova-D20/Subset-Test-D20/test.cpp
> +//   Time with reading from file: 26.811 ms
пересчитала, добавила информацию о памяти и времени

2021-12-06 17:13 UTC, KateZin commented on 3-Zinyakova-D20/3-ZinyakovaKate-D20/SubsetFunctions.c
> +		if (set[i] < 0 && i!= n) {
исправила

2021-12-06 17:13 UTC, KateZin commented on 3-Zinyakova-D20/3-ZinyakovaKate-D20/SubsetFunctions.c
> +	check = fgets((char*)countBuf, MAX_LENGTH, fstdin);
переписала функцию

2021-12-06 17:15 UTC, KateZin commented
изменила пути к файлам
добавила функцию LabSolution, которая проводит все вычисления и запись
переписала и добавила некоторые тесты

2021-12-11 16:04 UTC, maik-nack commented on 3-Zinyakova-D20/Subset-Test-D20/test.cpp
> +	EXPECT_EQ(checkSum, B);
Я писал о том, что зачем Вам считать сумму, если Вы знаете ответ и можете с ним сравнить результат работы Вашей программы

2021-12-11 16:08 UTC, maik-nack requested changes
Исправьте, пожалуйста, замечания

2021-12-11 16:08 UTC, maik-nack commented on 3-Zinyakova-D20/Subset-Test-D20/test.cpp
> +	free(countBuf);
Не похоже

2021-12-11 20:59 UTC, KateZin commented
исправила замечания.
по какой-то причине в последнем pull reqest отобразились не все изменения в тестах. сейчас все верно

2021-12-23 08:47 UTC, maik-nack requested changes
Исправьте, пожалуйста, замечания

2021-12-23 08:47 UTC, maik-nack commented on 3-Zinyakova-D20/3-ZinyakovaKate-D20/SubsetFunctions.c
> +	int** subset = CreateRectMatrix(n + 1, sum + 1);
Здесь может произойти переполнение типа

2021-12-23 08:47 UTC, maik-nack commented on 3-Zinyakova-D20/3-ZinyakovaKate-D20/SubsetFunctions.c
> +int** CreateRectMatrix(int str, int col) {
А тут точно второй аргумент нужного типа? Проверьте и в других функциях тоже

2021-12-23 08:47 UTC, maik-nack commented on 3-Zinyakova-D20/Subset-Test-D20/test.cpp
> +	int toCheck = LabSolution(input, output);
А как Вы замеряете время?

2021-12-23 08:47 UTC, maik-nack commented on 3-Zinyakova-D20/Subset-Test-D20/test.cpp
> +TEST(FunctionalTest, CheckWritingInFile) {
А где именно здесь проверка записи в файл?

2021-12-23 12:55 UTC, KateZin commented on 3-Zinyakova-D20/3-ZinyakovaKate-D20/SubsetFunctions.c
> +	int** subset = CreateRectMatrix(n + 1, sum + 1);
исправила тип

2021-12-23 12:56 UTC, KateZin commented on 3-Zinyakova-D20/3-ZinyakovaKate-D20/SubsetFunctions.c
> +int** CreateRectMatrix(int str, int col) {
исправила здесь и в других функциях

2021-12-23 12:57 UTC, KateZin commented on 3-Zinyakova-D20/Subset-Test-D20/test.cpp
> +	int toCheck = LabSolution(input, output);
в прошлом pull request писала, что по какой-то причине не все изменения были сохранены. Измеряю использую библиотеку Windows.h

2021-12-23 12:58 UTC, KateZin commented on 3-Zinyakova-D20/Subset-Test-D20/test.cpp
> +TEST(FunctionalTest, CheckWritingInFile) {
я подумала, что этот тест н несет никакой смысловой нагрузки и в принципе не нужен

2021-12-23 14:04 UTC, maik-nack reviewed
Ура! Лабораторная зачтена!

2021-12-23 14:04 UTC, closed without merging