3-RubanovaValeria-D20
motorny/alg-dstruct pull request #171
Opened 2021-11-28 17:24 UTC by riapush

# Чек-лист для сдачи лабораторной

Список для проверки того, что вы ничего не забыли перед тем, как сдать лабораторную.

- [ ] Создан файл ридми с текстом задания лабораторной
- [ ] Директория с лабораторной называется согласно паттерну `<group_number>-<NameSurname>-<lab_variant>` (Пример: `1-NikitaLanskov-A26`). Это важно, такое название позволяет автоматически назначить в ревью нужного человека.
- [ ] Создан файл .gitignore в директории с лабораторной, в котором перечислены все вспомогательные файлы от visual studio
- [ ] В Pull Request отсутсвуют лишние файлы: сторонние библиотеки, их исходный код, собранные бинарные файлы вашей программы, ваши конфигурационные файлы IDE. В большинстве случаев в PR будет не более 10-15 файлов
- [ ] В Pull Request включены файлы только относящиеся к текущей лабораторной. Чтобы лабы не смешивались, создавайте новую ветвь для каждой лабы
- [ ] Написаны юнит-тесты для всех функций, подлежащих тестированию согласно памятке
- [ ] Пройдены тесты в системе проверки (для второй лабораторной и выше)
- [ ] Код написан в едином стиле

# Дополнительные комментарии к решению

Тут вы можете добавить дополнительные пояснения к решению вашего варианта лабораторной.

Различные сравнения и прочее.

2021-12-05 20:51 UTC, maik-nack requested changes
Исправьте, пожалуйста, замечания

1. Было бы неплохо иметь лишь одну функцию, которая на вход принимает пути к двум файлам.
2. Прекратите использовать одновременно `#pragma once` и `#ifndef _MY_H` - выберите что-то одно.

2021-12-05 20:51 UTC, maik-nack commented on 3-RubanovaValeria-D20/3-RubanovaValeria-D20/LabD.h
> +int compare(int * x, int* y);
Что-то не так с пробелами

2021-12-05 20:51 UTC, maik-nack commented on 3-RubanovaValeria-D20/3-RubanovaValeria-D20/LabD.h
> +int* readFile(const char* filename, int* B, int* N);
Переменные тут, 3 ниже и в других местах названы не в том стиле, что другие

2021-12-05 20:51 UTC, maik-nack commented on 3-RubanovaValeria-D20/3-RubanovaValeria-D20/LabDfunc.c
> +	fscanf(file, "%i\n", B);
А Вы уверены, что число из условия поместится в int?

2021-12-05 20:51 UTC, maik-nack commented on 3-RubanovaValeria-D20/LabDtest/test.cpp
> +TEST(subsetSum, stressTest) {
Что-то не так с пробелами в этом тесте

2021-12-05 20:51 UTC, maik-nack commented on 3-RubanovaValeria-D20/LabDtest/test.cpp
> +TEST(subsetSum, stressTest) {
Нет данных ни о времени, ни о памяти!

2021-12-05 20:51 UTC, maik-nack commented on 3-RubanovaValeria-D20/LabDtest/test.cpp
> +
В Вашем случае нужно написать функциональные тесты именно для функции `subsetSum`, а тестовые данные должны быть в файлах. Двух тестов точно недостаточно

2021-12-05 20:51 UTC, maik-nack commented on 3-RubanovaValeria-D20/LabDmain/LabDmain.c
> +int main()
В этой функции нет никаких проверок значений выделенной памяти

2021-12-16 13:15 UTC, maik-nack requested changes
Исправьте, пожалуйста, новые и старые замечания

2021-12-16 13:15 UTC, maik-nack commented on 3-RubanovaValeria-D20/3-RubanovaValeria-D20/LabDfunc.c
> +int labSolution(const char* input, const char* output) {
В этой функции есть утечки памяти

2021-12-16 13:15 UTC, maik-nack commented on 3-RubanovaValeria-D20/3-RubanovaValeria-D20/LabDfunc.c
> +int* traceSubset(bool** matrix, int* set, int c, long int r, int* subset_size) {
В этой функции возможны утечки памяти

2021-12-16 13:15 UTC, maik-nack commented on 3-RubanovaValeria-D20/3-RubanovaValeria-D20/LabDfunc.c
> +	int* a = NULL;
В функции не при всех путях выполнения возвращается значение

2021-12-16 13:15 UTC, maik-nack commented on 3-RubanovaValeria-D20/LabDtest/test.cpp
> +TEST(functionalTest, sum7_set123_expected0) {
Нет проверки значения `to_check`

2021-12-23 18:39 UTC, maik-nack requested changes
Исправьте, пожалуйста, замечание

2021-12-23 18:39 UTC, maik-nack commented on 3-RubanovaValeria-D20/3-RubanovaValeria-D20/LabDfunc.c
> +	fscanf(file, "%li\n", b);
`long` и `int` занимают одинаковое количество байт и имеют одинаковые диапазоны. Поэтому я повторю вопрос, Вы уверены, что число из условия поместится в `int`?

2021-12-26 12:49 UTC, maik-nack requested changes
Исправьте, пожалуйста, замечание и сделайте так, чтобы тесты работали

2021-12-26 12:49 UTC, maik-nack commented on 3-RubanovaValeria-D20/3-RubanovaValeria-D20/LabDfunc.c
> +	bool** m = createMatrix(n, sum + 1);
Здесь и в похожих местах ниже может произойти переполнение типа

2021-12-26 14:01 UTC, riapush commented on 3-RubanovaValeria-D20/3-RubanovaValeria-D20/LabDfunc.c
> +	bool** m = createMatrix(n, sum + 1);
@maik-nack ответьте, пожалуйста, в телеграме

2021-12-26 21:52 UTC, maik-nack requested changes
Исправьте, пожалуйста, замечания

2021-12-26 21:52 UTC, maik-nack commented on 3-RubanovaValeria-D20/3-RubanovaValeria-D20/LabDfunc.c
> +					if (j - set[i] >= 0) {
Это выражение всегда истинно

2021-12-26 21:52 UTC, maik-nack commented on 3-RubanovaValeria-D20/3-RubanovaValeria-D20/LabDfunc.c
> +	bool** m = createMatrix(n, sum + 1);
Подумайте, чему может быть равно `sum + 1`, если взято максимальное значение для `sum` из условия

2021-12-27 00:23 UTC, maik-nack requested changes

2021-12-27 00:23 UTC, maik-nack commented on 3-RubanovaValeria-D20/3-RubanovaValeria-D20/LabDfunc.c
> +				if ((matrix[i - 1][j] == true) || matrix[i - 1][j - (long long int)set[i]] == true) {
Вот зря Вы стрёрли предыдущий код. Если выражение всегда истинно, то нужно понять, почему так, а не просто его стирать. Сейчас в данной строчке можно словить исключение доступа к памяти

2021-12-27 00:58 UTC, maik-nack requested changes

2021-12-27 00:58 UTC, maik-nack commented on 3-RubanovaValeria-D20/3-RubanovaValeria-D20/LabDfunc.c
> +				}
Одна из этих скобок лишняя

2021-12-27 01:02 UTC, maik-nack reviewed
Ок, лабораторная зачтена!

2021-12-27 01:02 UTC, closed without merging