FirstTry
motorny/alg-dstruct pull request #180
Opened 2021-12-06 16:15 UTC by Pavel5926

# Чек-лист для сдачи лабораторной

Список для проверки того, что вы ничего не забыли перед тем, как сдать лабораторную.

- [ ] Создан файл ридми с текстом задания лабораторной
- [ ] Директория с лабораторной называется согласно паттерну `<group_number>-<NameSurname>-<lab_variant>` (Пример: `1-NikitaLanskov-A26`). Это важно, такое название позволяет автоматически назначить в ревью нужного человека.
- [ ] Создан файл .gitignore в директории с лабораторной, в котором перечислены все вспомогательные файлы от visual studio
- [ ] В Pull Request отсутсвуют лишние файлы: сторонние библиотеки, их исходный код, собранные бинарные файлы вашей программы, ваши конфигурационные файлы IDE. В большинстве случаев в PR будет не более 10-15 файлов
- [ ] В Pull Request включены файлы только относящиеся к текущей лабораторной. Чтобы лабы не смешивались, создавайте новую ветвь для каждой лабы
- [ ] Написаны юнит-тесты для всех функций, подлежащих тестированию согласно памятке
- [ ] Пройдены тесты в системе проверки (для второй лабораторной и выше)
- [ ] Код написан в едином стиле

# Дополнительные комментарии к решению

Тут вы можете добавить дополнительные пояснения к решению вашего варианта лабораторной.

Различные сравнения и прочее.

2021-12-11 17:33 UTC, maik-nack requested changes
Исправьте, пожалуйста, замечания и напишите тест, в котором будет судоку без решения с N равным хотя бы 3

2021-12-11 17:33 UTC, maik-nack commented on 3-PopovPavel-D14/sudoku_header.h
> +int SudokuSolver(int** matrix, int dimension, int small_dimension, int s_cur);
Нужна ещё функция, принимающая в качестве аргументов пути к входному и выходному файлам, и именно эта функция должна быть в тестах

2021-12-11 17:33 UTC, maik-nack commented on 3-PopovPavel-D14-Test/test.cpp
> +TEST(SudokuSolverTest, FunctionalTestSolutionFound) {
В тестах нужно проверять, что ответ верный!

2021-12-11 17:33 UTC, maik-nack commented on 3-PopovPavel-D14-Test/test.cpp
> +#include "D:\\repos\\alg-dstruct\\3-PopovPavel-D14\\sudoku_header.h"
Везде пишите относительный пути!

2021-12-12 01:25 UTC, Pavel5926 commented on 3-PopovPavel-D14/sudoku_header.h
> +void  MatrixDelete(int** matrix, int dimension);
> Исправьте, пожалуйста, замечания и напишите тест, в котором будет судоку без решения с N равным хотя бы 3. Исправил. Пробел также убрал.

2021-12-12 01:26 UTC, Pavel5926 commented on 3-PopovPavel-D14/lab_sudoku.c
> +	int** matrix = (int**)malloc(sizeof(double*) * dimension);
Скопировал ф-ю со своей лабы по численным методам и забыл исправить

2021-12-12 01:26 UTC, Pavel5926 commented on 3-PopovPavel-D14/lab_sudoku.c
> +		matrix[i] = (int*)malloc(sizeof(double) * dimension);
Аналогично исправил

2021-12-12 01:26 UTC, Pavel5926 commented on 3-PopovPavel-D14/lab_sudoku.c
> +void  MatrixDelete(int** matrix, int dimension) {
Исправил

2021-12-12 01:26 UTC, Pavel5926 commented on 3-PopovPavel-D14/sudoku_header.h
> +int SudokuSolver(int** matrix, int dimension, int small_dimension, int s_cur);
Добавил в тестах

2021-12-12 01:26 UTC, Pavel5926 commented on 3-PopovPavel-D14-Test/test.cpp
> +TEST(SudokuSolverTest, FunctionalTestSolutionFound) {
Исправил

2021-12-12 01:26 UTC, Pavel5926 commented on 3-PopovPavel-D14-Test/test.cpp
> +#include "D:\\repos\\alg-dstruct\\3-PopovPavel-D14\\sudoku_header.h"
Исправил

2021-12-12 14:40 UTC, Pavel5926 commented on 3-PopovPavel-D14/sudoku_header.h
> +int SudokuSolver(int** matrix, int dimension, int small_dimension, int s_cur);
в Fix2 добавил именно эту ф-ю. Также добавил функцию проверки результата.

2021-12-23 09:14 UTC, maik-nack requested changes
Исправьте, пожалуйста, замечания

2021-12-23 09:14 UTC, maik-nack commented on 3-PopovPavel-D14-Test/test.cpp
> +	FILE* in = fopen("D:\\repos\\alg-dstruct\\3-PopovPavel-D14\\SudokuIn.txt", "r");
ВЕЗДЕ нужно писать относительные пути

2021-12-23 09:14 UTC, maik-nack commented on 3-PopovPavel-D14-Test/test.cpp
> +	fseek(out, 0, SEEK_SET);
Зачем перемещать указатель в начало файла?

2021-12-23 09:14 UTC, maik-nack commented on 3-PopovPavel-D14/lab_sudoku.c
> +void PrintMatrix(FILE* out, int** matrix, int dimension) {
Проверьте требуемый формат вывода

2021-12-23 09:14 UTC, maik-nack commented on 3-PopovPavel-D14/lab_sudoku.c
> +	int small_dimension = 0;
Функция не объявлена в заголовочном файле

2021-12-23 21:23 UTC, Pavel5926 commented on 3-PopovPavel-D14/lab_sudoku.c
> +int SudokuSolverFile(FILE* in, FILE* out) {
+

2021-12-23 21:23 UTC, Pavel5926 commented on 3-PopovPavel-D14-Test/test.cpp
> +	FILE* in = fopen("D:\\repos\\alg-dstruct\\3-PopovPavel-D14\\SudokuIn.txt", "r");
+

2021-12-23 21:23 UTC, Pavel5926 commented on 3-PopovPavel-D14-Test/test.cpp
> +	fseek(out, 0, SEEK_SET);
+

2021-12-23 21:24 UTC, Pavel5926 commented on 3-PopovPavel-D14/lab_sudoku.c
> +void PrintMatrix(FILE* out, int** matrix, int dimension) {
Поправил в .с файле в 163 строчке

2021-12-23 21:24 UTC, Pavel5926 commented on 3-PopovPavel-D14/lab_sudoku.c
> +	int small_dimension = 0;
+

2021-12-26 13:01 UTC, maik-nack reviewed
Ок, лабораторная зачтена!

2021-12-26 13:01 UTC, closed without merging