3-ChaikovskiNikolai-D19
motorny/alg-dstruct pull request #181
Opened 2021-12-06 19:27 UTC by nikolaichay

# Чек-лист для сдачи лабораторной

Список для проверки того, что вы ничего не забыли перед тем, как сдать лабораторную.

- [ ] Создан файл ридми с текстом задания лабораторной
- [ ] Директория с лабораторной называется согласно паттерну `<group_number>-<NameSurname>-<lab_variant>` (Пример: `1-NikitaLanskov-A26`). Это важно, такое название позволяет автоматически назначить в ревью нужного человека.
- [ ] Создан файл .gitignore в директории с лабораторной, в котором перечислены все вспомогательные файлы от visual studio
- [ ] В Pull Request отсутсвуют лишние файлы: сторонние библиотеки, их исходный код, собранные бинарные файлы вашей программы, ваши конфигурационные файлы IDE. В большинстве случаев в PR будет не более 10-15 файлов
- [ ] В Pull Request включены файлы только относящиеся к текущей лабораторной. Чтобы лабы не смешивались, создавайте новую ветвь для каждой лабы
- [ ] Написаны юнит-тесты для всех функций, подлежащих тестированию согласно памятке
- [ ] Пройдены тесты в системе проверки (для второй лабораторной и выше)
- [ ] Код написан в едином стиле

# Дополнительные комментарии к решению

Тут вы можете добавить дополнительные пояснения к решению вашего варианта лабораторной.

Различные сравнения и прочее.

2021-12-11 20:46 UTC, maik-nack requested changes
Исправьте, пожалуйста, замечания

1. Определитесь, в каком стиле Вы называете переменные
2. Определитесь, как Вы проверяете значение указателя на `NULL`

2021-12-11 20:46 UTC, maik-nack commented on 3-ChaikovskiNikolai-D19/AlgosLaba4/VertexCover.c
> +graph_t* GraphRead(FILE* in,int* k) {
Пробел

2021-12-11 20:46 UTC, maik-nack commented on 3-ChaikovskiNikolai-D19/AlgosLaba4/VertexCover.c
> +		return NULL;
Здесь будет утечка памяти

2021-12-11 20:46 UTC, maik-nack commented on 3-ChaikovskiNikolai-D19/AlgosLaba4/VertexCover.c
> +	while (fscanf(in, "%d %d\n", &first, &second)>0) {
Пробелы

2021-12-11 20:46 UTC, maik-nack commented on 3-ChaikovskiNikolai-D19/AlgosLaba4/VertexCover.c
> +		edge_t* edge=EdgeCreate(first, second);
Пробелы

2021-12-11 20:46 UTC, maik-nack commented on 3-ChaikovskiNikolai-D19/AlgosLaba4/VertexCover.c
> +		edge_t* edge=EdgeCreate(first, second);
Нет проверки возвращаемого значения

2021-12-11 20:46 UTC, maik-nack commented on 3-ChaikovskiNikolai-D19/AlgosLaba4/VertexCover.c
> +	ver=SearchRefurd(ver, m, graph, k);
Пробелы

2021-12-11 20:46 UTC, maik-nack commented on 3-ChaikovskiNikolai-D19/AlgosLaba4/VertexCover.c
> +int VertexCover(graph_t* graph, int k,FILE* out) {
Пробел

2021-12-11 20:46 UTC, maik-nack commented on 3-ChaikovskiNikolai-D19/AlgosLaba4/VertexCover.c
> +		if (Head->check ==0) {
Пробел

2021-12-11 20:46 UTC, maik-nack commented on 3-ChaikovskiNikolai-D19/AlgosLaba4/VertexCover.c
> +		free(ver);
Вы уже потеряли указатель на выделенную память

2021-12-11 20:46 UTC, maik-nack commented on 3-ChaikovskiNikolai-D19/AlgosLaba4/VertexCover.c
> +		for (int i = m+1; i <= graph->edges->size; i++) {
Пробелы

2021-12-11 20:46 UTC, maik-nack commented on 3-ChaikovskiNikolai-D19/AlgosLaba4/VertexCover.c
> +			ChangeInGraph(graph, -i);
А при этом вызове Вы не обнулите `check` у ребра, которое инцидентно одной из вершин `ver[0]`, ..., `ver[m - 1]`?

2021-12-11 20:46 UTC, maik-nack commented on 3-ChaikovskiNikolai-D19/TestLaba4/test.cpp
> +    const int maxNeighbourDelta = (int)(0.5*verticesCount);
Пробелы

2021-12-11 20:46 UTC, maik-nack commented on 3-ChaikovskiNikolai-D19/AlgosLaba4/VertexCover.h
> +int VertexCover(graph_t* graph, int k);
Нужна ещё функция, принимающая в качестве аргументов пути к входному и выходному файлам, и именно эта функция должна быть в тестах

2021-12-12 10:47 UTC, nikolaichay commented on 3-ChaikovskiNikolai-D19/AlgosLaba4/VertexCover.c
> +			ChangeInGraph(graph, -i);
ChangeInGraph прибавляет 1 или отнимает 1, в зависимости от входных данных. Другими словами, если вершина не вошла в вершинное покрытие, то check у всех соответствующих ребер уменьшится на 1. Если только эта вершина их покрывала, check станет равен 0, иначе не 0.

2021-12-23 18:16 UTC, maik-nack requested changes
Исправьте, пожалуйста, замечания

2021-12-23 18:16 UTC, maik-nack commented on 3-ChaikovskiNikolai-D19/TestLaba4/test.cpp
> +//TEST(StressTest, GraphCover) {
А зачем нагрузочный тест закомментировали?

2021-12-26 13:29 UTC, maik-nack requested changes
Исправьте, пожалуйста, замечание и сделайте так, чтобы тесты проходились

2021-12-26 13:29 UTC, maik-nack commented on 3-ChaikovskiNikolai-D19/TestLaba4/test.cpp
> +TEST(StressTest, GraphCover) {
В этом тесте тоже должна использоваться функция `VertexCoverFile`

2021-12-26 13:31 UTC, nikolaichay commented on 3-ChaikovskiNikolai-D19/TestLaba4/test.cpp
> +TEST(StressTest, GraphCover) {
Нужно ли, чтобы существовало покрытие?

2021-12-26 13:36 UTC, nikolaichay commented
Нужно ли, чтобы существовало покрытие в стресс-тесте?

2021-12-26 14:45 UTC, maik-nack commented on 3-ChaikovskiNikolai-D19/TestLaba4/test.cpp
> +TEST(StressTest, GraphCover) {
По желанию

2021-12-26 22:02 UTC, maik-nack reviewed
Ок, лабораторная зачтена!

2021-12-26 22:02 UTC, closed without merging