1-FilippovDenis-D27
motorny/alg-dstruct pull request #193
Opened 2021-12-11 00:25 UTC by AfellayDS

## Задание D27 "Расстановка ферзей"
Условие
   На шахматной доске размером NxN расставить N ферзей, так, чтобы не какие два не били
друг друга.

Исходные данные
   В текстовом файле input.txt записано число целое неотрицательное число N < 1000000.
Выведите в текстовый файл output.txt координаты ферзей – номер ряда и номер колонки,
начиная нумерацию с 0

2021-12-12 20:56 UTC, LanskovNV requested changes
1) В файле с тестами течет память, но это ладно, будем считать что это доп файл и вы на нем "расслабились") В основном блоке вроде все хорошо.
2) Я запустил вашу программу с `50000` - мне выдали memory allocation error стабильно.
На `100000` - программа просто вылетает. Запускаю я вашу программу на незагруженном компьютере с 16 гигабайтами оперативной памяти. В условии у вас ограничение на вход - какой-то жалкий миллион. Ладно, если программа долго работает, но падать она точно не должна на допустимом входе.

2021-12-13 00:39 UTC, AfellayDS commented
>2. Я запустил вашу программу с 50000 - мне выдали memory allocation error стабильно.
На 100000 - программа просто вылетает. Запускаю я вашу программу на незагруженном компьютере с 16 гигабайтами оперативной памяти. В условии у вас ограничение на вход - какой-то жалкий миллион. Ладно, если программа долго работает, но падать она точно не должна на допустимом входе

Проблема с выделением памяти возникала в функции CreateMatrix( ).

Архитектура x32, которая стоит в программе по умолчанию выделяет для типа данных size_t 32 бита. Ее максимальная величина ~ 4*10^9. Для создания матрицы требуется O(4n^2). В случае при N = 50000 для матрицы потребуется ~
5 * 10^4 * 5 * 10^4 * 4 = 10^10 байт = 10 Гб оперативной памяти. Уже в этом случает происходит целочисленное переполнение некоторых переменных, в том числе size_t size - которое хранит в себе размер динамического массива. 

В случае N=50000 ОС просто не выделяет память (size = 1,41 * 10^9), возвращается NULL. В случае N = 100000 память выделяется (size = 1,34 * 10^9), но затем при инициализации матрицы происходит запись в память, которая не была выделена программе, что вызывает ошибку "нарушение доступа".

Архитектура x64 выделяет для типа size_t 64 бита, и в заданных пределах N переполнение не возникает. Я немного изменил функцию CreateMatrix( )  и при такой архитектуре ОС выделяет память при N = 50000. Правда программа все равно выдает ошибку - переполнение стека вызовов из-за очень глубокой рекурсии.

При N = 100000 всегда приходит NULL, однако и ошибки записи в неинициализированную память не выдаются. Размер оперативной памяти моего ноутбука - 8 ГБ.

2021-12-15 20:20 UTC, LanskovNV requested changes
Добрый вечер, 
Изучил подробней вашу программу... Хотел попросить вас раскрыть рекурсию, но на самом деле это не так принципиально. В вашей программе метод выделения памяти под двумерный массив не совсем корректен. Тут опять возвращаемся к тому, что мы с вами обсуждали во второй лабораторной, а именно к различным размерам типов на разных архитектурах. В функции CreacteMatrix при использовании адресных операций делается неявное предположение, что размеры int и int* одинаковы, а это не так, из-за этого при больших размерностях возникают ошибки записи не в свою память.
Я попрошу вас переделать процесс выделения памяти под матрицу, чтобы он точно и явно работал, что-то в таком ключе проще всего:
```c
m->Elements = (int **) malloc(dim * sizeof(int *));
for (i = 0; i < dim; i++) {
    m->Elements[i] = malloc(dim * sizeof(int));
}
```
(Не забудьте про нужные проверки и соответствующие изменения при освобождении памяти)
В остальном ваш код написан хорошо и понятно!)

2021-12-16 20:22 UTC, AfellayDS commented
Здравствуйте, переделал функции выделения и освобождения динамической памяти для двумерного массива.

2021-12-20 10:30 UTC, LanskovNV approved these changes
Лабораторная зачтена

2021-12-20 13:25 UTC, closed without merging