3-ZinyakovaKate-E5
motorny/alg-dstruct pull request #212
Opened 2021-12-19 08:25 UTC by KateZin

# Чек-лист для сдачи лабораторной

Список для проверки того, что вы ничего не забыли перед тем, как сдать лабораторную.

- [ ] Создан файл ридми с текстом задания лабораторной
- [ ] Директория с лабораторной называется согласно паттерну `<group_number>-<NameSurname>-<lab_variant>` (Пример: `1-NikitaLanskov-A26`). Это важно, такое название позволяет автоматически назначить в ревью нужного человека.
- [ ] Создан файл .gitignore в директории с лабораторной, в котором перечислены все вспомогательные файлы от visual studio
- [ ] В Pull Request отсутсвуют лишние файлы: сторонние библиотеки, их исходный код, собранные бинарные файлы вашей программы, ваши конфигурационные файлы IDE. В большинстве случаев в PR будет не более 10-15 файлов
- [ ] В Pull Request включены файлы только относящиеся к текущей лабораторной. Чтобы лабы не смешивались, создавайте новую ветвь для каждой лабы
- [ ] Написаны юнит-тесты для всех функций, подлежащих тестированию согласно памятке
- [ ] Пройдены тесты в системе проверки (для второй лабораторной и выше)
- [ ] Код написан в едином стиле

# Дополнительные комментарии к решению

Тут вы можете добавить дополнительные пояснения к решению вашего варианта лабораторной.

Различные сравнения и прочее.

2021-12-24 10:15 UTC, maik-nack requested changes
Исправьте, пожалуйста, замечания

2021-12-24 10:15 UTC, maik-nack commented on 3-ZinyakovaKate-E5/3-ZinyakovaKate-E5/Functions.c
> +Tree* Insert(Tree* myTree, int val) {
В этой функции возможны утечки памяти

2021-12-24 10:15 UTC, maik-nack commented on 3-ZinyakovaKate-E5/3-ZinyakovaKate-E5/Functions.c
> +void FillWidth(Tree** myTree) {
А зачем Вам здесь двойной указатель?

2021-12-24 10:15 UTC, maik-nack commented on 3-ZinyakovaKate-E5/StressTestBinaryTree/test.cpp
> +}
По-хорошему, нужен ещё тест с деревом, в котором есть и положительные, и отрицательные числа

2021-12-24 10:15 UTC, maik-nack commented on 3-ZinyakovaKate-E5/StressTestBinaryTree/test.cpp
> +	tree = Insert(tree, 5);
Здесь и в других похожих местах может произойти утечка памяти

2021-12-24 17:07 UTC, KateZin commented on 3-ZinyakovaKate-E5/3-ZinyakovaKate-E5/Header.h
> +#define __HEADER_H_
выбрала

2021-12-24 17:07 UTC, KateZin commented on 3-ZinyakovaKate-E5/StressTestBinaryTree/test.cpp
> +TEST(FunctionalTest, CheckResult) {
добавила проверку

2021-12-24 17:07 UTC, KateZin commented on 3-ZinyakovaKate-E5/StressTestBinaryTree/test.cpp
> +	EXPECT_EQ((tree->right)->right->width, 2);
исправила

2021-12-24 17:08 UTC, KateZin commented on 3-ZinyakovaKate-E5/3-ZinyakovaKate-E5/Functions.c
> +Tree* Insert(Tree* myTree, int val) {
исправила

2021-12-24 17:08 UTC, KateZin commented on 3-ZinyakovaKate-E5/3-ZinyakovaKate-E5/Functions.c
> +void FillWidth(Tree** myTree) {
и правда не нужен.... исправила

2021-12-24 17:08 UTC, KateZin commented on 3-ZinyakovaKate-E5/StressTestBinaryTree/test.cpp
> +}
добавила

2021-12-24 17:08 UTC, KateZin commented on 3-ZinyakovaKate-E5/StressTestBinaryTree/test.cpp
> +	tree = Insert(tree, 5);
исправила

2021-12-25 21:35 UTC, maik-nack commented on 3-ZinyakovaKate-E5/3-ZinyakovaKate-E5/Functions.c
> +Tree* Insert(Tree* myTree, int val) {
Внутри функции `Insert` удалять всё дерево, если не получилось вставить какой-то элемент - плохое решение

2021-12-25 21:36 UTC, maik-nack requested changes
Исправьте функцию `Insert` и добавьте тестирование печати дерева с заполненной шириной в узлах

2021-12-26 11:30 UTC, KateZin commented
решила обойтись без функции Insert, в тестах заполняю вручную.
добавила тест печати.

2021-12-26 15:08 UTC, maik-nack requested changes
Исправьте, пожалуйста, замечание и добавьте в тесты проверку печати дерева с заполненной шириной в узлах

2021-12-26 15:08 UTC, maik-nack commented on 3-ZinyakovaKate-E5/3-ZinyakovaKate-E5/Header.h
> +	int ComparePrintResults(Tree* tree, char* resFile, char* myFile);
Функции, написанные для тестов, должны лежать там, где тесты

2021-12-26 23:00 UTC, maik-nack reviewed
Ок, лабораторная зачтена!

2021-12-26 23:00 UTC, closed without merging