3-PopovPavel-F22
motorny/alg-dstruct pull request #219
Opened 2021-12-20 16:12 UTC by Pavel5926

# Чек-лист для сдачи лабораторной

Список для проверки того, что вы ничего не забыли перед тем, как сдать лабораторную.

- [ ] Создан файл ридми с текстом задания лабораторной
- [ ] Директория с лабораторной называется согласно паттерну `<group_number>-<NameSurname>-<lab_variant>` (Пример: `1-NikitaLanskov-A26`). Это важно, такое название позволяет автоматически назначить в ревью нужного человека.
- [ ] Создан файл .gitignore в директории с лабораторной, в котором перечислены все вспомогательные файлы от visual studio
- [ ] В Pull Request отсутсвуют лишние файлы: сторонние библиотеки, их исходный код, собранные бинарные файлы вашей программы, ваши конфигурационные файлы IDE. В большинстве случаев в PR будет не более 10-15 файлов
- [ ] В Pull Request включены файлы только относящиеся к текущей лабораторной. Чтобы лабы не смешивались, создавайте новую ветвь для каждой лабы
- [ ] Написаны юнит-тесты для всех функций, подлежащих тестированию согласно памятке
- [ ] Пройдены тесты в системе проверки (для второй лабораторной и выше)
- [ ] Код написан в едином стиле

# Дополнительные комментарии к решению

Тут вы можете добавить дополнительные пояснения к решению вашего варианта лабораторной.

Различные сравнения и прочее.

2021-12-25 14:49 UTC, maik-nack requested changes
Исправьте, пожалуйста, замечания

1. Определитесь с тем, как Вы ставите пробелы после директивы `#include`.
2. Определитесь с тем, как Вы расставляете скобки при операторах условия.
3. В тестах возможны утечки памяти.
4. У Вас неверно реализовано удаление.
5. В тестах на удаление нужно как минимум проверить все 3 случая, которые возникают при удалении существующего узла.
6. Нет ни одного теста на проверку найденных отрезков, пересекающихся с данным.

2021-12-25 14:49 UTC, maik-nack commented on 3-PopovPavel-F22/Tree.c
> +	Intersect(tree->right, low, high);
Всегда ли нужно искать в правом поддереве?

2021-12-25 14:49 UTC, maik-nack commented on 3-PopovPavel-F22/Tree.c
> +tree_t* CreateModelTree(tree_t* tree) {
В этой функции возможны утечки памяти

2021-12-25 14:49 UTC, maik-nack commented on 3-PopovPavel-F22/Tree.c
> +		}
А что будет если нижние границы совпадут?

2021-12-25 14:49 UTC, maik-nack commented on 3-PopovPavel-F22/Tree.c
> +	int max[N];
А кто Вам сказал, что столько памяти хватит?

2021-12-25 14:49 UTC, maik-nack commented on 3-PopovPavel-F22/Tree.c
> +		memset(max, SMALLNUMBER, sizeof(int));
С чего Вы взяли, что значения меньше не будет?

2021-12-26 17:29 UTC, Pavel5926 commented on 3-PopovPavel-F22/TreeHeader.h
> +#pragma once
Исправил

2021-12-26 17:29 UTC, Pavel5926 commented on 3-PopovPavel-F22/Tree.c
> +//Function for tests
Исправил

2021-12-26 17:29 UTC, Pavel5926 commented on 3-PopovPavel-F22/Tree.c
> +tree_t* AddTree(tree_t* tree, int low, int high) {
Обсудили в телеграме

2021-12-26 17:29 UTC, Pavel5926 commented on 3-PopovPavel-F22/Tree.c
> +	Intersect(tree->right, low, high);
Да. В методичке опечатка. Там не должно быть else

2021-12-26 17:29 UTC, Pavel5926 commented on 3-PopovPavel-F22/Tree.c
> +tree_t* CreateModelTree(tree_t* tree) {
Поправил

2021-12-26 17:31 UTC, Pavel5926 commented on 3-PopovPavel-F22/Tree.c
> +		}
Выход из функции удаления с ошибкой по причине того, что такой ключ уже есть в дереве

2021-12-26 17:31 UTC, Pavel5926 commented on 3-PopovPavel-F22/Tree.c
> +		memset(max, SMALLNUMBER, sizeof(int));
работаем в int, взял по нижней границе. Исправил

2021-12-26 17:33 UTC, Pavel5926 commented on 3-PopovPavel-F22/Tree.c
> +	int max[N];
На самом деле хороший вопрос. Но я не сообразил, как это переделать, использовать realloc в рекурсии тяжко

2021-12-26 17:41 UTC, Pavel5926 commented on 3-PopovPavel-F22/TreeHeader.h
> +#pragma once
Все комменты сверху тоже поправил, удаление починил, тесты добавил.

2021-12-26 23:28 UTC, maik-nack requested changes

2021-12-26 23:28 UTC, maik-nack commented on 3-PopovPavel-F22/Tree.c
> +					tree->max = high;
То есть `max` нужно обновлять только если что-то добавили где-то слева?

2021-12-26 23:28 UTC, maik-nack commented on 3-PopovPavel-F22-TEST/test.cpp
> +TEST_F(DelTreeMemory, DeleteIntervalWithTwoSubtrees_returnsCorrectTree) {
Данный тест не проходится

2021-12-27 00:51 UTC, maik-nack reviewed
Ок, лабораторная зачтена!

2021-12-27 00:51 UTC, closed without merging