3-DikarevaMaria-D25
motorny/alg-dstruct pull request #220
Opened 2021-12-20 18:38 UTC by dikareva-me

# Чек-лист для сдачи лабораторной

Список для проверки того, что вы ничего не забыли перед тем, как сдать лабораторную.

- [ ] Создан файл ридми с текстом задания лабораторной
- [ ] Директория с лабораторной называется согласно паттерну `<group_number>-<NameSurname>-<lab_variant>` (Пример: `1-NikitaLanskov-A26`). Это важно, такое название позволяет автоматически назначить в ревью нужного человека.
- [ ] Создан файл .gitignore в директории с лабораторной, в котором перечислены все вспомогательные файлы от visual studio
- [ ] В Pull Request отсутсвуют лишние файлы: сторонние библиотеки, их исходный код, собранные бинарные файлы вашей программы, ваши конфигурационные файлы IDE. В большинстве случаев в PR будет не более 10-15 файлов
- [ ] В Pull Request включены файлы только относящиеся к текущей лабораторной. Чтобы лабы не смешивались, создавайте новую ветвь для каждой лабы
- [ ] Написаны юнит-тесты для всех функций, подлежащих тестированию согласно памятке
- [ ] Пройдены тесты в системе проверки (для второй лабораторной и выше)
- [ ] Код написан в едином стиле

# Дополнительные комментарии к решению

Тут вы можете добавить дополнительные пояснения к решению вашего варианта лабораторной.

Различные сравнения и прочее.

2021-12-20 18:52 UTC, dikareva-me commented
В файлах labd.h и sack.c автоматически ставит 4 пробела в качетсве отступа. Вижуалка делает это у меня в некоторых файлах, даже если я ставлю их как таб. Те же самые отступы в файле test.cpp отображаются как таб.

2021-12-20 19:00 UTC, dikareva-me commented
И еще, если что я не буду сдавать лабу E/F, на всякий случай говорю.

2021-12-25 21:06 UTC, maik-nack requested changes
Исправьте, пожалуйста, замечания и определитесь с тем, как Вы передаёте массивы в функции.

2021-12-25 21:06 UTC, maik-nack commented on 3-DikarevaMaria-D25/TestLabD/test.cpp
> +	for (int i = 0; i < ValsNumFOut; i++)
Если тестировать таким образом, то можно засчитать за верный ответ тот, в котором было больше чем `ValsNumFOut` чисел, но первые `ValsNumFOut` являются верным ответом

2021-12-25 21:06 UTC, maik-nack commented on 3-DikarevaMaria-D25/TestLabD/test.cpp
> +		"test_data/KSmallerMaxPrice/output.txt", correctResult, 1);
А почему 1?

2021-12-26 20:49 UTC, maik-nack requested changes
Исправьте, пожалуйста, замечание

2021-12-26 20:49 UTC, maik-nack commented on 3-DikarevaMaria-D25/Lab D/sack.c
> +    fscanf(input, "%d %ld %ld", &g_objectCount, &g_sackCapacity, &g_requiredPrice);
`long` и `int` занимают одинаковое количество байт и имеют одинаковые диапазоны. Поэтому я повторю вопрос, Вы уверены, что число из условия поместится в `int`?

2021-12-26 23:00 UTC, dikareva-me commented on 3-DikarevaMaria-D25/Lab D/sack.c
> +    fscanf(input, "%d %ld %ld", &g_objectCount, &g_sackCapacity, &g_requiredPrice);
Изменила на unsigned

2021-12-27 00:03 UTC, maik-nack reviewed
Ок, лабораторная зачтена!

2021-12-27 00:03 UTC, closed without merging