3-PustynnaiaJulia-D22
motorny/alg-dstruct pull request #229
Opened 2021-12-22 13:59 UTC by julie171

# Чек-лист для сдачи лабораторной

Список для проверки того, что вы ничего не забыли перед тем, как сдать лабораторную.

- [ ] Создан файл ридми с текстом задания лабораторной
- [ ] Директория с лабораторной называется согласно паттерну `<group_number>-<NameSurname>-<lab_variant>` (Пример: `1-NikitaLanskov-A26`). Это важно, такое название позволяет автоматически назначить в ревью нужного человека.
- [ ] Создан файл .gitignore в директории с лабораторной, в котором перечислены все вспомогательные файлы от visual studio
- [ ] В Pull Request отсутсвуют лишние файлы: сторонние библиотеки, их исходный код, собранные бинарные файлы вашей программы, ваши конфигурационные файлы IDE. В большинстве случаев в PR будет не более 10-15 файлов
- [ ] В Pull Request включены файлы только относящиеся к текущей лабораторной. Чтобы лабы не смешивались, создавайте новую ветвь для каждой лабы
- [ ] Написаны юнит-тесты для всех функций, подлежащих тестированию согласно памятке
- [ ] Пройдены тесты в системе проверки (для второй лабораторной и выше)
- [ ] Код написан в едином стиле

# Дополнительные комментарии к решению

Тут вы можете добавить дополнительные пояснения к решению вашего варианта лабораторной.

Различные сравнения и прочее.

2021-12-26 09:39 UTC, maik-nack requested changes
Исправьте, пожалуйста, замечания и определитесь с тем, в каком стиле Вы называете переменные

2021-12-26 09:39 UTC, maik-nack commented on 3-Pustynnaia-Julia-D22/Test/test.cpp
> +TEST(StressTest, TheLongestWay_StressTest) {
Нет данных ни о времени, ни о памяти

2021-12-26 09:39 UTC, maik-nack commented on 3-Pustynnaia-Julia-D22/LabD22/LabD.c
> +int LabSolution(FILE* input, FILE* output) {
В этой функции возможны утечки памяти

2021-12-26 09:39 UTC, maik-nack commented on 3-Pustynnaia-Julia-D22/Test/test.cpp
> +
В тестах не используется функция `LabSolution`

2021-12-26 09:39 UTC, maik-nack commented on 3-Pustynnaia-Julia-D22/Test/test.cpp
> +
В тестах нет ни печати пути в файл, ни проверки напечатанного пути в файл

2021-12-26 09:39 UTC, maik-nack commented on 3-Pustynnaia-Julia-D22/LabD22/LabD.c
> +        FreeAllQueue(queue);
В функции печати не должно быть никаких изменений данных, которые печатаются

2021-12-26 09:39 UTC, maik-nack commented on 3-Pustynnaia-Julia-D22/LabD22/LabD.h
> +    int LabSolution(FILE* input, FILE* output);
На вход должны передаваться именно пути к файлам

2021-12-26 09:39 UTC, maik-nack commented on 3-Pustynnaia-Julia-D22/LabD22/LabD.c
> +void WriteQueue(FILE* stream, queue_t* queue, int* success) {
А зачем Вам тут нужен именно указатель на `success`?

2021-12-26 09:39 UTC, maik-nack commented on 3-Pustynnaia-Julia-D22/LabD22/LabD.c
> +            FreeWrongWay(queue, neighbList[neighborId], visited);
Здесь может возникнуть ошибка доступа к памяти

2021-12-26 09:39 UTC, maik-nack commented on 3-Pustynnaia-Julia-D22/LabD22/LabD.c
> +        while (ptr->next->value != vertex) {
А Вы не можете сразу сказать, где именно находится `vertex` в `queue`?

2021-12-26 17:34 UTC, julie171 commented on 3-Pustynnaia-Julia-D22/LabD22/LabD.c
> +        while (ptr->next->value != vertex) {
Могу, в конце очереди она находится
Но мне ведь нужен указатель на предыдущий элемент в очереди, а список односвяный
Без первого цикла не обойтись, всё остальное будет исправлено

2021-12-26 17:36 UTC, julie171 commented on 3-Pustynnaia-Julia-D22/LabD22/LabD.c
> +            FreeWrongWay(queue, neighbList[neighborId], visited);
Я исправила эту функцию
И в её конечном варианте я не могу найти ошибку, про которую Вы пишите
Надеюсь, я её исправила вместе с другим замечанием

2021-12-26 18:31 UTC, julie171 commented on 3-Pustynnaia-Julia-D22/Test/test.cpp
> +
Я надеюсь, я правильно поняла, что должна делать
LabSolution вызывает все остальные функции, а в функциональных тестах мы должны проверять лишь конечный результат, поэтому в них я буду вызывать только её, а затем смотреть, правильно ли всё записано в файле

2021-12-26 21:07 UTC, maik-nack requested changes
Исправьте, пожалуйста, замечания

2021-12-26 21:07 UTC, maik-nack commented on 3-Pustynnaia-Julia-D22/Test/test.cpp
> +TEST(StressTest, TheLongestWay_StressTest) {
В этом тесте тоже нужно использовать функцию `LabSolution`

2021-12-26 21:07 UTC, maik-nack commented on 3-Pustynnaia-Julia-D22/Test/test.cpp
> +    USED MEMORY: 100 KB
Неужели нельзя добиться более больших значений?

2021-12-26 22:24 UTC, julie171 commented on 3-Pustynnaia-Julia-D22/Test/test.cpp
> +    USED MEMORY: 100 KB
В задании сказано, что количество вершин меньше 1000
Поэтому я так и сделала
Сейчас сделаю побольше

2021-12-27 00:08 UTC, maik-nack reviewed
Ок, лабораторная зачтена!

2021-12-27 00:08 UTC, closed without merging