3-DikarevaMaria-A12
motorny/alg-dstruct pull request #23
Opened 2021-09-28 10:58 UTC by dikareva-me

# Чек-лист для сдачи лабораторной

Список для проверки того, что вы ничего не забыли перед тем, как сдать лабораторную.

- [ ] Создан файл ридми с текстом задания лабораторной
- [ ] Создан файл .gitignore в директории с лабораторной, в котором перечислены все вспомогательные файлы от visual studio
- [ ] В Pull Request отсутсвуют лишние файлы: сторонние библиотеки, их исходный код, собранные бинарные файлы вашей программы, ваши конфигурационные файлы IDE. В большинстве случаев в PR будет не более 10-15 файлов
- [ ] В Pull Request включены файлы только относящиеся к текущей лабораторной. Чтобы лабы не смешивались, создавайте новую ветвь для каждой лабы
- [ ] Написаны юнит-тесты для всех функций, подлежащих тестированию согласно памятке
- [ ] Пройдены тесты в системе проверки (для второй лабораторной и выше)
- [ ] Код написан в едином стиле

# Дополнительные комментарии к решению

Тут вы можете добавить дополнительные пояснения к решению вашего варианта лабораторной.

Различные сравнения и прочее.

2021-10-02 21:13 UTC, maik-nack requested changes
Исправьте, пожалуйста, комментарии.

1. Стиль кодирования нарушен: определитесь, как именно Вы ставите фигурные скобки в начале блока кода и как Вы записываете ветвление с одной командой. А также определитесь, что именно Вы используете: `NULL` или `nullptr`.
2. Выполняется много ненужных операций XOR вида `a ^ 0`, результаты которых заранее известны.
3. `init_list_test` - единственный тест в Вашем случае, в котором Вам можно использовать две функции. Во всех остальных тестах Вы обязаны использовать только одну из Вами написанных функций - ту, которую Вы тестируете.
4. Ни в одном тесте нет проверки на успешное выделение памяти. Используйте динамическое выделение памяти только в тесте на удаление элемента, и именно для удаляемого элемента выделяйте динамически память. Во всех остальных случаях рекомендуется использовать статическую память. При этом из-за динамического выделения памяти у Вас в тестах присутствуют утечки памяти.
5. Не все тесты написаны для поиска/удаления: нужно проверять элементы в начале, в середине и в конце.
6. Очень интересно узнать про недостаток `невозможность использования стандартного сборщика мусора`, особенно в аспекте языка C. 
7. Есть ли ещё какие-нибудь недостатки у XOR-связного списка по сравнению с двусвязным списком?

2021-10-03 21:01 UTC, dikareva-me commented
Постаралась исправить. Другой недостаток XOR связного списка по сравнению с двусвязным состоит в невозможности вычислить адрес следующего или предыдущего элемента, зная только адрес нынешнего. То есть, чтобы добавить или удалить элемент по адресу надо пройти весь список.

2021-10-05 14:12 UTC, maik-nack requested changes
Исправьте, пожалуйста, комментарии, и мы договоримся.

1. Вы так и не определились с записыванием ветвления с одной командой. В каких случаях Вы пишите фигурные скобки, в каких-то - нет, а бывает, что и условие, и команда записаны в одной строке.
2. В тестах на добавление присутствуют утечки памяти.
3. В некоторых тестах используются функции, которые не являются тестируемой функцией.
4. В тестах на удаление нет проверки на успешное выделение памяти.
5. Как хорошо, что Вы вспомнили про пустой список и список без элемента в тестах для `DeleteElementKey`. Добавьте их и к другим двум функциям удаления.

2021-10-07 15:47 UTC, maik-nack commented
В следующий раз используйте макросы `ASSERT_*` от GoogleTest вместо обычного `assert` в тестах.

2021-10-11 06:37 UTC, closed without merging