3-ChaikovskiNikolai-E5
motorny/alg-dstruct pull request #230
Opened 2021-12-22 15:33 UTC by nikolaichay

# Чек-лист для сдачи лабораторной

Список для проверки того, что вы ничего не забыли перед тем, как сдать лабораторную.

- [ ] Создан файл ридми с текстом задания лабораторной
- [ ] Директория с лабораторной называется согласно паттерну `<group_number>-<NameSurname>-<lab_variant>` (Пример: `1-NikitaLanskov-A26`). Это важно, такое название позволяет автоматически назначить в ревью нужного человека.
- [ ] Создан файл .gitignore в директории с лабораторной, в котором перечислены все вспомогательные файлы от visual studio
- [ ] В Pull Request отсутсвуют лишние файлы: сторонние библиотеки, их исходный код, собранные бинарные файлы вашей программы, ваши конфигурационные файлы IDE. В большинстве случаев в PR будет не более 10-15 файлов
- [ ] В Pull Request включены файлы только относящиеся к текущей лабораторной. Чтобы лабы не смешивались, создавайте новую ветвь для каждой лабы
- [ ] Код написан в едином стиле

# Дополнительные комментарии к решению

Тут вы можете добавить дополнительные пояснения к решению вашего варианта лабораторной.

Различные сравнения и прочее.

2021-12-25 17:52 UTC, maik-nack requested changes
Исправьте, пожалуйста, замечания

2021-12-25 17:52 UTC, maik-nack commented on 3-ChaikovskiNikolai-E5/AlgosLaba5/BinaryTree.c
> +tree_t* Insert(tree_t* tree, int val) {
В этой функции возможны утечки памяти

2021-12-25 17:52 UTC, maik-nack commented on 3-ChaikovskiNikolai-E5/AlgosLaba5/BinaryTree.c
> +void FillLen(tree_t** tree) {
В ширине нужно учитывать только данные. Не нужно считать ширину для ширины

2021-12-25 17:52 UTC, maik-nack commented on 3-ChaikovskiNikolai-E5/TestLaba5/test.cpp
> +	tree = Insert(tree, 20);
Здесь и в других похожих местах может произойти утечка памяти

2021-12-25 17:52 UTC, maik-nack commented on 3-ChaikovskiNikolai-E5/AlgosLaba5/BinaryTree.h
> +void FillLen(tree_t** tree);
Зачем Вам здесь двойной указатель?

2021-12-25 17:52 UTC, maik-nack commented on 3-ChaikovskiNikolai-E5/TestLaba5/test.cpp
> +}
По-хорошему, нужен ещё тест с деревом, в котором есть и положительные, и отрицательные числа

2021-12-25 17:52 UTC, maik-nack commented on 3-ChaikovskiNikolai-E5/TestLaba5/test.cpp
> +TEST(FunctionalTest, OnlyRoot) {
Ни в одном тесте нет проверки правильности напечатанного дерева

2021-12-26 08:10 UTC, nikolaichay commented on 3-ChaikovskiNikolai-E5/TestLaba5/test.cpp
> +TEST(FunctionalTest, OnlyRoot) {
Правильность печати проверять я не вижу смысла, т.к. там есть только одна проверка (на существования дерева) и используется только PrintTree и printf. Печать будет правильная, если заполнение ширины узлов верная. Именно это я и проверяю во всех тестах.

2021-12-26 08:36 UTC, nikolaichay commented on 3-ChaikovskiNikolai-E5/TestLaba5/test.cpp
> +TEST(FunctionalTest, OnlyRoot) {
Я добавил проверку на успешную печать.

2021-12-26 17:28 UTC, maik-nack requested changes
Допишите, пожалуйста, тесты

2021-12-26 17:28 UTC, maik-nack commented on 3-ChaikovskiNikolai-E5/TestLaba5/test.cpp
> +TEST(FunctionalTest, OnlyRoot) {
Когда Вам нужно написать тесты, Вы забываете то, что написано внутри функции - Вы знаете лишь то, что функция принимает на вход, и конечный результат работы функции. По заданию Вы должны написать функции, которые будут корректно заполнять узлы дополнительной информацией, а также при печати дерева печатать ширину под числами, хранящимися в узлах дерева. Таким образом, кроме проверки заполненной дополнительной информации Вы обязаны написать тесты, в которых будет проверяться напечатанное дерево с дополнительной информацией. Скажу ещё раз, при написании теста неизвестно, что написано внутри функции - известен лишь результат выполнения функции на переданном входе.

2021-12-26 17:30 UTC, nikolaichay commented
А как мне тестировать печать в поток? По заданию не сказано, что печать происходит в файл.

2021-12-26 23:40 UTC, maik-nack requested changes
Исправьте, пожалуйста, замечания

2021-12-26 23:40 UTC, maik-nack commented on 3-ChaikovskiNikolai-E5/AlgosLaba5/BinaryTree.h
> +void FillLen(tree_t** tree);
А объявление функции то не изменено

2021-12-26 23:40 UTC, maik-nack commented on 3-ChaikovskiNikolai-E5/AlgosLaba5/BinaryTree.h
> +int PrintTree(tree_t* tree, int n,FILE* in);
Пропал пробел

2021-12-27 05:53 UTC, maik-nack reviewed
Ок, лабораторная зачтена!

2021-12-27 05:53 UTC, closed without merging