3-PetroshenkoArtem-E4
motorny/alg-dstruct pull request #234
Opened 2021-12-23 18:16 UTC by Artem-Petroshenko

# Чек-лист для сдачи лабораторной

Список для проверки того, что вы ничего не забыли перед тем, как сдать лабораторную.

- [ ] Создан файл ридми с текстом задания лабораторной
- [ ] Директория с лабораторной называется согласно паттерну `<group_number>-<NameSurname>-<lab_variant>` (Пример: `1-NikitaLanskov-A26`). Это важно, такое название позволяет автоматически назначить в ревью нужного человека.
- [ ] Создан файл .gitignore в директории с лабораторной, в котором перечислены все вспомогательные файлы от visual studio
- [ ] В Pull Request отсутсвуют лишние файлы: сторонние библиотеки, их исходный код, собранные бинарные файлы вашей программы, ваши конфигурационные файлы IDE. В большинстве случаев в PR будет не более 10-15 файлов
- [ ] В Pull Request включены файлы только относящиеся к текущей лабораторной. Чтобы лабы не смешивались, создавайте новую ветвь для каждой лабы
- [ ] Написаны юнит-тесты для всех функций, подлежащих тестированию согласно памятке
- [ ] Пройдены тесты в системе проверки (для второй лабораторной и выше)
- [ ] Код написан в едином стиле

# Дополнительные комментарии к решению

Тут вы можете добавить дополнительные пояснения к решению вашего варианта лабораторной.

Различные сравнения и прочее.

2021-12-25 21:29 UTC, maik-nack requested changes
Исправьте, пожалуйста, замечания

2021-12-25 21:29 UTC, maik-nack commented on 3-Petroshenko-E4/LabE-Var4/LabE.h
> +int IntLen(int Number);
Эта функция нигде не используется

2021-12-25 21:29 UTC, maik-nack commented on 3-Petroshenko-E4/Functional_Tests/test.cpp
> +
Нет тестирования печати дерева с заполненной шириной в узлах

2021-12-25 23:56 UTC, Artem-Petroshenko commented on 3-Petroshenko-E4/Functional_Tests/test.cpp
> +
Я добавил тесты заполнения ширины, с уже заполненными числами ширины в узлах, но сейчас понял, что это не то, что вы хотите, отсюда вопрос: как мы тестируем функцию печати, поскольку в юнит тестах к первой лабораторной мы их не писали

2021-12-26 00:05 UTC, Artem-Petroshenko commented on 3-Petroshenko-E4/Functional_Tests/test.cpp
> +
В том плане, что именно, мы должны проверить, что функция печати выполнилась в принципе, или печатать в файл и сравнивать ожидаемый и полученный?

2021-12-26 09:24 UTC, Artem-Petroshenko commented on 3-Petroshenko-E4/Functional_Tests/test.cpp
> +
В общем, я сделал сравнение ожидаемого и полученного файлов

2021-12-26 18:07 UTC, maik-nack requested changes
Исправьте, пожалуйста, замечания

2021-12-26 18:07 UTC, maik-nack commented on 3-Petroshenko-E4/LabE-Var4/LabE.h
> +int CompareFilesTest(tree_t* Root, char* ExpectedFile, char* ResultFile);
Функции, которые были написаны для тестов, должны лежать рядом с тестами

2021-12-26 18:07 UTC, maik-nack commented on 3-Petroshenko-E4/Functional_Tests/test.cpp
> +
У Вас есть 4 различных дерева в тестах, поэтому для каждого из них напишите проверку печати после заполнения ширин в узлах

2021-12-26 23:44 UTC, maik-nack reviewed
Ок, лабораторная зачтена!

2021-12-26 23:44 UTC, closed without merging