3-TronyaginaAlexandra-F20
motorny/alg-dstruct pull request #236
Opened 2021-12-23 20:57 UTC by tronyaginaa

# Чек-лист для сдачи лабораторной

Список для проверки того, что вы ничего не забыли перед тем, как сдать лабораторную.

- [ ] Создан файл ридми с текстом задания лабораторной
- [ ] Директория с лабораторной называется согласно паттерну `<group_number>-<NameSurname>-<lab_variant>` (Пример: `1-NikitaLanskov-A26`). Это важно, такое название позволяет автоматически назначить в ревью нужного человека.
- [ ] Создан файл .gitignore в директории с лабораторной, в котором перечислены все вспомогательные файлы от visual studio
- [ ] В Pull Request отсутсвуют лишние файлы: сторонние библиотеки, их исходный код, собранные бинарные файлы вашей программы, ваши конфигурационные файлы IDE. В большинстве случаев в PR будет не более 10-15 файлов
- [ ] В Pull Request включены файлы только относящиеся к текущей лабораторной. Чтобы лабы не смешивались, создавайте новую ветвь для каждой лабы
- [ ] Написаны юнит-тесты для всех функций, подлежащих тестированию согласно памятке
- [ ] Пройдены тесты в системе проверки (для второй лабораторной и выше)
- [ ] Код написан в едином стиле

# Дополнительные комментарии к решению

Тут вы можете добавить дополнительные пояснения к решению вашего варианта лабораторной.

Различные сравнения и прочее.

2021-12-25 22:59 UTC, maik-nack requested changes
Исправьте, пожалуйста, замечания и определитесь с тем, как Вы проверяете указатель на `NULL`

2021-12-25 22:59 UTC, maik-nack commented on 3-TronyaginaAlexandra-F20/3-TronyaginaAlexandra-F20/Source.cpp
> +	myTree = createTree(key);
Отсутствует проверка возвращаемого значения

2021-12-25 22:59 UTC, maik-nack commented on 3-TronyaginaAlexandra-F20/3-TronyaginaAlexandra-F20/Source.cpp
> +	if (myTree->key <= key) {
Прочтите задание ещё раз и подумайте, что тут не так

2021-12-25 22:59 UTC, maik-nack commented on 3-TronyaginaAlexandra-F20/3-TronyaginaAlexandra-F20/test.cpp
> +
Проверьте пробелы в этом файле

2021-12-25 22:59 UTC, maik-nack commented on 3-TronyaginaAlexandra-F20/3-TronyaginaAlexandra-F20/test.cpp
> +		result =(int*) realloc(result, sizeof(int));
В этой строчке сразу две ошибки

2021-12-25 22:59 UTC, maik-nack commented on 3-TronyaginaAlexandra-F20/3-TronyaginaAlexandra-F20/test.cpp
> +TEST(FunctionalTest, kMin_Even) {
Тесты не запускаются!

2021-12-26 14:40 UTC, tronyaginaa commented on 3-TronyaginaAlexandra-F20/3-TronyaginaAlexandra-F20/Source.cpp
> +	if (myTree->key <= key) {
Если я верно поняла, то я печатала и К-й элемент тоже, а по условию нужно было печатать элементы с порядковыми номерами меньше. Это я исправила. Если ошибка в чем-то другом, могли бы Вы, пожалуйста, подсказать что именно стоит проверить.

2021-12-26 18:36 UTC, maik-nack reviewed
Ок, лабораторная зачтена!

2021-12-26 18:36 UTC, closed without merging