3-AnishchenkoMihail-E6
motorny/alg-dstruct pull request #242
Opened 2021-12-25 15:24 UTC by mshnschnko

# Чек-лист для сдачи лабораторной

Список для проверки того, что вы ничего не забыли перед тем, как сдать лабораторную.

- [ ] Создан файл ридми с текстом задания лабораторной
- [ ] Директория с лабораторной называется согласно паттерну `<group_number>-<NameSurname>-<lab_variant>` (Пример: `1-NikitaLanskov-A26`). Это важно, такое название позволяет автоматически назначить в ревью нужного человека.
- [ ] Создан файл .gitignore в директории с лабораторной, в котором перечислены все вспомогательные файлы от visual studio
- [ ] В Pull Request отсутсвуют лишние файлы: сторонние библиотеки, их исходный код, собранные бинарные файлы вашей программы, ваши конфигурационные файлы IDE. В большинстве случаев в PR будет не более 10-15 файлов
- [ ] В Pull Request включены файлы только относящиеся к текущей лабораторной. Чтобы лабы не смешивались, создавайте новую ветвь для каждой лабы
- [ ] Написаны юнит-тесты для всех функций, подлежащих тестированию согласно памятке
- [ ] Пройдены тесты в системе проверки (для второй лабораторной и выше)
- [ ] Код написан в едином стиле

# Дополнительные комментарии к решению

Тут вы можете добавить дополнительные пояснения к решению вашего варианта лабораторной.

Различные сравнения и прочее.

2021-12-26 13:17 UTC, mshnschnko commented
Возникли проблемы с назначением ревьюера из-за неправильного имени папки. Заметил и исправил только сегодня, работу отправил вчера около суток назад.

2021-12-26 19:50 UTC, maik-nack requested changes
Исправьте, пожалуйста, замечания

2021-12-26 19:50 UTC, maik-nack commented on 3-AnishchenkoMihail-E6/src/LabSolution.c
> +	fileText = malloc((size + 2) * sizeof(char));
Нет проверки возвращаемого значения

2021-12-26 19:50 UTC, maik-nack commented on 3-AnishchenkoMihail-E6/src/LabSolution.c
> +		recursErr = RECURSION_ERROR;
Здесь будет утечка памяти

2021-12-26 19:50 UTC, maik-nack commented on 3-AnishchenkoMihail-E6/src/LabSolution.c
> +		return NULL;
Здесь будет утечка памяти

2021-12-26 19:50 UTC, maik-nack commented on 3-AnishchenkoMihail-E6/src/LabSolution.c
> +		return NULL;
Здесь будет утечка памяти

2021-12-26 19:50 UTC, maik-nack commented on LAB_E6_TEST/test.cpp
> +    tree_t* tree = ReadBinaryTree("test_files/empty_tree/Input.txt");
Такого файла нет

2021-12-26 23:51 UTC, maik-nack requested changes
Исправьте, пожалуйста, замечание

2021-12-26 23:51 UTC, maik-nack commented on 3-AnishchenkoMihail-E6/src/LabSolution.c
> +		return NULL;
Уже лучше, но утечка памяти всё ещё возможна

2021-12-27 00:14 UTC, maik-nack requested changes

2021-12-27 00:14 UTC, maik-nack commented on 3-AnishchenkoMihail-E6/src/LabSolution.c
> +		return NULL;
Вот уже почти! У `left` ведь тоже могут быть `left` и `right`. А у них свои и т.д.

2021-12-27 00:24 UTC, maik-nack reviewed
Ок, лабораторная зачтена!

2021-12-27 00:25 UTC, closed without merging