laboratory work
motorny/alg-dstruct pull request #25
Opened 2021-09-28 18:24 UTC by AleksaMax24

# Чек-лист для сдачи лабораторной

Список для проверки того, что вы ничего не забыли перед тем, как сдать лабораторную.

- [ ] Создан файл ридми с текстом задания лабораторной
- [ ] Директория с лабораторной называется согласно паттерну `<group_number>-<NameSurname>-<lab_variant>` (Пример: `1-NikitaLanskov-A26`). Это важно, такое название позволяет автоматически назначить в ревью нужного человека.
- [ ] Создан файл .gitignore в директории с лабораторной, в котором перечислены все вспомогательные файлы от visual studio
- [ ] В Pull Request отсутсвуют лишние файлы: сторонние библиотеки, их исходный код, собранные бинарные файлы вашей программы, ваши конфигурационные файлы IDE. В большинстве случаев в PR будет не более 10-15 файлов
- [ ] В Pull Request включены файлы только относящиеся к текущей лабораторной. Чтобы лабы не смешивались, создавайте новую ветвь для каждой лабы
- [ ] Написаны юнит-тесты для всех функций, подлежащих тестированию согласно памятке
- [ ] Пройдены тесты в системе проверки (для второй лабораторной и выше)
- [ ] Код написан в едином стиле

# Дополнительные комментарии к решению

Тут вы можете добавить дополнительные пояснения к решению вашего варианта лабораторной.

Различные сравнения и прочее.

2021-09-28 18:27 UTC, AleksaMax24 commented
Алгоритмическая сложность программ O(n^2)

2021-09-29 15:43 UTC, ExpressFromSiberia requested changes
Исправьте пожалуйста комментарии и код, в соответствии с внесёнными исправлениями. Проверьте также, везде ли Вы проверяете возвращаемое значение функции malloc.
В тестах рекомендуется использовать память на стеке, т.е. без использования malloc, тогда вам не придётся волноваться об успехе выделения памяти, что влияет на проведение тестов. Динамическое выделение памяти стоит использовать только в тех тестах в которых проверяются функции в поведении которых ожидается очистка этой памяти.
В каждом тесте нужно использовать только одну функцию из библиотеки - ту, которую вы тестируете.
Проверьте стиль кодирования. Уделите внимание именованию функций, переменных и т.д.

2021-09-29 15:43 UTC, ExpressFromSiberia commented on 4-Maksimova-A19/19V/19V/nineteen.h
> +typedef struct LIST {
Эта структура является излишней при реализации двусвязного списка. Реализация двусвязного списка содержит только указатель на голову.  Принято считать указателем на список указатель на голову.

2021-09-29 15:43 UTC, ExpressFromSiberia commented on 4-Maksimova-A19/19V/19V/nineteen.h
> +typedef struct DATA {
Эта структура не имеет смысла при реализации списка. Это добавляет лишние операции и занимает лишнюю память.

2021-09-29 15:43 UTC, ExpressFromSiberia commented on 4-Maksimova-A19/19V/19V/nineteen.h
> +	char value[MAX_SIZE];
При работе со строками мы используем динамическую память для хранения информации. Память на стеке можно использовать для чтения из входного потока.

2021-09-29 15:43 UTC, ExpressFromSiberia commented on 4-Maksimova-A19/19V/19V/nineteen.h
> +#define LIST_SIZE 6
Это не несёт смысла при использовании, поэтому это нужно выносить в файл с тестами.

2021-10-02 21:31 UTC, ExpressFromSiberia requested changes
Вы не исправили все замечания. Проверьте ещё раз то, что я вас просил исправить в структурной части.

2021-10-05 13:35 UTC, ExpressFromSiberia commented on 4-Maksimova-A19/19V/19V/nineteen.c
> +  if (ne == NULL || ne->next != NULL)
Почему вы делаете проверку только следующего элемента?

2021-10-07 12:47 UTC, ExpressFromSiberia commented on 4-Maksimova-A19/19V/Sample-Test1/test (4).cpp
> +    LIST* list = createList("tmp");
Вы же тестируете функцию popFront. Почему вы используете здесь createList и для чего здесь вообще вызов функции set?

2021-10-07 12:48 UTC, ExpressFromSiberia commented on 4-Maksimova-A19/19V/19V/nineteen.c
> +int pushFront(LIST** list, LIST* newel) {
Приведите к единому стилю оформление функций. 
Либо вы их оформляете как 
func {
}
Либо как 
func
{
}

2021-10-07 12:49 UTC, ExpressFromSiberia requested changes
Исправьте комментарии.

2021-11-02 07:25 UTC, closed without merging