3-SalihovMagomet-B11
motorny/alg-dstruct pull request #267
Opened 2022-02-12 00:12 UTC by MagometS

# Чек-лист для сдачи лабораторной

Список для проверки того, что вы ничего не забыли перед тем, как сдать лабораторную.

- [x] Создан файл ридми с текстом задания лабораторной
- [x] Директория с лабораторной называется согласно паттерну `<group_number>-<NameSurname>-<lab_variant>` (Пример: `1-NikitaLanskov-A26`). Это важно, такое название позволяет автоматически назначить в ревью нужного человека.
- [x] Создан файл .gitignore в директории с лабораторной, в котором перечислены все вспомогательные файлы от visual studio
- [x] В Pull Request отсутсвуют лишние файлы: сторонние библиотеки, их исходный код, собранные бинарные файлы вашей программы, ваши конфигурационные файлы IDE. В большинстве случаев в PR будет не более 10-15 файлов
- [x] В Pull Request включены файлы только относящиеся к текущей лабораторной. Чтобы лабы не смешивались, создавайте новую ветвь для каждой лабы
- [x] Написаны юнит-тесты для всех функций, подлежащих тестированию согласно памятке
- [x] Пройдены тесты в системе проверки (для второй лабораторной и выше)
- [ ] Код написан в едином стиле

# Дополнительные комментарии к решению

Тут вы можете добавить дополнительные пояснения к решению вашего варианта лабораторной.

Различные сравнения и прочее.

2022-02-13 23:04 UTC, maik-nack requested changes
Исправьте, пожалуйста, замечания
1. Проверьте расстановку фигурных скобок
2. Определитесь со стилем названия переменных

2022-02-13 23:04 UTC, maik-nack commented on 3-SalihovMagomet-B11/memallocator.cc
> +	if (buffer_block->next != NULL)
В связи с чем возникает необходимость проверок ниже?

2022-02-15 23:14 UTC, MagometS commented on 3-SalihovMagomet-B11/memallocator.cc
> +				new_size = (char*)(head + 1) + fullSize - (char*)(free_block->prev + 1);
Это то же, что (char*)head + sizeof(descriptor_t). В блоке доступное для выделения памяти пространство лежит после дескриптора.

2022-02-16 00:13 UTC, MagometS commented on 3-SalihovMagomet-B11/memallocator.cc
> +	if (buffer_block->next != NULL)
Проверяем правильно ли размер блока записали, есть ли какая то память которую потеряли.

2022-02-16 10:03 UTC, maik-nack commented on 3-SalihovMagomet-B11/memallocator.cc
> +				new_size = (char*)(head + 1) + fullSize - (char*)(free_block->prev + 1);
Но в Вашем коде `fullSize` - это размер всего блока памяти, включая дескриптор для `head`

2022-02-16 10:05 UTC, maik-nack commented on 3-SalihovMagomet-B11/memallocator.cc
> +	if (buffer_block->next != NULL)
Я не спрашивал, что тут происходит. Я спрашивал, зачем Вы это делаете.

2022-02-16 23:09 UTC, MagometS commented on 3-SalihovMagomet-B11/memallocator.cc
> +	if (buffer_block->next != NULL)
Когда выделяем память, может остаться такой маленький кусочек, что туда не влезет дескриптор, соответственно указателя на него у нас нет. Тут мы проверяем есть ли такие кусочки памяти, и если есть присоединяем их к блоку.

2022-02-17 00:34 UTC, MagometS commented on 3-SalihovMagomet-B11/memallocator.cc
> +				new_size = (char*)(head + 1) + fullSize - (char*)(free_block->prev + 1);
Тогда надо просто head. Исправлю

2022-02-18 07:42 UTC, maik-nack commented on 3-SalihovMagomet-B11/memallocator.cc
> +	if (buffer_block->next != NULL)
Но тут же не выделяется память

2022-02-18 10:08 UTC, MagometS commented on 3-SalihovMagomet-B11/memallocator.cc
> +	if (buffer_block->next != NULL)
Память выделяется в мемаллоке, и когда она там выделяется может произойти, то что после выделения останется маленький кусочек в который не влез дескриптор. Так как дескриптор в него не влезает использовать его мы не можем и указателя на него нет, но при освобождении памяти мы можем этот кусочек прикрепить к блоку и избежать утечку.

2022-02-19 10:40 UTC, maik-nack reviewed
Ок, лабораторная зачтена!

2022-02-19 10:41 UTC, closed without merging