3-SalihovMagomet-F20
motorny/alg-dstruct pull request #289
Opened 2022-02-21 17:02 UTC by MagometS

# Чек-лист для сдачи лабораторной

Список для проверки того, что вы ничего не забыли перед тем, как сдать лабораторную.

- [ ] Создан файл ридми с текстом задания лабораторной
- [ ] Директория с лабораторной называется согласно паттерну `<group_number>-<NameSurname>-<lab_variant>` (Пример: `1-NikitaLanskov-A26`). Это важно, такое название позволяет автоматически назначить в ревью нужного человека.
- [ ] Создан файл .gitignore в директории с лабораторной, в котором перечислены все вспомогательные файлы от visual studio
- [ ] В Pull Request отсутсвуют лишние файлы: сторонние библиотеки, их исходный код, собранные бинарные файлы вашей программы, ваши конфигурационные файлы IDE. В большинстве случаев в PR будет не более 10-15 файлов
- [ ] В Pull Request включены файлы только относящиеся к текущей лабораторной. Чтобы лабы не смешивались, создавайте новую ветвь для каждой лабы
- [ ] Написаны юнит-тесты для всех функций, подлежащих тестированию согласно памятке
- [ ] Пройдены тесты в системе проверки (для второй лабораторной и выше)
- [ ] Код написан в едином стиле

# Дополнительные комментарии к решению

Тут вы можете добавить дополнительные пояснения к решению вашего варианта лабораторной.

Различные сравнения и прочее.

2022-02-21 21:33 UTC, maik-nack requested changes
Исправьте, пожалуйста, замечания

1. Определитесь с тем, как Вы проверяете нулевой указатель
2. Проверьте расстановку пробелов

2022-02-21 21:33 UTC, maik-nack commented on 3-SalihovMagomet-F20/test.cpp
> +
Нет теста с пустым файлом

2022-02-21 21:33 UTC, maik-nack commented on 3-SalihovMagomet-F20/labF.c
> +			return myTree;
Раз вы решили так сделать, то покажите, что умеете проверять, было ли дерево считано полностью. Не обязательно писать в коде - можно тут ответить в комментарии, как это можно сделать

2022-02-22 10:36 UTC, MagometS commented on 3-SalihovMagomet-F20/labF.c
> +			return myTree;
Можно внутри if написать сообщение, что мы полностью дерево не прочитали.

2022-02-22 10:41 UTC, MagometS commented on 3-SalihovMagomet-F20/labF.c
> +			return myTree;
Ну или можно с помощью fseek и ftell проверить весь ли мы файл считали.

2022-02-22 22:19 UTC, maik-nack requested changes
Исправьте, пожалуйста, замечания
1. Определитесь с тем, как Вы проверяете нулевой указатель
2. Проверьте расстановку пробелов

2022-02-22 22:19 UTC, maik-nack commented on 3-SalihovMagomet-F20/test.cpp
> +
Нет файла

2022-02-23 07:55 UTC, MagometS commented on 3-SalihovMagomet-F20/test.cpp
> +
Когда я пытаюсь загрузить пустые файлы, гит пишет: "This file is empty" и не загружает их

2022-02-23 08:48 UTC, maik-nack commented on 3-SalihovMagomet-F20/test.cpp
> +
У Ваших одногруппников получилось это сделать. Спросите у них как

2022-02-23 12:56 UTC, MagometS commented on 3-SalihovMagomet-F20/test.cpp
> +
Добавил

2022-02-24 16:42 UTC, maik-nack requested changes
Исправьте, пожалуйста, замечание

2022-02-24 16:42 UTC, maik-nack commented on 3-SalihovMagomet-F20/test.cpp
> +	LabSolution(input, output, 6);
Для пустого файла создаётся непустое дерево

2022-02-25 07:41 UTC, maik-nack commented on 3-SalihovMagomet-F20/test.cpp
> +	LabSolution(input, output, 6);
Ничего не изменилось

2022-02-25 12:09 UTC, MagometS commented on 3-SalihovMagomet-F20/test.cpp
> +	LabSolution(input, output, 6);
Ааа, я кажется понял, о чём вы говорите. Я добавил в ReadFile проверку что мы из файла что то считали.

2022-02-25 12:14 UTC, maik-nack reviewed
Ок, лабораторная зачтена!

2022-02-25 12:15 UTC, closed without merging