3-Rubanova-Valeria-H50
motorny/alg-dstruct pull request #301
Opened 2022-03-04 08:39 UTC by riapush

# Чек-лист для сдачи лабораторной

Список для проверки того, что вы ничего не забыли перед тем, как сдать лабораторную.

- [ ] Создан файл ридми с текстом задания лабораторной
- [ ] Директория с лабораторной называется согласно паттерну `<group_number>-<NameSurname>-<lab_variant>` (Пример: `1-NikitaLanskov-A26`). Это важно, такое название позволяет автоматически назначить в ревью нужного человека.
- [ ] Создан файл .gitignore в директории с лабораторной, в котором перечислены все вспомогательные файлы от visual studio
- [ ] В Pull Request отсутсвуют лишние файлы: сторонние библиотеки, их исходный код, собранные бинарные файлы вашей программы, ваши конфигурационные файлы IDE. В большинстве случаев в PR будет не более 10-15 файлов
- [ ] В Pull Request включены файлы только относящиеся к текущей лабораторной. Чтобы лабы не смешивались, создавайте новую ветвь для каждой лабы
- [ ] Написаны юнит-тесты для всех функций, подлежащих тестированию согласно памятке
- [ ] Пройдены тесты в системе проверки (для второй лабораторной и выше)
- [ ] Код написан в едином стиле

# Дополнительные комментарии к решению

Тут вы можете добавить дополнительные пояснения к решению вашего варианта лабораторной.

Различные сравнения и прочее.

2022-03-09 06:59 UTC, maik-nack requested changes
Исправьте, пожалуйста, замечания

1. Присутсвует утечка памяти.
2. Функции `solution` и `main` не относятся к реализации дерева.
3. Повторяется определение структуры.
4. Отсутствует сравнение времени работы операций с их аналогами в дереве бинарного поиска.

2022-03-29 19:55 UTC, maik-nack requested changes
Исправьте, пожалуйста, замечание

2022-03-29 19:55 UTC, maik-nack commented on 3-RubanovaValeria-H50/3-RubanovaValeria-H50/AA-tree.c
> +		bottom = (aa*)malloc(sizeof(aa));
До сих пор отсутствует возможность освобождения данной памяти, что неизбежно приводит к утечке памяти

2022-03-31 15:30 UTC, maik-nack requested changes

2022-04-01 09:40 UTC, riapush commented on 3-RubanovaValeria-H50/3-RubanovaValeria-H50/testing_system_file.c
> +#define _CRT_SECURE_NO_WARNINGS
отправила сейчас, все ок

2022-04-03 09:58 UTC, maik-nack requested changes
Исправьте, пожалуйста, замечание

2022-04-03 09:58 UTC, maik-nack commented on 3-RubanovaValeria-H50/3-RubanovaValeria-H50/AA-tree.c
> +		bottom = (aa*)malloc(sizeof(aa));
До сих пор отсутствует возможность освобождения памяти, выделенной в этой строчке!

2022-04-03 14:32 UTC, maik-nack requested changes

2022-04-03 14:32 UTC, maik-nack commented on 3-RubanovaValeria-H50/3-RubanovaValeria-H50/AA-tree.c
> +		bottom = (aa*)malloc(sizeof(aa));
Напишите любой тест с использованием `AA-tree.c` и `LabH.h` (кстати, правильней было бы назвать `AA-tree.h` тогда уж) и Вы сможете увидеть проблему, я надеюсь

2022-04-07 07:34 UTC, maik-nack reviewed
Ок, лабораторная зачтена

2022-04-07 07:34 UTC, closed without merging