3-ChibyshevTimofey-H20
motorny/alg-dstruct pull request #305
Opened 2022-03-08 22:29 UTC by Timofey-Chibyshev

# Чек-лист для сдачи лабораторной

Список для проверки того, что вы ничего не забыли перед тем, как сдать лабораторную.

- [ ] Создан файл ридми с текстом задания лабораторной
- [ ] Директория с лабораторной называется согласно паттерну `<group_number>-<NameSurname>-<lab_variant>` (Пример: `1-NikitaLanskov-A26`). Это важно, такое название позволяет автоматически назначить в ревью нужного человека.
- [ ] Создан файл .gitignore в директории с лабораторной, в котором перечислены все вспомогательные файлы от visual studio
- [ ] В Pull Request отсутсвуют лишние файлы: сторонние библиотеки, их исходный код, собранные бинарные файлы вашей программы, ваши конфигурационные файлы IDE. В большинстве случаев в PR будет не более 10-15 файлов
- [ ] В Pull Request включены файлы только относящиеся к текущей лабораторной. Чтобы лабы не смешивались, создавайте новую ветвь для каждой лабы
- [ ] Написаны юнит-тесты для всех функций, подлежащих тестированию согласно памятке
- [ ] Пройдены тесты в системе проверки (для второй лабораторной и выше)
- [ ] Код написан в едином стиле

# Дополнительные комментарии к решению

Тут вы можете добавить дополнительные пояснения к решению вашего варианта лабораторной.

Различные сравнения и прочее.

2022-03-15 07:59 UTC, maik-nack requested changes
Исправьте, пожалуйста, замечания

1. Различаются проверки указателя на NULL.
2. Различаются обозначения нулевого указателя.
3. Отсутствует сравнение времени работы операций с их аналогами в дереве бинарного поиска.
4. В `main.c` ожидается увидеть только `ReadingData` и `main`, а иначе зачем Вам заголовочный файл, название которого намекает на реализацию красно-чёрного дерева.

2022-03-15 07:59 UTC, maik-nack commented on 3-ChibyshevTimofey-H20/main.c
> +            return (current);
Зачем тут скобки?

2022-03-15 22:00 UTC, Timofey-Chibyshev commented
Сравнение времени работы операций с их аналогами в дереве бинарного поиска.
1)Давайте посмотрим, какой может быть максимальная глубина корректного красно-черного дерева с n вершинами.
Возьмем самый глубокий лист. Пусть он находится на глубине h. Из-за правила 1, как минимум половина вершин на пути из корня будет черными, то есть черная высота дерева будет не меньше h/2. Можно показать, что в таком дереве будет не менее 2^(h/2)-1 черных вершин (так как у каждой черной вершины с черной глубиной k, если она не лист, должно быть как минимум два потомка с черной глубиной k+1). Тогда 2^(h/2)-1 <= n или h<= 2*log2(n+1). Все основные операции с красно-черным деревом можно реализовать за O(h), то есть O(log n) по доказанному выше.
2) То есть в RBtree в плохих и средних случаях операции можно реализовать за O(log n), в бинарном же дереве в среднем те же O(log n), однако в худшем случае O(n). Следовательно, отличие в том, что RB-tree приблизительно сбалансировано, даже в худшем случае. В отличие от обычного бинарного дерева.

2022-03-23 21:15 UTC, maik-nack requested changes
Исправьте, пожалуйста, замечания

2022-03-23 21:15 UTC, maik-nack commented on 3-ChibyshevTimofey-H20/RBTree.h
> +    void ReadingData(Node* tree);
К реализации красно-чёрного дерева эта функция не имеет никакого отношения

2022-03-23 21:15 UTC, maik-nack commented on 3-ChibyshevTimofey-H20/main.c
> +int main(void)
В этой функции присутствуют утечки памяти

2022-03-23 21:18 UTC, maik-nack commented
> ```
>                           Сравнение времени работы операций с их аналогами в дереве бинарного поиска.
> ```
> 
> 1)Давайте посмотрим, какой может быть максимальная глубина корректного красно-черного дерева с n вершинами. Возьмем самый глубокий лист. Пусть он находится на глубине h. Из-за правила 1, как минимум половина вершин на пути из корня будет черными, то есть черная высота дерева будет не меньше h/2. Можно показать, что в таком дереве будет не менее 2^(h/2)-1 черных вершин (так как у каждой черной вершины с черной глубиной k, если она не лист, должно быть как минимум два потомка с черной глубиной k+1). Тогда 2^(h/2)-1 <= n или h<= 2*log2(n+1). Все основные операции с красно-черным деревом можно реализовать за O(h), то есть O(log n) по доказанному выше. 2) То есть в RBtree в плохих и средних случаях операции можно реализовать за O(log n), в бинарном же дереве в среднем те же O(log n), однако в худшем случае O(n). Следовательно, отличие в том, что RB-tree приблизительно сбалансировано, даже в худшем случае. В отличие от обычного бинарного дерева.

Что такое `правило 1`?

2022-03-24 17:28 UTC, Timofey-Chibyshev commented
правило 1: Ребенок красной вершины не может быть красной вершиной.

2022-03-27 11:42 UTC, maik-nack requested changes
Исправьте, пожалуйста, замечание

2022-03-27 11:42 UTC, maik-nack commented on 3-ChibyshevTimofey-H20/main.c
> +int main(void)
Утечки памяти как были, так и остались. Кроме того к ним добавилось возможное исключение о доступе к памяти.

2022-03-31 15:36 UTC, maik-nack requested changes
Проверьте расстановку пробелов

2022-04-03 09:59 UTC, maik-nack reviewed
Ок, лабораторная зачтена

2022-04-03 10:00 UTC, closed without merging