3-Eroshkin-H21
motorny/alg-dstruct pull request #317
Opened 2022-03-15 18:14 UTC by error228666

# Чек-лист для сдачи лабораторной

Список для проверки того, что вы ничего не забыли перед тем, как сдать лабораторную.

- [x] Создан файл ридми с текстом задания лабораторной
- [x] Директория с лабораторной называется согласно паттерну `<group_number>-<NameSurname>-<lab_variant>` (Пример: `1-NikitaLanskov-A26`). Это важно, такое название позволяет автоматически назначить в ревью нужного человека.
- [ ] Создан файл .gitignore в директории с лабораторной, в котором перечислены все вспомогательные файлы от visual studio
- [x] В Pull Request отсутсвуют лишние файлы: сторонние библиотеки, их исходный код, собранные бинарные файлы вашей программы, ваши конфигурационные файлы IDE. В большинстве случаев в PR будет не более 10-15 файлов
- [x] В Pull Request включены файлы только относящиеся к текущей лабораторной. Чтобы лабы не смешивались, создавайте новую ветвь для каждой лабы
- [ ] Написаны юнит-тесты для всех функций, подлежащих тестированию согласно памятке
- [x] Пройдены тесты в системе проверки (для второй лабораторной и выше)
- [x] Код написан в едином стиле

# Дополнительные комментарии к решению

Тут вы можете добавить дополнительные пояснения к решению вашего варианта лабораторной.

Различные сравнения и прочее.

2022-03-23 21:01 UTC, maik-nack requested changes
Исправьте, пожалуйста, замечания
1. Проверьте расстановку отступов.
2. Проверьте расстановку фигурных скобок.

2022-03-23 21:01 UTC, maik-nack commented on 3-Eroshkin-H21/main.c
> +RBTree* merge(RBTree* tree1, RBTree* tree2, int data)
За сколько работает данная операция?

2022-04-22 11:48 UTC, maik-nack requested changes
Исправьте, пожалуйста, замечания
1. Проверьте расстановку отступов.
2. Проверьте расстановку фигурных скобок.

2022-04-22 11:48 UTC, maik-nack commented on 3-Eroshkin-H21/main.c
> +void delete_tree(RBTree* node)
Ничего не изменилось

2022-04-22 11:48 UTC, maik-nack commented on 3-Eroshkin-H21/main.c
> +    RBTree* result = (RBTree*)malloc(sizeof(RBTree));
Отсутствует проверка возвращаеого значения

2022-04-22 11:48 UTC, maik-nack commented on 3-Eroshkin-H21/main.c
> +RBTree* megre_rbt(RBTree* t1, RBTree* t2, int k)
Скажите, предполагается ли возможность после вызова этой функции использовать деревья t1 и t2, не изменяя при этом итоговое дерево?

2022-04-24 11:43 UTC, error228666 commented on 3-Eroshkin-H21/main.c
> +RBTree* megre_rbt(RBTree* t1, RBTree* t2, int k)
Нет

2022-04-24 19:49 UTC, maik-nack commented on 3-Eroshkin-H21/main.c
> +	RBTree* t = node(t1->data, t1->color, t1->left, join_to_r(t1->right, t2, k));
Отсутствует проверка возвращаеого значения

2022-04-24 19:49 UTC, maik-nack commented on 3-Eroshkin-H21/main.c
> +void delete_tree(RBTree* node)
То, что Вы теперь написали, не имеет смысла и при этом добавяет новые исключения о доступе к памяти

2022-04-24 19:57 UTC, maik-nack commented on 3-Eroshkin-H21/main.c
> +	RBTree* t = node(t2->data, t2->color, join_to_l(t1, t2->left, k), t2->right);
Отсутствует проверка возвращаеого значения

2022-04-24 19:57 UTC, maik-nack commented on 3-Eroshkin-H21/main.c
> +RBTree* megre_rbt(RBTree* t1, RBTree* t2, int k)
Тогда укажите, почему возникают утечки памяти после использования этой функции и как можно было бы от них избавиться

2022-04-24 20:03 UTC, maik-nack requested changes
Исправьте, пожалуйста, замечания и проверьте расстановку фигурных скобок

2022-04-24 20:03 UTC, maik-nack commented on 3-Eroshkin-H21/main.c
> +		*
Что это означает?

2022-04-24 20:39 UTC, error228666 commented
Утечки памяти возникают из-за того что создаются новые узлы при вызове функции node
Чтобы утечек не было нужно по завершению программы удалять дерево , полученное в результате функции merge

2022-04-25 10:59 UTC, maik-nack commented on 3-Eroshkin-H21/main.c
> +void delete_tree(RBTree* node)
Отлично! А теперь осталось объединить то, что написано сейчас, с тем, что было в самом начале

2022-04-25 11:04 UTC, maik-nack commented on 3-Eroshkin-H21/main.c
> +RBTree* megre_rbt(RBTree* t1, RBTree* t2, int k)
> Утечки памяти возникают из-за того что создаются новые узлы при вызове функции node
Чтобы утечек не было нужно по завершению программы удалять дерево , полученное в результате функции merge

Очистка выделенной память после её использования - это действие, которое необходимо делать, чтобы избежать тривиальных утечек памяти во всей программе. Мы же говорим именно про функцию `merge`.

2022-04-25 21:13 UTC, error228666 commented on 3-Eroshkin-H21/main.c
> +RBTree* megre_rbt(RBTree* t1, RBTree* t2, int k)
Я не могу понять откуда там появляются утечки памяти
Только если в случаях когда не удается выделить память. Вы об этом?

2022-04-27 20:19 UTC, maik-nack commented on 3-Eroshkin-H21/main.c
> +RBTree* megre_rbt(RBTree* t1, RBTree* t2, int k)
Нет, я не об этом. Подумайте о том, как изменялся объём выделенной памяти при работе функции `merge`.

2022-04-29 07:40 UTC, maik-nack requested changes
Запрашиваю изменения, чтобы у Вас была возможность запросить ревью. Вам необходимо ещё исправить одну функцию, ответить в одной беседе и определиться со своим стилем кодирования.

2022-05-10 14:27 UTC, maik-nack requested changes

2022-05-10 14:27 UTC, maik-nack commented on 3-Eroshkin-H21/main.c
> +void delete_tree(RBTree* node)
Вы скажите, если у Вас `node != NIL`, то всегда ли можно обратиться к какому-либо полю `node`?

2022-05-10 14:27 UTC, maik-nack commented on 3-Eroshkin-H21/main.c
> +
> t->right = join_to_r(t1->right, t2, k);
	if (t->right == NULL)
		return NULL;
		
Какая здесь допущена типичная ошибка при работе с динамической памятью? Такая ошибка ещё бывает при использовании функции `realloc`.

2022-05-15 13:58 UTC, error228666 commented on 3-Eroshkin-H21/main.c
> +
Я потерял указатель на t->right и потом не смогу его очистить

2022-05-15 15:43 UTC, maik-nack reviewed
Ок, лабораторная зачтена

2022-05-15 15:44 UTC, closed without merging