3-ChaikovskiNikolai-H11
motorny/alg-dstruct pull request #324
Opened 2022-03-18 08:55 UTC by nikolaichay

# Чек-лист для сдачи лабораторной

Список для проверки того, что вы ничего не забыли перед тем, как сдать лабораторную.

- [ ] Создан файл ридми с текстом задания лабораторной
- [ ] Директория с лабораторной называется согласно паттерну `<group_number>-<NameSurname>-<lab_variant>` (Пример: `1-NikitaLanskov-A26`). Это важно, такое название позволяет автоматически назначить в ревью нужного человека.
- [ ] Создан файл .gitignore в директории с лабораторной, в котором перечислены все вспомогательные файлы от visual studio
- [ ] В Pull Request отсутсвуют лишние файлы: сторонние библиотеки, их исходный код, собранные бинарные файлы вашей программы, ваши конфигурационные файлы IDE. В большинстве случаев в PR будет не более 10-15 файлов
- [ ] В Pull Request включены файлы только относящиеся к текущей лабораторной. Чтобы лабы не смешивались, создавайте новую ветвь для каждой лабы
- [ ] Написаны юнит-тесты для всех функций, подлежащих тестированию согласно памятке
- [ ] Пройдены тесты в системе проверки (для второй лабораторной и выше)
- [ ] Код написан в едином стиле

# Дополнительные комментарии к решению

Тут вы можете добавить дополнительные пояснения к решению вашего варианта лабораторной.

Различные сравнения и прочее.

2022-03-18 08:55 UTC, nikolaichay commented
Тесты 100/100

2022-03-24 18:41 UTC, maik-nack requested changes
Исправьте, пожалуйста, замечания
1. Проверьте расстановку фигурных скобок.
2. Проверьте расстановку пробелов.
3. Различаются обозначения нулевого указателя.

2022-03-24 18:41 UTC, maik-nack commented on 3-ChaikovskiNikolai-H11/LabaH.c
> +node_t* SearchKey(node_t* p, int k) {
Не при всех путях выполнения функция возвращает результат

2022-03-24 18:41 UTC, maik-nack commented on 3-ChaikovskiNikolai-H11/LabaH.c
> +	return p;
Почему в этом случае не требуется делать балансировку?

2022-03-24 18:41 UTC, maik-nack commented on 3-ChaikovskiNikolai-H11/LabaH.c
> +node_t* SearchData(node_t* p, int data) {
В этой функции ошибка

2022-03-24 18:41 UTC, maik-nack commented on 3-ChaikovskiNikolai-H11/LabaH.c
> +int test() {
Должны использоваться функции для работы с данными

2022-03-24 18:41 UTC, maik-nack commented on 3-ChaikovskiNikolai-H11/LabaH.c
> +		sscanf(command, "%c%i%i\n", &ch, &key, &data);
Приведите пример входной строки

2022-03-24 18:41 UTC, maik-nack commented on 3-ChaikovskiNikolai-H11/LabaH.c
> +	node_t* fict = malloc(sizeof(node_t));
А можно ли выполнить слияние без выделения дополнительной памяти?

2022-03-25 09:09 UTC, nikolaichay commented on 3-ChaikovskiNikolai-H11/LabaH.c
> +int test() {
Не понял, в чем заключается ошибка.

2022-03-29 07:09 UTC, maik-nack requested changes
Исправьте, пожалуйста, замечания
1. Проверьте расстановку фигурных скобок.
2. Различаются обозначения нулевого указателя.

2022-03-29 07:09 UTC, maik-nack commented on 3-ChaikovskiNikolai-H11/LabaH.c
> +	return tmp;
А полученное дерево является сбалансированным?

2022-04-01 09:23 UTC, maik-nack requested changes

2022-04-01 09:23 UTC, maik-nack commented on 3-ChaikovskiNikolai-H11/LabaH.c
> +node_t* Merge(node_t* p, node_t* q) {
А Вы эту функцию тестировали?

2022-04-05 12:32 UTC, maik-nack requested changes

2022-04-05 12:32 UTC, maik-nack commented on 3-ChaikovskiNikolai-H11/LabaH.c
> +node_t* Merge(node_t* p, node_t* q) {
Ответа нет, но вижу, что одну ошибку в этой функции Вы исправили. Осталось исправить остальные

2022-04-11 20:08 UTC, maik-nack requested changes
Исправьте, пожалуйста, замечания и проверьте расстановку фигурных скобок.

2022-04-11 20:08 UTC, maik-nack commented on 3-ChaikovskiNikolai-H11/LabaH.c
> +node_t* Merge(node_t* p, node_t* q) {
А достаточно ли одной балансировки?

2022-04-11 22:54 UTC, nikolaichay commented
Убедительная просьба, проверить до занятия.

2022-04-12 00:30 UTC, nikolaichay commented
Извините, что еще раз исправил, нашел ошибку после отправки.
Проверьте до занятия

2022-04-19 08:13 UTC, maik-nack reviewed
Ок, лабораторная зачтена

2022-04-19 08:13 UTC, closed without merging