3-Zinyakova-I10
motorny/alg-dstruct pull request #327
Opened 2022-03-21 03:32 UTC by KateZin

# Чек-лист для сдачи лабораторной

Список для проверки того, что вы ничего не забыли перед тем, как сдать лабораторную.

- [ ] Создан файл ридми с текстом задания лабораторной
- [ ] Директория с лабораторной называется согласно паттерну `<group_number>-<NameSurname>-<lab_variant>` (Пример: `1-NikitaLanskov-A26`). Это важно, такое название позволяет автоматически назначить в ревью нужного человека.
- [ ] Создан файл .gitignore в директории с лабораторной, в котором перечислены все вспомогательные файлы от visual studio
- [ ] В Pull Request отсутсвуют лишние файлы: сторонние библиотеки, их исходный код, собранные бинарные файлы вашей программы, ваши конфигурационные файлы IDE. В большинстве случаев в PR будет не более 10-15 файлов
- [ ] В Pull Request включены файлы только относящиеся к текущей лабораторной. Чтобы лабы не смешивались, создавайте новую ветвь для каждой лабы
- [ ] Написаны юнит-тесты для всех функций, подлежащих тестированию согласно памятке
- [ ] Пройдены тесты в системе проверки (для второй лабораторной и выше)
- [ ] Код написан в едином стиле

# Дополнительные комментарии к решению

Тут вы можете добавить дополнительные пояснения к решению вашего варианта лабораторной.

Различные сравнения и прочее.

2022-03-31 15:05 UTC, maik-nack requested changes
Исправьте, пожалуйста, замечания
1. В пулл реквесте должны быть только файлы, относящиеся к данной лабораторной.
2. Отсутствуют проверки выделения памяти.

2022-04-09 12:25 UTC, KateZin commented on 3-Zinyakova-I10/Functions.c
> +void TransformNode(int value, int* keys, Tree* treeNode, Tree* first, Tree* second) {
Исправила

2022-04-09 12:25 UTC, KateZin commented on 3-Zinyakova-I10/Functions.c
> +    else if (value <= tree->keys[0]) {
Вы правы, в поиске нет смысла допускать равенства. Исправила

2022-04-09 12:25 UTC, KateZin commented on 3-Zinyakova-I10/Header.h
> +#pragma once
Изменила структуру файлов: теперь есть .h, .c и main

2022-04-09 12:26 UTC, KateZin commented on 3-Zinyakova-I10/Functions.c
> +void PrintTree(Tree* tree) {
Написала другую функцию

2022-04-09 12:26 UTC, KateZin commented
Удалила ненужные файлы
Добавила проверки памяти

2022-04-22 12:53 UTC, maik-nack requested changes

2022-04-22 12:53 UTC, maik-nack commented on 3-Zinyakova-I10/Functions.c
> +Tree* Split(Tree* item) {
В этой функции возможны утечки памяти

2022-04-25 11:17 UTC, maik-nack requested changes

2022-04-25 11:17 UTC, maik-nack commented on 3-Zinyakova-I10/Functions.c
> +Tree* Split(Tree* item) {
Изменение в нужном месте, но неверное

2022-04-27 20:21 UTC, maik-nack requested changes

2022-04-27 20:21 UTC, maik-nack commented on 3-Zinyakova-I10/Functions.c
> +Tree* Split(Tree* item) {
Скажем так, у функции `Split` нет полномочий очищать всё дерево

2022-05-12 11:26 UTC, maik-nack reviewed
Ок, лабораторная зачтена

2022-05-12 11:27 UTC, closed without merging