3-PustynnaiaJulia-H40
motorny/alg-dstruct pull request #330
Opened 2022-03-21 20:14 UTC by julie171

# Чек-лист для сдачи лабораторной

Список для проверки того, что вы ничего не забыли перед тем, как сдать лабораторную.

- [ ] Создан файл ридми с текстом задания лабораторной
- [ ] Директория с лабораторной называется согласно паттерну `<group_number>-<NameSurname>-<lab_variant>` (Пример: `1-NikitaLanskov-A26`). Это важно, такое название позволяет автоматически назначить в ревью нужного человека.
- [ ] Создан файл .gitignore в директории с лабораторной, в котором перечислены все вспомогательные файлы от visual studio
- [ ] В Pull Request отсутсвуют лишние файлы: сторонние библиотеки, их исходный код, собранные бинарные файлы вашей программы, ваши конфигурационные файлы IDE. В большинстве случаев в PR будет не более 10-15 файлов
- [ ] В Pull Request включены файлы только относящиеся к текущей лабораторной. Чтобы лабы не смешивались, создавайте новую ветвь для каждой лабы
- [ ] Написаны юнит-тесты для всех функций, подлежащих тестированию согласно памятке
- [ ] Пройдены тесты в системе проверки (для второй лабораторной и выше)
- [ ] Код написан в едином стиле

# Дополнительные комментарии к решению

Тут вы можете добавить дополнительные пояснения к решению вашего варианта лабораторной.

Различные сравнения и прочее.

2022-03-26 22:06 UTC, maik-nack requested changes
Исправьте, пожалуйста, замечания
1. Файлы с названиями `SplayTree.h` и `SplayTree.c` подразумевают реализацию скошенного дерева. В этих файлах не должно быть функций `Interface` и `main`.

2022-03-30 20:17 UTC, julie171 commented on 3-Pustynnaia-H40/LabH40/SplayTree.c
> +        FreeTree(root);
Здесь я проверяю возвращаемое из функции инициализации значение указателя
В случае ошибки с malloc необходимо очистить дерево и вернуть нулевой указатель
К сожалению, я не понимаю, что Вас смутило
Подскажите, пожалуйста

2022-03-31 15:10 UTC, maik-nack commented on 3-Pustynnaia-H40/LabH40/SplayTree.c
> +        FreeTree(root);
В пролшлом семестре неоднократно говорили о том, что функция вставки не должна очищать всю структуру при неудаче

2022-04-03 10:08 UTC, maik-nack reviewed
Ок, лабораторная зачтена

2022-04-03 10:08 UTC, closed without merging