3-DikarevaMaria-H20
motorny/alg-dstruct pull request #333
Opened 2022-03-23 20:10 UTC by dikareva-me

# Чек-лист для сдачи лабораторной

Список для проверки того, что вы ничего не забыли перед тем, как сдать лабораторную.

- [x] Создан файл ридми с текстом задания лабораторной
- [x] Директория с лабораторной называется согласно паттерну `<group_number>-<NameSurname>-<lab_variant>` (Пример: `1-NikitaLanskov-A26`). Это важно, такое название позволяет автоматически назначить в ревью нужного человека.
- [x] Создан файл .gitignore в директории с лабораторной, в котором перечислены все вспомогательные файлы от visual studio
- [x] В Pull Request отсутсвуют лишние файлы: сторонние библиотеки, их исходный код, собранные бинарные файлы вашей программы, ваши конфигурационные файлы IDE. В большинстве случаев в PR будет не более 10-15 файлов
- [x] В Pull Request включены файлы только относящиеся к текущей лабораторной. Чтобы лабы не смешивались, создавайте новую ветвь для каждой лабы
- [ ] Написаны юнит-тесты для всех функций, подлежащих тестированию согласно памятке
- [x] Пройдены тесты в системе проверки (для второй лабораторной и выше)
- [x] Код написан в едином стиле

# Дополнительные комментарии к решению

Тут вы можете добавить дополнительные пояснения к решению вашего варианта лабораторной.

Различные сравнения и прочее.

2022-03-26 23:03 UTC, maik-nack requested changes
Исправьте, пожалуйста, замечания
1. Различаются обозначения нулевого указателя.
2. Отсутствует сравнение времени работы операций с их аналогами в дереве бинарного поиска.
3. Проверьте расстановку отступов.

2022-03-27 16:49 UTC, dikareva-me commented
Сравнение времени работы с бинарным деревом:
В бинарном дереве поиск, удаление, добавление в худшем случае занимает О(n), в среднем - O(logn).
В красно-черном дереве поиск, удаление, добавление и в худшем, и в среднем случае занимает O(logn).

2022-03-30 13:28 UTC, maik-nack requested changes
Отправьте последнюю версию в систему проверки

2022-03-30 13:28 UTC, maik-nack commented on 3-DikarevaMaria-H20/Lab H/LabH.c
> +    if (noderoot == (*root))
Что это и зачем?

2022-04-07 07:48 UTC, maik-nack requested changes

2022-04-07 07:48 UTC, maik-nack commented on 3-DikarevaMaria-H20/Lab H/LabH.c
> +tree_t* Insert(tree_t* root, int data) {
В этой функции есть утечка памяти

2022-04-09 20:40 UTC, maik-nack reviewed
Ок, лабораторная зачтена

2022-04-09 20:41 UTC, closed without merging