3-KrasnikovRoman-I12
motorny/alg-dstruct pull request #350
Opened 2022-04-06 18:26 UTC by krasnikovra

# Чек-лист для сдачи лабораторной

Список для проверки того, что вы ничего не забыли перед тем, как сдать лабораторную.

- [ ] Создан файл ридми с текстом задания лабораторной
- [ ] Директория с лабораторной называется согласно паттерну `<group_number>-<NameSurname>-<lab_variant>` (Пример: `1-NikitaLanskov-A26`). Это важно, такое название позволяет автоматически назначить в ревью нужного человека.
- [ ] Создан файл .gitignore в директории с лабораторной, в котором перечислены все вспомогательные файлы от visual studio
- [ ] В Pull Request отсутсвуют лишние файлы: сторонние библиотеки, их исходный код, собранные бинарные файлы вашей программы, ваши конфигурационные файлы IDE. В большинстве случаев в PR будет не более 10-15 файлов
- [ ] В Pull Request включены файлы только относящиеся к текущей лабораторной. Чтобы лабы не смешивались, создавайте новую ветвь для каждой лабы
- [ ] Написаны юнит-тесты для всех функций, подлежащих тестированию согласно памятке
- [ ] Пройдены тесты в системе проверки (для второй лабораторной и выше)
- [ ] Код написан в едином стиле

# Дополнительные комментарии к решению

Тесты прошли на 100/100 с параметром B-дерева t = 3.

2022-05-02 13:06 UTC, maik-nack requested changes
Исправьте, пожалуйста, замечания

2022-05-03 10:43 UTC, krasnikovra commented on 3-Krasnikov-I12/src/main.c
> +Node* _NodeAllocate(const int t) {
В условии `if (!res->children)` нужно сначала очищать память под `res->keys`, а потом под `res`, а не наоборот

2022-05-03 10:46 UTC, krasnikovra commented on 3-Krasnikov-I12/src/main.c
> +            return false;
Нужно вернуть дереву старый корень, потому что после `_NodeDestroy(newRoot)` корень дерева окажется висячим указателем

2022-05-03 10:46 UTC, krasnikovra commented on 3-Krasnikov-I12/src/main.c
> +void _Destroy(Node* node, const int t) {
Параметр `t` здесь не нужен

2022-05-15 11:03 UTC, maik-nack reviewed
Ок, лабораторная зачтена!

2022-05-15 11:03 UTC, closed without merging