3-TronyaginaAlexandra-A26
motorny/alg-dstruct pull request #36
Opened 2021-10-03 18:50 UTC by tronyaginaa

# Чек-лист для сдачи лабораторной

Список для проверки того, что вы ничего не забыли перед тем, как сдать лабораторную.

- [ ] Создан файл ридми с текстом задания лабораторной
- [ ] Директория с лабораторной называется согласно паттерну `<group_number>-<NameSurname>-<lab_variant>` (Пример: `1-NikitaLanskov-A26`). Это важно, такое название позволяет автоматически назначить в ревью нужного человека.
- [ ] Создан файл .gitignore в директории с лабораторной, в котором перечислены все вспомогательные файлы от visual studio
- [ ] В Pull Request отсутсвуют лишние файлы: сторонние библиотеки, их исходный код, собранные бинарные файлы вашей программы, ваши конфигурационные файлы IDE. В большинстве случаев в PR будет не более 10-15 файлов
- [ ] В Pull Request включены файлы только относящиеся к текущей лабораторной. Чтобы лабы не смешивались, создавайте новую ветвь для каждой лабы
- [ ] Написаны юнит-тесты для всех функций, подлежащих тестированию согласно памятке
- [ ] Пройдены тесты в системе проверки (для второй лабораторной и выше)
- [ ] Код написан в едином стиле

# Дополнительные комментарии к решению

Строки в файле в формате: 2021-10-3 10

2021-10-04 22:12 UTC, maik-nack requested changes
Исправьте, пожалуйста, комментарии.

1. У Вас возникают утечки памяти из-за того, что Вы просто вызываете `exit(1)`. И ещё в одном другом месте есть утечка памяти (но это не про тесты).
2. Проверять возвращаемое значение `sscanf` необязательно, потому что в данных лабораторных мы считаем, что данные в файле записаны корректно.
3. Проверьте отступы и пробелы.
4. `deleteList` разрешено использовать только в тесте с `listInitialization`. И даже с `deleteList` у Вас есть утечки памяти в тестах.

2021-10-04 22:12 UTC, maik-nack commented on 3-TronyaginaAlexandra-A26/Sample-Tests_LAB1/test.cpp
> +	EXPECT_TRUE(head->temp < head->ptr->temp);
Нужно ещё проверить, что данные в элементах списка правильные (дата и температура).

2021-10-04 22:12 UTC, maik-nack commented on 3-TronyaginaAlexandra-A26/Sample-Tests_LAB1/test.cpp
> +TEST(averageTemperatureSearch, noElementsWAverageTemperature) {
Нужен ещё хотя бы один тест, а то создаётся впечатление, что функция `averageTemperatureSearch` может работать только для `0`.

2021-10-04 22:12 UTC, maik-nack commented on 3-TronyaginaAlexandra-A26/Sample-Tests_LAB1/test.cpp
> +TEST(readFile, normalFileFor3Elements) {
Либо добавьте ещё два теста:
- файл, в котором список написан в обратном порядке
- файл, в котором температуры располагаются случайно (можно из testFile.txt убрать несколько записей и использовать его)

либо сделайте так, чтобы список в файле test.txt был неотсортированным.

2021-10-07 19:52 UTC, maik-nack commented on 3-TronyaginaAlexandra-A26/Sample-Tests_LAB1/test.cpp
> +	ASSERT_FALSE(head == NULL);
А разве это не проверено выше?

2021-10-07 21:32 UTC, tronyaginaa commented
Исправила Ваши замечания. 
Если у меня все еще остались ошибки в оформлении кода, могли бы Вы, пожалуйста, подсказать, что именно я делаю не так. Спасибо!)

2021-10-10 08:18 UTC, maik-nack requested changes
Исправьте, пожалуйста, комментарии, и мы договоримся.

1. В двух местах не совпадает расстановка пробелов с остальными похожими местами.
2. В одном месте не совпадает размер отступа по сравнению со всеми остальными похожими местами.
3. Вызов функции `deleteList` нужно вынести из функции `push`.

2021-10-10 19:55 UTC, maik-nack reviewed
Ок, лабораторная зачтена!

2021-10-11 06:37 UTC, closed without merging