3-KopnovAlexandr-I11
motorny/alg-dstruct pull request #374
Opened 2022-04-17 13:37 UTC by Wumianzhe

# Чек-лист для сдачи лабораторной

Список для проверки того, что вы ничего не забыли перед тем, как сдать лабораторную.

- [ ] Создан файл ридми с текстом задания лабораторной
- [ ] Директория с лабораторной называется согласно паттерну `<group_number>-<NameSurname>-<lab_variant>` (Пример: `1-NikitaLanskov-A26`). Это важно, такое название позволяет автоматически назначить в ревью нужного человека.
- [ ] Создан файл .gitignore в директории с лабораторной, в котором перечислены все вспомогательные файлы от visual studio
- [ ] В Pull Request отсутсвуют лишние файлы: сторонние библиотеки, их исходный код, собранные бинарные файлы вашей программы, ваши конфигурационные файлы IDE. В большинстве случаев в PR будет не более 10-15 файлов
- [ ] В Pull Request включены файлы только относящиеся к текущей лабораторной. Чтобы лабы не смешивались, создавайте новую ветвь для каждой лабы
- [ ] Написаны юнит-тесты для всех функций, подлежащих тестированию согласно памятке
- [ ] Пройдены тесты в системе проверки (для второй лабораторной и выше)
- [ ] Код написан в едином стиле

# Дополнительные комментарии к решению

Тут вы можете добавить дополнительные пояснения к решению вашего варианта лабораторной.

Различные сравнения и прочее.

2022-05-11 22:09 UTC, maik-nack requested changes

2022-05-15 10:55 UTC, maik-nack commented on 3-Kopnov-I11/src/btree.c
> +void treePrint(tree_t* tree, int offset) {
Вот интересно получается: если узел не полный, то перед ключом ставится стрелка, а если узел полный, то ни одной стрелки нет. Почему именно так?

2022-05-19 17:43 UTC, Wumianzhe commented on 3-Kopnov-I11/src/btree.c
> +void treePrint(tree_t* tree, int offset) {
> Вот интересно получается: если узел не полный, то перед ключом ставится стрелка, а если узел полный, то ни одной стрелки нет. Почему именно так?

Так было сделано из-за того, что я не придумал, как поставить стрелку в середину узла. В целом идея как это сделать появилась, но уже что есть

2022-05-20 20:39 UTC, maik-nack reviewed
Ок, лабораторная зачтена!

2022-05-20 20:40 UTC, closed without merging