3-Petroshenko-I11
motorny/alg-dstruct pull request #378
Opened 2022-04-18 21:15 UTC by Artem-Petroshenko

17/100 in testing system(I don't know what's wrong)
Merge and Split is absent(I don't know how to write them)

# Чек-лист для сдачи лабораторной

Список для проверки того, что вы ничего не забыли перед тем, как сдать лабораторную.

- [ ] Создан файл ридми с текстом задания лабораторной
- [ ] Директория с лабораторной называется согласно паттерну `<group_number>-<NameSurname>-<lab_variant>` (Пример: `1-NikitaLanskov-A26`). Это важно, такое название позволяет автоматически назначить в ревью нужного человека.
- [ ] Создан файл .gitignore в директории с лабораторной, в котором перечислены все вспомогательные файлы от visual studio
- [ ] В Pull Request отсутсвуют лишние файлы: сторонние библиотеки, их исходный код, собранные бинарные файлы вашей программы, ваши конфигурационные файлы IDE. В большинстве случаев в PR будет не более 10-15 файлов
- [ ] В Pull Request включены файлы только относящиеся к текущей лабораторной. Чтобы лабы не смешивались, создавайте новую ветвь для каждой лабы
- [ ] Написаны юнит-тесты для всех функций, подлежащих тестированию согласно памятке
- [ ] Пройдены тесты в системе проверки (для второй лабораторной и выше)
- [ ] Код написан в едином стиле

# Дополнительные комментарии к решению

Тут вы можете добавить дополнительные пояснения к решению вашего варианта лабораторной.

Различные сравнения и прочее.

2022-05-15 10:48 UTC, maik-nack requested changes
Исправьте, пожалуйста, замечания и проверьте расстоновку фигурных скобок и отступов

2022-05-15 10:48 UTC, maik-nack commented on 3-Petroshenko-I11/LabI.c
> +tree_t* root(tree_t* node) {
Функция названа не в том стиле, что все остальные

2022-05-15 10:48 UTC, maik-nack commented on 3-Petroshenko-I11/LabI.c
> +				tree_t* next = InitNode(leftParent, lmax, left);
Отсутствует проверка возвращаемого значения

2022-05-15 10:48 UTC, maik-nack commented on 3-Petroshenko-I11/LabI.c
> +				tree_t* next = InitNode(rightParent, rightParent->key2, rightParent->mid);
Отсутствует проверка возвращаемого значения

2022-05-15 10:48 UTC, maik-nack commented on 3-Petroshenko-I11/LabI.h
> +#pragma once
Зачем Вам заголовочный файл, если все функции, включая функцию `main`, находятся в одном файле (в нём только структуры узла дерева нет)?

2022-05-15 12:31 UTC, Artem-Petroshenko commented on 3-Petroshenko-I11/LabI.h
> +#pragma once
Изначально в LabI.c не было main, я его добавил для тестов. Сейчас main можно удалить

2022-05-18 08:11 UTC, maik-nack reviewed
Ок, лабораторная зачтена

2022-05-18 08:12 UTC, closed without merging