3-ChibyshevTimofey-I11
motorny/alg-dstruct pull request #379
Opened 2022-04-18 21:25 UTC by Timofey-Chibyshev

# Чек-лист для сдачи лабораторной

Список для проверки того, что вы ничего не забыли перед тем, как сдать лабораторную.

- [ ] Создан файл ридми с текстом задания лабораторной
- [ ] Директория с лабораторной называется согласно паттерну `<group_number>-<NameSurname>-<lab_variant>` (Пример: `1-NikitaLanskov-A26`). Это важно, такое название позволяет автоматически назначить в ревью нужного человека.
- [ ] Создан файл .gitignore в директории с лабораторной, в котором перечислены все вспомогательные файлы от visual studio
- [ ] В Pull Request отсутсвуют лишние файлы: сторонние библиотеки, их исходный код, собранные бинарные файлы вашей программы, ваши конфигурационные файлы IDE. В большинстве случаев в PR будет не более 10-15 файлов
- [ ] В Pull Request включены файлы только относящиеся к текущей лабораторной. Чтобы лабы не смешивались, создавайте новую ветвь для каждой лабы
- [ ] Написаны юнит-тесты для всех функций, подлежащих тестированию согласно памятке
- [ ] Пройдены тесты в системе проверки (для второй лабораторной и выше)
- [ ] Код написан в едином стиле

# Дополнительные комментарии к решению

Тут вы можете добавить дополнительные пояснения к решению вашего варианта лабораторной.

Различные сравнения и прочее.

2022-04-18 21:26 UTC, Timofey-Chibyshev commented
Это вторая попытка, первая была в 00:00 , но я что-то сломал :(

2022-05-17 09:54 UTC, maik-nack requested changes
Исправьте, пожалуйста, замечания

При этом сделайте так, чтобы дерево стало 2-3+ деревом: у листьев должны быть ссылки на соседей для быстрого обхода дерева в порядке возрастания ключей. То есть листья должны образовывать односвязный список.

2022-05-17 09:54 UTC, maik-nack commented on 3-ChibyshevTimofey-I11/TreePlus.c
> +        Node* newRoot = NodeCreate();
Отсутствует проверка возвращаемого значения

2022-05-17 09:54 UTC, maik-nack commented on 3-ChibyshevTimofey-I11/full.c
> +            tree = Del(tree, key);
А это нормально, что если в дереве нет элемента с ключом `key`, Вы обнуляете указатель на корень дерева?

2022-05-17 09:54 UTC, maik-nack commented on 3-ChibyshevTimofey-I11/TreePlus.c
> +                root = p->sons[0];
А `p` удалять не нужно после этого?

2022-05-17 09:54 UTC, maik-nack commented on 3-ChibyshevTimofey-I11/TreePlus.c
> +                Del(v, x);
А почему этот вызов в итоге удалит `x` без утечек памяти?

2022-05-17 09:54 UTC, maik-nack commented on 3-ChibyshevTimofey-I11/TreePlus.c
> +        while (abs(hRight - GetHeight(v)) > 1) {
Ни один шаг данного цикла никогда не будет выполнен

2022-05-17 09:54 UTC, maik-nack commented on 3-ChibyshevTimofey-I11/TreePlus.c
> +        while (abs(hLeft - GetHeight(v)) > 1) {
Ни один шаг данного цикла никогда не будет выполнен

2022-05-17 09:54 UTC, maik-nack commented on 3-ChibyshevTimofey-I11/TreePlus.c
> +        r->sons[r->size] = l;
А зачем нужно `v`?

2022-05-17 09:54 UTC, maik-nack commented on 3-ChibyshevTimofey-I11/TreePlus.c
> +        l->sons[l->size] = r;
А зачем нужно `v`?

2022-05-17 09:54 UTC, maik-nack commented on 3-ChibyshevTimofey-I11/TreePlus.c
> +            v = v->sons[0];
А почему нужно спускаться по дереву влево?

2022-05-17 09:54 UTC, maik-nack commented on 3-ChibyshevTimofey-I11/TreePlus.c
> +SplitRetval Split(Node* t, int key) {
В этой функции присутствуют утечки памяти

2022-05-17 09:54 UTC, maik-nack commented on 3-ChibyshevTimofey-I11/TreePlus.c
> +SplitRetval Split(Node* t, int key) {
В этой функции отсутствуют проверки возвращаемых значений

2022-05-22 16:30 UTC, maik-nack reviewed
Ок, лабораторная зачтена

2022-05-22 16:30 UTC, closed without merging