3-TronyaginaAlexandra-I12
motorny/alg-dstruct pull request #383
Opened 2022-04-19 18:46 UTC by tronyaginaa

# Чек-лист для сдачи лабораторной

Список для проверки того, что вы ничего не забыли перед тем, как сдать лабораторную.

- [ ] Создан файл ридми с текстом задания лабораторной
- [ ] Директория с лабораторной называется согласно паттерну `<group_number>-<NameSurname>-<lab_variant>` (Пример: `1-NikitaLanskov-A26`). Это важно, такое название позволяет автоматически назначить в ревью нужного человека.
- [ ] Создан файл .gitignore в директории с лабораторной, в котором перечислены все вспомогательные файлы от visual studio
- [ ] В Pull Request отсутсвуют лишние файлы: сторонние библиотеки, их исходный код, собранные бинарные файлы вашей программы, ваши конфигурационные файлы IDE. В большинстве случаев в PR будет не более 10-15 файлов
- [ ] В Pull Request включены файлы только относящиеся к текущей лабораторной. Чтобы лабы не смешивались, создавайте новую ветвь для каждой лабы
- [ ] Написаны юнит-тесты для всех функций, подлежащих тестированию согласно памятке
- [ ] Пройдены тесты в системе проверки (для второй лабораторной и выше)
- [ ] Код написан в едином стиле

2022-05-15 12:41 UTC, maik-nack requested changes
Исправьте, пожалуйста, замечания

2022-05-15 12:41 UTC, maik-nack commented on 3-TronyaginaAlexandra-I12/LabI_source.cpp
> +        return;
Судя по Вашему коду, если данная функция не будет выполнена корректно, то функция, которая вызвала данную, всё равно выполнит всё правильно. Так ли это на самом деле?

2022-05-15 12:41 UTC, maik-nack commented on 3-TronyaginaAlexandra-I12/LabI_source.cpp
> +    if (tmp->childrens[0])
Я так понимаю, что таким образом Вы хотите проверять, является ли `tmp` листом. Зачем так делать, если у Вас есть `tmp->isLeaf`? Почему та проверка, которая написана у Вас, является корректной даже при условии, что при создании листа Вы не обнуляете эти указатели?

2022-05-15 12:41 UTC, maik-nack commented on 3-TronyaginaAlexandra-I12/README.md
> +Написать процедуры добавления в B дерево и его печати.
А где функция печати?

2022-05-20 22:37 UTC, tronyaginaa commented on 3-TronyaginaAlexandra-I12/LabI_source.cpp
> +        return;
Нет так быть не должнл. В функциях которые вызывали данную добавила проверку.

2022-05-20 22:39 UTC, tronyaginaa commented on 3-TronyaginaAlexandra-I12/LabI_source.cpp
> +    if (tmp->childrens[0])
"isLeaf" добавляла уже к концу работы над задачей, поэтому немного напутала с ним. Постаралась исправить все ошибки и добавить проверки на то является ли узел листом именно через "isLeaf".

2022-05-22 16:43 UTC, maik-nack reviewed
Ок, лабораторная зачтена

2022-05-22 16:44 UTC, closed without merging