3-BoitsovAnton-H11
motorny/alg-dstruct pull request #391
Opened 2022-04-27 12:32 UTC by d3biruwan

# Чек-лист для сдачи лабораторной

Список для проверки того, что вы ничего не забыли перед тем, как сдать лабораторную.

- [ ] Создан файл ридми с текстом задания лабораторной
- [ ] Директория с лабораторной называется согласно паттерну `<group_number>-<NameSurname>-<lab_variant>` (Пример: `1-NikitaLanskov-A26`). Это важно, такое название позволяет автоматически назначить в ревью нужного человека.
- [ ] Создан файл .gitignore в директории с лабораторной, в котором перечислены все вспомогательные файлы от visual studio
- [ ] В Pull Request отсутсвуют лишние файлы: сторонние библиотеки, их исходный код, собранные бинарные файлы вашей программы, ваши конфигурационные файлы IDE. В большинстве случаев в PR будет не более 10-15 файлов
- [ ] В Pull Request включены файлы только относящиеся к текущей лабораторной. Чтобы лабы не смешивались, создавайте новую ветвь для каждой лабы
- [ ] Написаны юнит-тесты для всех функций, подлежащих тестированию согласно памятке
- [ ] Пройдены тесты в системе проверки (для второй лабораторной и выше)
- [ ] Код написан в едином стиле

# Дополнительные комментарии к решению

Тут вы можете добавить дополнительные пояснения к решению вашего варианта лабораторной.

Различные сравнения и прочее.

2022-04-29 05:57 UTC, maik-nack requested changes
Исправьте, пожалуйста, замечания и проверьте расстановку пробелов

2022-04-29 05:57 UTC, maik-nack commented on 3-Boitsov-H11/src/solution.c
> +		node_t* temp_node = cur_branch;
А разве это нужно делать не в тот момент, когда высоты `cur_branch` и `left_tree` будут равны?

2022-04-29 05:57 UTC, maik-nack commented on 3-Boitsov-H11/src/solution.c
> +		if(prev_branch)
А что будет, если `prev_branch` - `NULL`?

2022-04-29 05:57 UTC, maik-nack commented on 3-Boitsov-H11/src/solution.c
> +node_t* merge(node_t* p, node_t* q) {
А возможно ли написать эту функцию так, чтобы не нужно было очищать память и снова её выделять?

2022-05-23 22:05 UTC, d3biruwan commented on 3-Boitsov-H11/src/solution.c
> +		node_t* temp_node = cur_branch;
По-моему, нужно учесть, что эти высоты могут не выровняться, а мое условие обеспечивает исполнение слияния и не нарушает условия балансировки для AVL дерева

2022-05-23 22:13 UTC, d3biruwan commented on 3-Boitsov-H11/src/solution.c
> +		if(prev_branch)
Если prev_branch - NULL, то это значит, что нам не нужно спускаться вниз по дереву и проводить балансировку на обратном пути, т.к. cur_branch- корень правого дерева, а rotate_point, соответственно,- корень нового.

2022-05-23 22:16 UTC, d3biruwan commented on 3-Boitsov-H11/README.md
> +в случае массивов - это поиск по ключу, который выполняется за О(1).  Единственным недостатком представления списка в виде AVL дерева является наличие рекурсий, что
Тут я немного запутался в формулировках. В массиве преимущество даст поиск k­го элемента по заданному k.

2022-05-23 22:31 UTC, d3biruwan commented on 3-Boitsov-H11/src/solution.c
> +int test(node_t* p) {
Как я понимаю, key для дерева- это порядковый номер элемента, а data- какие-то данные( то есть ключ для элементов списка).

2022-05-23 22:32 UTC, d3biruwan commented on 3-Boitsov-H11/README.md
> +в случае массивов - это поиск по ключу, который выполняется за О(1).  Единственным недостатком представления списка в виде AVL дерева является наличие рекурсий, что
Говоря "поиск по ключу" я имею в виду ключ в значении дерева

2022-05-25 07:00 UTC, maik-nack requested changes

2022-05-25 07:00 UTC, maik-nack commented on 3-Boitsov-H11/src/solution.c
> +int test(node_t* p) {
Так вот, Вы должны считать `data` (данные, которые кладёте в список), а не `key` (индекс элемента в списке). И положить в список именно то, что Вы считали, а не `1`. В какое мето класть - Вам решать. Самое простое в плане реализации - положить в конец списка.

2022-05-25 07:01 UTC, maik-nack commented on 3-Boitsov-H11/src/solution.c
> +		if(prev_branch)
И в итоге вместо корня нового дерева Вы возвращаете совсем не то

2022-05-25 16:53 UTC, maik-nack requested changes
Вы же видите, что тесты не все пройдены, значит, где-то ошибка. Как минимум в том, что и поиск, и удаление тоже нужно написать для данных!

2022-05-25 18:12 UTC, d3biruwan commented
Сделал поиск и удаление по data, но тесты проходит не на 100

2022-05-25 20:24 UTC, maik-nack commented on 3-Boitsov-H11/src/solution.c
> +		if(prev_branch)
Мы же выяснили, что проблема, когда `prev_branch` - `NULL`. Зачем же тогда менять место, где это не так?

2022-05-25 20:57 UTC, maik-nack requested changes
Последние тесты не проходят именно по времени. Для этого варианта это нормально. Давайте разберёмся с объединением списков.

2022-05-25 21:26 UTC, maik-nack reviewed
Ок, лабораторная зачтена

2022-05-25 21:26 UTC, closed without merging