3-DikarevaMaria-I11
motorny/alg-dstruct pull request #395
Opened 2022-05-01 16:07 UTC by dikareva-me

# Чек-лист для сдачи лабораторной

Список для проверки того, что вы ничего не забыли перед тем, как сдать лабораторную.

- [ ] Создан файл ридми с текстом задания лабораторной
- [ ] Директория с лабораторной называется согласно паттерну `<group_number>-<NameSurname>-<lab_variant>` (Пример: `1-NikitaLanskov-A26`). Это важно, такое название позволяет автоматически назначить в ревью нужного человека.
- [ ] Создан файл .gitignore в директории с лабораторной, в котором перечислены все вспомогательные файлы от visual studio
- [ ] В Pull Request отсутсвуют лишние файлы: сторонние библиотеки, их исходный код, собранные бинарные файлы вашей программы, ваши конфигурационные файлы IDE. В большинстве случаев в PR будет не более 10-15 файлов
- [ ] В Pull Request включены файлы только относящиеся к текущей лабораторной. Чтобы лабы не смешивались, создавайте новую ветвь для каждой лабы
- [ ] Написаны юнит-тесты для всех функций, подлежащих тестированию согласно памятке
- [ ] Пройдены тесты в системе проверки (для второй лабораторной и выше)
- [ ] Код написан в едином стиле

# Дополнительные комментарии к решению

Тут вы можете добавить дополнительные пояснения к решению вашего варианта лабораторной.

Различные сравнения и прочее.

2022-05-15 13:26 UTC, maik-nack requested changes

2022-05-15 13:26 UTC, maik-nack commented on 3-DikarevaMaria-I11/Lab_i/labi — копия.c
> +void PrintTree(tree_t* tree, int offset) {
Если узел не полный, то перед ключом ставится стрелка, а если узел полный, то ни одной стрелки нет. Почему именно так?

2022-05-21 10:39 UTC, dikareva-me commented on 3-DikarevaMaria-I11/Lab_i/labi — копия.c
> +void PrintTree(tree_t* tree, int offset) {
Если узел неполный, то стрелка ставится просто перед ключом узла, а если неполный, то надо поставить ее в середину узла. Однако в целом структура дерева при его печати понятна и без этой стрелки, а как ее сделать в середине узла я не придумала.

2022-05-22 16:51 UTC, maik-nack requested changes

2022-05-22 16:51 UTC, maik-nack commented on 3-DikarevaMaria-I11/Lab_i/labi — копия.c
> +void PrintTree(tree_t* tree, int offset) {
Во-первых, в случае полного узла наверное нужно поставить стрелку и в середине узла, и перед первым ключом.
А во-вторых, разве то, что Вы хотите, не делается изменением 431 строки?

2022-05-22 18:04 UTC, dikareva-me commented on 3-DikarevaMaria-I11/Lab_i/labi — копия.c
> +void PrintTree(tree_t* tree, int offset) {
Сделала по-другому печать дерева, теперь в полном узле стрелка указывает на первый ключ

2022-05-22 18:04 UTC, maik-nack reviewed
Ок, лабораторная зачтена

2022-05-22 18:04 UTC, closed without merging