3-Petroshenko-J25
motorny/alg-dstruct pull request #419
Opened 2022-05-15 12:55 UTC by Artem-Petroshenko

Got 83/100 in the testing system
Failed last 4 tests because of incorrect output

# Чек-лист для сдачи лабораторной

Список для проверки того, что вы ничего не забыли перед тем, как сдать лабораторную.

- [ ] Создан файл ридми с текстом задания лабораторной
- [ ] Директория с лабораторной называется согласно паттерну `<group_number>-<NameSurname>-<lab_variant>` (Пример: `1-NikitaLanskov-A26`). Это важно, такое название позволяет автоматически назначить в ревью нужного человека.
- [ ] Создан файл .gitignore в директории с лабораторной, в котором перечислены все вспомогательные файлы от visual studio
- [ ] В Pull Request отсутсвуют лишние файлы: сторонние библиотеки, их исходный код, собранные бинарные файлы вашей программы, ваши конфигурационные файлы IDE. В большинстве случаев в PR будет не более 10-15 файлов
- [ ] В Pull Request включены файлы только относящиеся к текущей лабораторной. Чтобы лабы не смешивались, создавайте новую ветвь для каждой лабы
- [ ] Написаны юнит-тесты для всех функций, подлежащих тестированию согласно памятке
- [ ] Пройдены тесты в системе проверки (для второй лабораторной и выше)
- [ ] Код написан в едином стиле

# Дополнительные комментарии к решению

Тут вы можете добавить дополнительные пояснения к решению вашего варианта лабораторной.

Различные сравнения и прочее.

2022-05-15 12:56 UTC, Artem-Petroshenko commented
Нужна помощь с последними 4мя тестами, не понимаю, где может быть ошибка в логике, есть предположение, что дело в функции `Resize`, но при своих тестах все правильно выводит.

2022-05-16 21:42 UTC, Artem-Petroshenko commented
Михаил, я убрал функцию `Resize` и стало 96/100, что для меня совершенно непонятно, почему...
Последний тест все также не проходится по причине неправильного вывода

2022-05-22 20:03 UTC, Artem-Petroshenko commented
Получил 100/100, увеличив размер таблицы, делать новый коммит пока не буду, изменю, вместе с правками,  если они будут

2022-05-23 17:41 UTC, maik-nack requested changes
Исправьте, пожалуйста, замечания

2022-05-23 17:41 UTC, maik-nack commented on 3-Petroshenko-J25/LabJ.c
> +		sscanf(lineBuffer, "%c%d", &action, &number);
То, что Вы считаете за число, должно быть строкой, которую нужно положить в таблицу

2022-05-23 17:41 UTC, maik-nack commented on 3-Petroshenko-J25/LabJ.c
> +void TableDestroy(HashTable* table, int index) {
А разве `index` бывает не равным `table->size`?

2022-05-25 06:20 UTC, maik-nack reviewed
Ок, лабораторная зачтена!

2022-05-25 06:21 UTC, closed without merging