First commit
motorny/alg-dstruct pull request #421
Opened 2022-05-15 13:55 UTC by error228666

# Чек-лист для сдачи лабораторной

Список для проверки того, что вы ничего не забыли перед тем, как сдать лабораторную.

- [ ] Создан файл ридми с текстом задания лабораторной
- [ ] Директория с лабораторной называется согласно паттерну `<group_number>-<NameSurname>-<lab_variant>` (Пример: `1-NikitaLanskov-A26`). Это важно, такое название позволяет автоматически назначить в ревью нужного человека.
- [ ] Создан файл .gitignore в директории с лабораторной, в котором перечислены все вспомогательные файлы от visual studio
- [ ] В Pull Request отсутсвуют лишние файлы: сторонние библиотеки, их исходный код, собранные бинарные файлы вашей программы, ваши конфигурационные файлы IDE. В большинстве случаев в PR будет не более 10-15 файлов
- [ ] В Pull Request включены файлы только относящиеся к текущей лабораторной. Чтобы лабы не смешивались, создавайте новую ветвь для каждой лабы
- [ ] Написаны юнит-тесты для всех функций, подлежащих тестированию согласно памятке
- [ ] Пройдены тесты в системе проверки (для второй лабораторной и выше)
- [ ] Код написан в едином стиле

# Дополнительные комментарии к решению

Тут вы можете добавить дополнительные пояснения к решению вашего варианта лабораторной.

Различные сравнения и прочее.

2022-05-18 07:48 UTC, maik-nack requested changes
Приведите к единому стилю расстановку отступов, пробелов и проверки на `NULL`. Также все комментарии в коде должны быть написаны на английском языке.

2022-05-18 07:48 UTC, maik-nack commented on 3-Eroshkin-I10/main.c
> +	else if (k <= tree->keys[0])
Почему при вставке допустимо равенство, а при поиске - нет?

2022-05-18 11:53 UTC, error228666 commented on 3-Eroshkin-I10/main.c
> +	else if (k <= tree->keys[0])
В случае вставки элемента, который уже есть, функция зайдет в иф и вернет дерево без изменений, поэтому случай равенства не имел смысла. Я его убрал

2022-05-20 20:31 UTC, maik-nack commented on 3-Eroshkin-I10/main.c
> +	else if (k <= tree->keys[0])
А для случая `tree->size == 2`?

2022-05-20 20:38 UTC, maik-nack requested changes
Проблемы с отсупами особенно заметны в функциях `insert_to_node` и `remove_from_node`, но проблемы есть не только там. Все комментарии в коде должны быть написаны на английском языке.

2022-05-23 21:33 UTC, maik-nack reviewed
Ок, лабораторная зачтена

2022-05-23 21:34 UTC, closed without merging