3-AnishchenkoMihail-J23
motorny/alg-dstruct pull request #430
Opened 2022-05-20 10:14 UTC by mshnschnko

# Чек-лист для сдачи лабораторной

Список для проверки того, что вы ничего не забыли перед тем, как сдать лабораторную.

- [ ] Создан файл ридми с текстом задания лабораторной
- [ ] Директория с лабораторной называется согласно паттерну `<group_number>-<NameSurname>-<lab_variant>` (Пример: `1-NikitaLanskov-A26`). Это важно, такое название позволяет автоматически назначить в ревью нужного человека.
- [ ] Создан файл .gitignore в директории с лабораторной, в котором перечислены все вспомогательные файлы от visual studio
- [ ] В Pull Request отсутсвуют лишние файлы: сторонние библиотеки, их исходный код, собранные бинарные файлы вашей программы, ваши конфигурационные файлы IDE. В большинстве случаев в PR будет не более 10-15 файлов
- [ ] В Pull Request включены файлы только относящиеся к текущей лабораторной. Чтобы лабы не смешивались, создавайте новую ветвь для каждой лабы
- [ ] Написаны юнит-тесты для всех функций, подлежащих тестированию согласно памятке
- [ ] Пройдены тесты в системе проверки (для второй лабораторной и выше)
- [ ] Код написан в едином стиле

# Дополнительные комментарии к решению

Тут вы можете добавить дополнительные пояснения к решению вашего варианта лабораторной.

Различные сравнения и прочее.

2022-05-20 10:15 UTC, mshnschnko commented
Не получается пройти последние 2 теста. Я думал, что на вход система подает очень длинные строки, но с увеличением размера строки ничего не изменялось, так что прошу помочь и дать комментарий

2022-05-24 10:02 UTC, maik-nack requested changes
Исправьте, пожалуйста, замечания и избавьтесь от утечек памяти из-за неправильной вставки или неправильного удаления

2022-05-24 10:02 UTC, maik-nack commented on 3-AnishchenkoMihail-J23/src/hash_23.c
> +int DeleteTable(Htable** ht) {
Данная функция не очищает таблицу полностью

2022-05-24 20:23 UTC, maik-nack requested changes
Исправьте функцию очистки таблицы и избавьтесь от утечек памяти из-за неправильной вставки или неправильного удаления

2022-05-25 06:26 UTC, maik-nack reviewed
Ок, лабораторная зачтена!

2022-05-25 06:27 UTC, closed without merging