3-TronyaginaAlexandra-J23
motorny/alg-dstruct pull request #433
Opened 2022-05-20 20:56 UTC by tronyaginaa

# Чек-лист для сдачи лабораторной

Список для проверки того, что вы ничего не забыли перед тем, как сдать лабораторную.

- [ ] Создан файл ридми с текстом задания лабораторной
- [ ] Директория с лабораторной называется согласно паттерну `<group_number>-<NameSurname>-<lab_variant>` (Пример: `1-NikitaLanskov-A26`). Это важно, такое название позволяет автоматически назначить в ревью нужного человека.
- [ ] Создан файл .gitignore в директории с лабораторной, в котором перечислены все вспомогательные файлы от visual studio
- [ ] В Pull Request отсутсвуют лишние файлы: сторонние библиотеки, их исходный код, собранные бинарные файлы вашей программы, ваши конфигурационные файлы IDE. В большинстве случаев в PR будет не более 10-15 файлов
- [ ] В Pull Request включены файлы только относящиеся к текущей лабораторной. Чтобы лабы не смешивались, создавайте новую ветвь для каждой лабы
- [ ] Написаны юнит-тесты для всех функций, подлежащих тестированию согласно памятке
- [ ] Пройдены тесты в системе проверки (для второй лабораторной и выше)
- [ ] Код написан в едином стиле

# Дополнительные комментарии к решению

Тут вы можете добавить дополнительные пояснения к решению вашего варианта лабораторной.

Различные сравнения и прочее.

2022-05-20 21:00 UTC, tronyaginaa commented
В тестовой системе не проходит два последних теста. Сокурсники, которые выполняли этот же вариант столкнулись с такой же проблей. 
Могли бы Вы, пожалуйста, подсказать в чем может быть ошибка (или где именно стоит ее искать)?

2022-05-24 10:13 UTC, maik-nack requested changes
Исправьте, пожалуйста, замечания

2022-05-24 10:13 UTC, maik-nack commented on 3-TronyaginaAlexandra-J23/LabJ_Source.c
> +    return res;
Данная функция никогда не должна возвращать число 0

2022-05-24 10:13 UTC, maik-nack commented on 3-TronyaginaAlexandra-J23/3-TronyaginaAlexandra-J23/main.c
> +    const int TABLE_SIZE = 100000;
Функция `Func2` должна выдавать взаимно простые с `TABLE_SIZE` числа

2022-05-24 10:13 UTC, maik-nack commented on 3-TronyaginaAlexandra-J23/LabJ_Source.c
> +        else if (table[x].status == NOT_FREE && strcmp(table[x].str, str) == 0)
Так же, как и у сокурсников, проблема скорее всего здесь. Представим, что мы вставляем некоторую строку `string`. Допустим, нам пришлось сделать `n` проб, чтобы найти наконец-то место в таблице, куда можно вставить данную строку. Далее мы удаляем какую-то другую строку, для которой функции `Func1` и `Func2` возвращают те же значения, что и для строки `string`. При этом нам понадобилось сделать, например, `n - 1` проб, чтобы найти эту строку в таблице. Теперь снова вставляем `string`. До этой строчки кода мы просто не дойдём, а новую строку вставим, хотя такая уже есть в таблице.

2022-05-24 10:13 UTC, maik-nack commented on 3-TronyaginaAlexandra-J23/3-TronyaginaAlexandra-J23/main.c
> +    free(table);
Лучше использовать `destroyTable`

2022-05-24 19:47 UTC, tronyaginaa commented on 3-TronyaginaAlexandra-J23/LabJ_Source.c
> +        else if (table[x].status == NOT_FREE && strcmp(table[x].str, str) == 0)
Спасибо большое! 
Разобралась и добавила в начале функции поиск такой же строки в таблице.

2022-05-24 19:50 UTC, tronyaginaa commented on 3-TronyaginaAlexandra-J23/LabJ_Source.c
> +    return res;
Если я правильно понимаю, такое может возникнуть только в случае, когда мы передаем пустую строку в функцию. Поэтому добавила в функциях, вызывающих данную, проверку на то, что передаваемая строка не пустая.

2022-05-24 20:26 UTC, maik-nack requested changes
Исправьте, пожалуйста, замечания

2022-05-24 20:26 UTC, maik-nack commented on 3-TronyaginaAlexandra-J23/LabJ_Source.c
> +    return res;
У Вас же написано `res %= size`. В этот момент `res` может обнулиться

2022-05-25 06:32 UTC, maik-nack requested changes
`hashFunction2` теперь не возвращает `0`, но может вернуть `size`. А `size` (значение которого равно `TABLE_SIZE`) и `TABLE_SIZE` - не взаимно простые числа.

2022-05-25 07:03 UTC, maik-nack commented on 3-TronyaginaAlexandra-J23/LabJ_Source.c
> +    int primeNum = 1230023; //TABLE_SIZE = 1230013
Тогда снова получается, что `res` может быть равен `TABLE_SIZE`

2022-05-25 16:26 UTC, maik-nack reviewed
Ок, лабораторная зачтена

2022-05-25 16:26 UTC, closed without merging