3-ChaikovskiNikolai-J22
motorny/alg-dstruct pull request #435
Opened 2022-05-21 13:33 UTC by nikolaichay

# Чек-лист для сдачи лабораторной

Список для проверки того, что вы ничего не забыли перед тем, как сдать лабораторную.

- [ ] Создан файл ридми с текстом задания лабораторной
- [ ] Директория с лабораторной называется согласно паттерну `<group_number>-<NameSurname>-<lab_variant>` (Пример: `1-NikitaLanskov-A26`). Это важно, такое название позволяет автоматически назначить в ревью нужного человека.
- [ ] Создан файл .gitignore в директории с лабораторной, в котором перечислены все вспомогательные файлы от visual studio
- [ ] В Pull Request отсутсвуют лишние файлы: сторонние библиотеки, их исходный код, собранные бинарные файлы вашей программы, ваши конфигурационные файлы IDE. В большинстве случаев в PR будет не более 10-15 файлов
- [ ] В Pull Request включены файлы только относящиеся к текущей лабораторной. Чтобы лабы не смешивались, создавайте новую ветвь для каждой лабы
- [ ] Написаны юнит-тесты для всех функций, подлежащих тестированию согласно памятке
- [ ] Пройдены тесты в системе проверки (для второй лабораторной и выше)
- [ ] Код написан в едином стиле

# Дополнительные комментарии к решению

Тут вы можете добавить дополнительные пояснения к решению вашего варианта лабораторной.

Различные сравнения и прочее.

2022-05-22 22:20 UTC, nikolaichay commented
Тесты 100/100

2022-05-23 21:21 UTC, maik-nack requested changes
В Вашем коде присутсвуют утечки памяти. Надо изменить алгоритмы вставки и/или удаления, чтобы от них избавиться.

2022-05-23 21:21 UTC, maik-nack commented on 3-ChaikovskiNikolai-J22/LabJ22.c
> +node* map;
Эта переменная не должна быть глобальной!

2022-05-23 21:21 UTC, maik-nack commented on 3-ChaikovskiNikolai-J22/LabJ22.c
> +node* map;
Эта переменная не должна быть глобальной!

2022-05-23 21:21 UTC, maik-nack commented on 3-ChaikovskiNikolai-J22/LabJ22.c
> +void Insert(const char* str) {
В этой функции отсутствуют проверки возвращаемых значений

2022-05-23 21:21 UTC, maik-nack commented on 3-ChaikovskiNikolai-J22/LabJ22.c
> +void Insert(const char* str) {
В этой функции отсутствуют проверки возвращаемых значений

2022-05-25 06:38 UTC, closed without merging