3-KopnovAlexander-A18
motorny/alg-dstruct pull request #7
Opened 2021-09-13 13:08 UTC by Wumianzhe

# Чек-лист для сдачи лабораторной

Список для проверки того, что вы ничего не забыли перед тем, как сдать лабораторную.

- [X] Создан файл ридми с текстом задания лабораторной
- [X] Создан файл .gitignore в директории с лабораторной, в котором перечислены все вспомогательные файлы от visual studio
- [X] В Pull Request отсутсвуют лишние файлы: сторонние библиотеки, их исходный код, собранные бинарные файлы вашей программы, ваши конфигурационные файлы IDE. В большинстве случаев в PR будет не более 10-15 файлов
- [X] В Pull Request включены файлы только относящиеся к текущей лабораторной. Чтобы лабы не смешивались, создавайте новую ветвь для каждой лабы
- [X] Написаны юнит-тесты для всех функций, подлежащих тестированию согласно памятке
- [ ] Пройдены тесты в системе проверки (для второй лабораторной и выше)
- [X] Код написан в едином стиле

# Дополнительные комментарии к решению

2021-09-18 08:52 UTC, maik-nack requested changes
Исправьте, пожалуйста, комментарии.

1. Код написан не в едином стиле. Обратите внимание на то, что Вы по-разному ставите пробелы в одинаковых случаях. Также стоит посмотреть на именования функций: большинство функций названы в lowerCamelCase, но не все.
2. Один тест - одна ситуация. Например, при проверки функции сортировки три различных ситуации проверяются в одном тесте - нужно разбить на три теста. И проверьте, что для каждой функции, которую вы тестируете, есть как все граничные случаи, так и 1-2 алгоритмических случая.
3. Не требуется использовать в тестах динамическое выделение памяти для данных, которые Вы используете для тестов. В противном случае Вам нужно проверять, что `malloc` будет возвращать не `NULL`. Делайте проще - используйте память, выделенную на стеке.
4. Нет теста для проверки сортировки списка строк. То, что работает сортировка списка целых чисел и компаратор для строк, не гарантирует работу сортировки списка строк.
5. Если уж Вы хотите хранить `void*`, то лучше Вам хранить и размер памяти, на которую указывает указатель, и передавать его в компаратор. Если работать с `void*`, то можно использовать функции `mem*` из стандартной библиотеки `string.h`. В противном случае лучше переписать на хранение `char*`.

2021-09-18 08:52 UTC, maik-nack commented on 3-Kopnov-A18/src/strlist.c
> +int strcmp(const char * str1, const char * str2) {
Я предполагаю, что это функция должна работать следующим образом:
1. если `str1` < `str2`, то возвращаемое значение будет меньше нуля;
2. если `str1` > `str2`, то возвращаемое значение будет больше нуля;
3. если `str1` = `str2`, то возвращаемое значение будет равно нулю.

На деле мы получаем, что функция работает следующим образом:
1. если `str1` != `str2`, то возвращаемое значение будет больше нуля;
2. если `str1` = `str2`, то возвращаемое значение будет равно нулю.

Пример:
```
strcmp("a", "")
  "a"[0] - ""[0] > 0
  // возвращаемое значение больше нуля

strcmp("", "a")
  ""[0] = 0
  "a"[0] != 0
  // возвращаемое значение больше нуля

strcmp("a", "a")
  "a"[0] - "a"[0] = 0
  "a"[1] = 0
  // возвращаемое значение равно нулю
```

Такая функция не годится для сортировки. Просто используйте функции из стандартной библиотеки `string.h`.

2021-09-18 08:52 UTC, maik-nack commented on 3-Kopnov-A18/tests/test.c
> +	// don't know how to test if memory is freed
Проверить очистку памяти можно по крайней мере двумя способами:
1. переопределить системные `malloc` и `free` и отслеживать количество выделенной и очищенной памяти;
2. если Вы используете Windows, то Вам доступна библиотека `crtdbg.h`, и Вы можете воспользоваться ею для проверки состояния памяти.

Но мы не требуем проверять состояние памяти, поэтому это не нужно делать.

2021-09-18 08:52 UTC, maik-nack commented on 3-Kopnov-A18/tests/test.c
> +	node_t* node=nodeCreate(data);
Странно, что в тесте на проверку создания списка есть `cr_assert_not_null`, а в этом тесте его нет.

2021-09-22 16:15 UTC, Wumianzhe commented on 3-Kopnov-A18/README.md
> +Я использую алгоритм сортировки вставками, имеющий сложность `O(n^2)`, где `n` размер массива, в котором используется функция сравнения строк, имеющая сложность `O(k)`, где `k` длина строки.
Использование алгоритма сортировки с лучшей алгоритмической сложностью, который не слишком сильно зависит от случайного доступа (merge sort, quicksort) или обеспечение случайного доступа к элементам (если считать размер списка постоянным во время сортировки, можно выделить массив указателей на элементы и отсортировать используя соответствующий компаратор, потом пересобрав список)

2021-09-22 16:24 UTC, Wumianzhe commented on 3-Kopnov-A18/src/list.c
> +		free(node->data);
Все варианты решения имеют свои минусы. Если не выделять память и не очищать память, если пользователь не хранит указатели он может обнаружить утечку памяти, если выделять и очищать, необходимо также передавать размер данных и каждое создание элемента будет включать в себя копирование.
К сожалению я не знаю способа указать данное поведение программными методами в С, помимо разделения на две функции.

2021-09-22 19:30 UTC, Wumianzhe commented on 3-Kopnov-A18/src/strlist.c
> +int strcmp(const char * str1, const char * str2) {
Функция возвращала ошибочное значение только если вторая строка длиннее первой (потерян -), но в любом случае уже не актуально поскольку используется стандартная функция

2021-09-23 08:45 UTC, maik-nack commented on 3-Kopnov-A18/src/list.c
> +		free(node->data);
> Если не выделять память и не очищать память, если пользователь не хранит указатели он может обнаружить утечку памяти

Это будет проблема пользователя, а не библиотеки, которую он использует. Поэтому Вам просто нужно выбрать один из двух вариантов реализации: либо Вы храните у себя указатель на копию, либо указатель на оригинал.

2021-09-25 20:31 UTC, maik-nack requested changes
Видно, что в большинстве случаев Вы решили просто удалить пробелы. В некоторых присваиваниях остались пробелы, хотя в большинстве присваиваниях их нет. 

Исправьте, пожалуйста, недочёты в стиле кодирования, и мы договоримся.

2021-09-25 20:31 UTC, maik-nack commented on 3-Kopnov-A18/src/strlist.c
> +void sortstrList(list_t *list) {
В отличие от остальных функций, название данной функции написано не в lowerCamelCase.

2021-09-26 08:59 UTC, maik-nack reviewed
Ок, лабораторная зачтена!

2021-10-11 06:36 UTC, closed without merging