3-PopovPavel-B15
motorny/alg-dstruct pull request #87
Opened 2021-10-28 18:39 UTC by Pavel5926

# Чек-лист для сдачи лабораторной

Список для проверки того, что вы ничего не забыли перед тем, как сдать лабораторную.

- [x] Создан файл ридми с текстом задания лабораторной
- [x] Директория с лабораторной называется согласно паттерну `<group_number>-<NameSurname>-<lab_variant>` (Пример: `1-NikitaLanskov-A26`). Это важно, такое название позволяет автоматически назначить в ревью нужного человека.
- [x] Создан файл .gitignore в директории с лабораторной, в котором перечислены все вспомогательные файлы от visual studio
- [x] В Pull Request отсутсвуют лишние файлы: сторонние библиотеки, их исходный код, собранные бинарные файлы вашей программы, ваши конфигурационные файлы IDE. В большинстве случаев в PR будет не более 10-15 файлов
- [x] В Pull Request включены файлы только относящиеся к текущей лабораторной. Чтобы лабы не смешивались, создавайте новую ветвь для каждой лабы
- [ ] Написаны юнит-тесты для всех функций, подлежащих тестированию согласно памятке
- [x] Пройдены тесты в системе проверки (для второй лабораторной и выше)
- [x] Код написан в едином стиле

# Дополнительные комментарии к решению

Тут вы можете добавить дополнительные пояснения к решению вашего варианта лабораторной.

Различные сравнения и прочее.

2021-10-31 13:25 UTC, maik-nack requested changes
Определитесь, пожалуйста, с тем, как Вы пишите условие с одной командой.

2021-10-31 13:25 UTC, maik-nack commented on 3-Popov-B15/memalloc_copy.cpp
> +			if (best_fit->size <= size + memgetminimumsize()) {
Функция `memgetminimumsize` возвращает сумму размеров дескриптора блока и дескриптора списка, а `memgetblocksize` - только размер дескриптора блока. Какая функция должна быть вызвана в этом случае?

2021-10-31 13:25 UTC, maik-nack commented on 3-Popov-B15/memalloc_copy.cpp
> +					if (first_free->next)
А разве `first_free->next` может быть `NULL`? Это же `new_free`.

2021-10-31 14:06 UTC, Pavel5926 commented on 3-Popov-B15/memalloc_copy.cpp
> +					if (first_free->next)
Убрал ненужное

2021-10-31 14:06 UTC, Pavel5926 commented on 3-Popov-B15/memalloc_copy.cpp
> +			if (best_fit->size <= size + memgetminimumsize()) {
memgetblocksize()

2021-10-31 14:06 UTC, Pavel5926 commented on 3-Popov-B15/memalloc_copy.cpp
> +			if (best_fit->size <= size + memgetminimumsize()) {
скобки тоже добавил в if. Теперь везде так:
if (..) {
...;
}

2021-10-31 20:57 UTC, maik-nack commented on 3-Popov-B15/memalloc_copy.cpp
> +					if (first_free->next)
А чуть ниже не такая же ситуация?

2021-10-31 21:24 UTC, Pavel5926 commented on 3-Popov-B15/memalloc_copy.cpp
> +					if (first_free->next)
Исправил

2021-11-01 08:36 UTC, maik-nack reviewed
Окей, лабораторная зачтена!

2021-11-01 08:36 UTC, closed without merging